### ISSUE TITLE
aws-sdk & dd-trace: uncaughtException: Cannot read property '_datadog' of undefined

### ISSUE THREAD

**Issue by zneel** [DataDog/dd-trace-js#1006]
**Describe the bug**
When using aws-sdk sqs and dd-trace v^0.22.0  it crashes:
```json
{
    "level": "error",
    "message": "uncaughtException: Cannot read property '_datadog' of undefined\nTypeError: Cannot read property '_datadog' of undefined\n    at Sqs.responseExtract (/home/elliotbouvier/workspace/ark/packages/lib-mmr-datadog/node_modules/dd-trace/packages/datadog-plugin-aws-sdk/src/services/sqs.js:24:76)\n    at Object.responseExtract (/home/elliotbouvier/workspace/ark/packages/lib-mmr-datadog/node_modules/dd-trace/packages/datadog-plugin-aws-sdk/src/helpers.js:61:36)\n    at Response.wrappedCb (/home/elliotbouvier/workspace/ark/packages/lib-mmr-datadog/node_modules/dd-trace/packages/datadog-plugin-aws-sdk/src/helpers.js:75:39)\n    at Request.<anonymous> (/home/elliotbouvier/workspace/ark/node_modules/aws-sdk/lib/request.js:364:18)\n    at Request.callListeners (/home/elliotbouvier/workspace/ark/node_modules/aws-sdk/lib/sequential_executor.js:106:20)\n    at Request.emit (/home/elliotbouvier/workspace/ark/node_modules/aws-sdk/lib/sequential_executor.js:78:10)\n    at Request.emit (/home/elliotbouvier/workspace/ark/node_modules/aws-sdk/lib/request.js:683:14)\n    at Request.transition (/home/elliotbouvier/workspace/ark/node_modules/aws-sdk/lib/request.js:22:10)\n    at AcceptorStateMachine.runTo (/home/elliotbouvier/workspace/ark/node_modules/aws-sdk/lib/state_machine.js:14:12)\n    at /home/elliotbouvier/workspace/ark/node_modules/aws-sdk/lib/state_machine.js:26:10\n    at Request.<anonymous> (/home/elliotbouvier/workspace/ark/node_modules/aws-sdk/lib/request.js:38:9)\n    at Request.<anonymous> (/home/elliotbouvier/workspace/ark/node_modules/aws-sdk/lib/request.js:685:12)\n    at Request.callListeners (/home/elliotbouvier/workspace/ark/node_modules/aws-sdk/lib/sequential_executor.js:116:18)\n    at Request.emit (/home/elliotbouvier/workspace/ark/node_modules/aws-sdk/lib/sequential_executor.js:78:10)\n    at Request.emit (/home/elliotbouvier/workspace/ark/node_modules/aws-sdk/lib/request.js:683:14)\n    at Request.transition (/home/elliotbouvier/workspace/ark/node_modules/aws-sdk/lib/request.js:22:10)",
    "metadata": {
        "error": {
            "message": "Cannot read property '_datadog' of undefined",
            "code": "TypeError",
            "time": "2020-07-01T08:47:38.428Z"
        },
        "stack": "TypeError: Cannot read property '_datadog' of undefined\n    at Sqs.responseExtract (/home/elliotbouvier/workspace/ark/packages/lib-mmr-datadog/node_modules/dd-trace/packages/datadog-plugin-aws-sdk/src/services/sqs.js:24:76)\n    at Object.responseExtract (/home/elliotbouvier/workspace/ark/packages/lib-mmr-datadog/node_modules/dd-trace/packages/datadog-plugin-aws-sdk/src/helpers.js:61:36)\n    at Response.wrappedCb (/home/elliotbouvier/workspace/ark/packages/lib-mmr-datadog/node_modules/dd-trace/packages/datadog-plugin-aws-sdk/src/helpers.js:75:39)\n    at Request.<anonymous> (/home/elliotbouvier/workspace/ark/node_modules/aws-sdk/lib/request.js:364:18)\n    at Request.callListeners (/home/elliotbouvier/workspace/ark/node_modules/aws-sdk/lib/sequential_executor.js:106:20)\n    at Request.emit (/home/elliotbouvier/workspace/ark/node_modules/aws-sdk/lib/sequential_executor.js:78:10)\n    at Request.emit (/home/elliotbouvier/workspace/ark/node_modules/aws-sdk/lib/request.js:683:14)\n    at Request.transition (/home/elliotbouvier/workspace/ark/node_modules/aws-sdk/lib/request.js:22:10)\n    at AcceptorStateMachine.runTo (/home/elliotbouvier/workspace/ark/node_modules/aws-sdk/lib/state_machine.js:14:12)\n    at /home/elliotbouvier/workspace/ark/node_modules/aws-sdk/lib/state_machine.js:26:10\n    at Request.<anonymous> (/home/elliotbouvier/workspace/ark/node_modules/aws-sdk/lib/request.js:38:9)\n    at Request.<anonymous> (/home/elliotbouvier/workspace/ark/node_modules/aws-sdk/lib/request.js:685:12)\n    at Request.callListeners (/home/elliotbouvier/workspace/ark/node_modules/aws-sdk/lib/sequential_executor.js:116:18)\n    at Request.emit (/home/elliotbouvier/workspace/ark/node_modules/aws-sdk/lib/sequential_executor.js:78:10)\n    at Request.emit (/home/elliotbouvier/workspace/ark/node_modules/aws-sdk/lib/request.js:683:14)\n    at Request.transition (/home/elliotbouvier/workspace/ark/node_modules/aws-sdk/lib/request.js:22:10)",
        "exception": true,
        "date": "Wed Jul 01 2020 10:47:38 GMT+0200 (GMT+02:00)",
        "process": {
            "pid": 67100,
            "uid": 1000,
            "gid": 1000,
            "cwd": "/home/elliotbouvier/workspace/ark/packages/worker-snapchat",
            "execPath": "/home/elliotbouvier/.nvm/versions/node/v12.18.1/bin/node",
            "version": "v12.18.1",
            "argv": [
                "/home/elliotbouvier/.nvm/versions/node/v12.18.1/bin/node",
                "/home/elliotbouvier/workspace/ark/packages/worker-snapchat/build/index.js"
            ],
            "memoryUsage": {
                "rss": 92147712,
                "heapTotal": 47333376,
                "heapUsed": 42648952,
                "external": 81305163,
                "arrayBuffers": 79845555
            }
        },
        "os": {
            "loadavg": [
                5.47509765625,
                3.95751953125,
                3.42431640625
            ],
            "uptime": 4986
        },
        "trace": [
            {
                "column": 76,
                "file": "/home/elliotbouvier/workspace/ark/packages/lib-mmr-datadog/node_modules/dd-trace/packages/datadog-plugin-aws-sdk/src/services/sqs.js",
                "function": "Sqs.responseExtract",
                "line": 24,
                "method": "responseExtract",
                "native": false
            },
            {
                "column": 36,
                "file": "/home/elliotbouvier/workspace/ark/packages/lib-mmr-datadog/node_modules/dd-trace/packages/datadog-plugin-aws-sdk/src/helpers.js",
                "function": "Object.responseExtract",
                "line": 61,
                "method": "responseExtract",
                "native": false
            },
            {
                "column": 39,
                "file": "/home/elliotbouvier/workspace/ark/packages/lib-mmr-datadog/node_modules/dd-trace/packages/datadog-plugin-aws-sdk/src/helpers.js",
                "function": "Response.wrappedCb",
                "line": 75,
                "method": "wrappedCb",
                "native": false
            },
            {
                "column": 18,
                "file": "/home/elliotbouvier/workspace/ark/node_modules/aws-sdk/lib/request.js",
                "function": null,
                "line": 364,
                "method": null,
                "native": false
            },
            {
                "column": 20,
                "file": "/home/elliotbouvier/workspace/ark/node_modules/aws-sdk/lib/sequential_executor.js",
                "function": "Request.callListeners",
                "line": 106,
                "method": "callListeners",
                "native": false
            },
            {
                "column": 10,
                "file": "/home/elliotbouvier/workspace/ark/node_modules/aws-sdk/lib/sequential_executor.js",
                "function": "Request.emit",
                "line": 78,
                "method": "emit",
                "native": false
            },
            {
                "column": 14,
                "file": "/home/elliotbouvier/workspace/ark/node_modules/aws-sdk/lib/request.js",
                "function": "Request.emit",
                "line": 683,
                "method": "emit",
                "native": false
            },
            {
                "column": 10,
                "file": "/home/elliotbouvier/workspace/ark/node_modules/aws-sdk/lib/request.js",
                "function": "Request.transition",
                "line": 22,
                "method": "transition",
                "native": false
            },
            {
                "column": 12,
                "file": "/home/elliotbouvier/workspace/ark/node_modules/aws-sdk/lib/state_machine.js",
                "function": "AcceptorStateMachine.runTo",
                "line": 14,
                "method": "runTo",
                "native": false
            },
            {
                "column": 10,
                "file": "/home/elliotbouvier/workspace/ark/node_modules/aws-sdk/lib/state_machine.js",
                "function": null,
                "line": 26,
                "method": null,
                "native": false
            },
            {
                "column": 9,
                "file": "/home/elliotbouvier/workspace/ark/node_modules/aws-sdk/lib/request.js",
                "function": null,
                "line": 38,
                "method": null,
                "native": false
            },
            {
                "column": 12,
                "file": "/home/elliotbouvier/workspace/ark/node_modules/aws-sdk/lib/request.js",
                "function": null,
                "line": 685,
                "method": null,
                "native": false
            },
            {
                "column": 18,
                "file": "/home/elliotbouvier/workspace/ark/node_modules/aws-sdk/lib/sequential_executor.js",
                "function": "Request.callListeners",
                "line": 116,
                "method": "callListeners",
                "native": false
            },
            {
                "column": 10,
                "file": "/home/elliotbouvier/workspace/ark/node_modules/aws-sdk/lib/sequential_executor.js",
                "function": "Request.emit",
                "line": 78,
                "method": "emit",
                "native": false
            },
            {
                "column": 14,
                "file": "/home/elliotbouvier/workspace/ark/node_modules/aws-sdk/lib/request.js",
                "function": "Request.emit",
                "line": 683,
                "method": "emit",
                "native": false
            },
            {
                "column": 10,
                "file": "/home/elliotbouvier/workspace/ark/node_modules/aws-sdk/lib/request.js",
                "function": "Request.transition",
                "line": 22,
                "method": "transition",
                "native": false
            }
        ],
        "dd": {
            "trace_id": "8339567957524275950",
            "span_id": "8339567957524275950",
            "service": "worker-snapchat",
            "version": "0.0.0"
        }
    }
}
```

**Environment**
```
yarn tsc -v
yarn run v1.22.4
$ /home/elliotbouvier/workspace/ark/node_modules/.bin/tsc -v
Version 3.9.2
```
```
"aws-sdk": "^2.663.0",
```
* **Operation system:**
```
lsb_release -a
No LSB modules are available.
Distributor ID:	Pop
Description:	Pop!_OS 20.04 LTS
Release:	20.04
Codename:	focal
```
* **Node version:**
```
node --version
v12.18.1
```
* **Tracer version:**
^0.22.1
* **Agent version:**

**Comment by rochdev** [comment]
Fixed in 0.22.2
