### ISSUE TITLE
Http Response End -- RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by ssingaraveluTrmb** [DataDog/dd-trace-js#1169]
**Describe the bug**
Getting the below exception on `dd-trace v0.28.0` and above (_possibly due to this change ([#1127](https://github.com/DataDog/dd-trace-js/pull/1127)))_. This makes the request timeout without returning a response. Should be reproducible on the below mentioned env setup.

```
(node:60192) UnhandledPromiseRejectionWarning: RangeError: Maximum call stack size exceeded
    at module.exports.internals.Response.end (/Users/ssingaravelu/Projects/cf-users/node_modules/@hapi/shot/lib/response.js:81:15)
    at module.exports.internals.Response.res._datadog_end (/Users/ssingaravelu/Projects/cf-users/node_modules/dd-trace/packages/dd-trace/src/plugins/util/web.js:265:29)
    at module.exports.internals.Response.end (/Users/ssingaravelu/Projects/cf-users/node_modules/@hapi/shot/lib/response.js:81:15)
    at module.exports.internals.Response.res._datadog_end (/Users/ssingaravelu/Projects/cf-users/node_modules/dd-trace/packages/dd-trace/src/plugins/util/web.js:265:29)
    at module.exports.internals.Response.end (/Users/ssingaravelu/Projects/cf-users/node_modules/@hapi/shot/lib/response.js:81:15)
    at module.exports.internals.Response.res._datadog_end (/Users/ssingaravelu/Projects/cf-users/node_modules/dd-trace/packages/dd-trace/src/plugins/util/web.js:265:29)
    at module.exports.internals.Response.end (/Users/ssingaravelu/Projects/cf-users/node_modules/@hapi/shot/lib/response.js:81:15)
    at module.exports.internals.Response.res._datadog_end (/Users/ssingaravelu/Projects/cf-users/node_modules/dd-trace/packages/dd-trace/src/plugins/util/web.js:265:29)
    at module.exports.internals.Response.end (/Users/ssingaravelu/Projects/cf-users/node_modules/@hapi/shot/lib/response.js:81:15)
    at module.exports.internals.Response.res._datadog_end (/Users/ssingaravelu/Projects/cf-users/node_modules/dd-trace/packages/dd-trace/src/plugins/util/web.js:265:29)
    at module.exports.internals.Response.end (/Users/ssingaravelu/Projects/cf-users/node_modules/@hapi/shot/lib/response.js:81:15)
    at module.exports.internals.Response.res._datadog_end (/Users/ssingaravelu/Projects/cf-users/node_modules/dd-trace/packages/dd-trace/src/plugins/util/web.js:265:29)
    at module.exports.internals.Response.end (/Users/ssingaravelu/Projects/cf-users/node_modules/@hapi/shot/lib/response.js:81:15)
    at module.exports.internals.Response.res._datadog_end (/Users/ssingaravelu/Projects/cf-users/node_modules/dd-trace/packages/dd-trace/src/plugins/util/web.js:265:29)
    at module.exports.internals.Response.end (/Users/ssingaravelu/Projects/cf-users/node_modules/@hapi/shot/lib/response.js:81:15)
    at module.exports.internals.Response.res._datadog_end (/Users/ssingaravelu/Projects/cf-users/node_modules/dd-trace/packages/dd-trace/src/plugins/util/web.js:265:29)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:60192) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:60192) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Environment**
* **Operation system:** --> Linux _(reproducible locally in MacOS as well)_
* **Node version:** --> 14.5.x
* **Hapi version:** --> 20.0.3
* **Tracer version:** --> 0.28.0
* **Agent version:** --> 6.13.0

**Comment by rochdev** [comment]
Can you provide a replication snippet? I tried replicating this with the example from the `shot` documentation but it's working properly.

**Comment by rochdev** [comment]
Since I wasn't able to replicate and it's been a while, we simply went ahead and reverted the aforementioned PR.

@ssingaraveluTrmb Can you try `0.30.0-beta.0` and let me know if it fixes the issue?

**Comment by jasonvangundy** [comment]
We are having the exact same issue.  I pinpointed it down to our use of: https://github.com/travi/hapi-react-router and seemingly our use of server side rendering.  HTML requests manifest the above issue, but our calls for json succeed just fine.  If I hear anything back externally I'll report here.

**Comment by rochdev** [comment]
@jasonvangundy Can you try the beta version from above?

**Comment by jasonvangundy** [comment]
this seems to have fixed it for us! thank you!

**Comment by rochdev** [comment]
Thanks for confirming!

@ssingaraveluTrmb I'm closing the issue since we have multiple confirmations that this resolved the issue at this point. Please feel free to re-open if you're still having issues. The fix will be in the next release later today.

**Comment by ssingaraveluTrmb** [comment]
That fixed the issue for us too! Thanks
