### ISSUE TITLE
MaxListenersExceededWarning: Possible EventEmitter memory leak detected

### ISSUE THREAD

**Issue by ssingaraveluTrmb** [DataDog/dd-trace-js#1202]
**Describe the bug**

Getting a MaxListenersExceededWarning on tracer version `0.30.0`. Would be nice to increase the listener limit to avoid warning if this expected.

```
DATADOG TRACER CONFIGURATION - {"date":"2021-01-11T18:04:02.062Z","os_name":"Darwin","os_version":"19.6.0","architecture":"x64","version":"0.30.0","lang":"nodejs","lang_version":"14.15.1","enabled":true,"service":"node","agent_url":{"slashes":true,"protocol":"http:","hash":"","query":"","pathname":"","auth":"","host":"127.0.0.1:8126","port":"8126","hostname":"127.0.0.1","password":"","username":"","origin":"http://127.0.0.1:8126","href":"http://127.0.0.1:8126"},"debug":false,"analytics_enabled":false,"sample_rate":1,"sampling_rules":[],"tags":{"service":"node","version":"1.0.0"},"dd_version":"1.0.0","log_injection_enabled":false,"runtime_metrics_enabled":false,"integrations_loaded":["pino@6.7.0","http","https","fs","@hapi/hapi@20.0.3","bluebird@3.7.2","net","dns","pg@8.5.1","@elastic/elasticsearch@6.8.1"]}
(node:89418) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 update listeners added to [Config]. Use emitter.setMaxListeners() to increase limit
    at _addListener (events.js:390:17)
    at Config.addListener (events.js:406:10)
    at Config.retroOn (/Users/ssingaravelu/Projects/cf-users/node_modules/dd-trace/packages/dd-trace/src/config.js:71:10)
    at new Sampler (/Users/ssingaravelu/Projects/cf-users/node_modules/dd-trace/packages/dd-trace/src/sampler.js:7:12)
    at PrioritySampler.update (/Users/ssingaravelu/Projects/cf-users/node_modules/dd-trace/packages/dd-trace/src/priority_sampler.js:69:23)
    at /Users/ssingaravelu/Projects/cf-users/node_modules/dd-trace/packages/dd-trace/src/exporters/agent/writer.js:58:31
    at /Users/ssingaravelu/Projects/cf-users/node_modules/dd-trace/packages/dd-trace/src/exporters/agent/writer.js:133:5
    at IncomingMessage.<anonymous> (/Users/ssingaravelu/Projects/cf-users/node_modules/dd-trace/packages/dd-trace/src/platform/node/request.js:40:9)
    at /Users/ssingaravelu/Projects/cf-users/node_modules/dd-trace/packages/dd-trace/src/scope/base.js:54:19
    at AsyncLocalStorage.run (async_hooks.js:295:14)
    at Scope._activate (/Users/ssingaravelu/Projects/cf-users/node_modules/dd-trace/packages/dd-trace/src/scope/async_local_storage.js:25:26)
    at Scope.activate (/Users/ssingaravelu/Projects/cf-users/node_modules/dd-trace/packages/dd-trace/src/scope/base.js:12:19)
    at IncomingMessage.bound (/Users/ssingaravelu/Projects/cf-users/node_modules/dd-trace/packages/dd-trace/src/scope/base.js:53:20)
    at IncomingMessage.emit (events.js:327:22)
    at IncomingMessage.EventEmitter.emit (domain.js:486:12)
    at endReadableNT (_stream_readable.js:1327:12)
```

**Environment**

* **Operation system:** -- Unix, MacOS
* **Node version:** -- 14.15.1
* **Tracer version:** -- 0.30.0
* **Agent version:** -- 6.22.0

**Comment by rochdev** [comment]
We register many listeners on the config so it's normal that it's above 10 and not a leak. The warning will be fixed in the next release.

**Comment by bengl** [comment]
This is fixed in the latest release.

**Comment by nampas** [comment]
Did this change get wiped out, or is it no longer relevant? We're seeing this warning a lot on version 1.2.1. Seems like the fix @bengl is long gone (at least, I'm not seeing any dd-trace code extending EventEmitter anymore, or calling setMaxListeners() ).

**Comment by bengl** [comment]
@nampas the change is gone because config is no longer an EventEmitter. Could you post the stack trace you're seeing, preferably in a new issue?

**Comment by nampas** [comment]
Sure, thanks @bengl . Let me do a little more digging on my side before I waste your time more.

**Comment by nampas** [comment]
Ok, here ya go. https://github.com/DataDog/dd-trace-js/issues/1758. I appreciate the help.
