### ISSUE TITLE
Fastify crash

### ISSUE THREAD

**Issue by Eomm** [DataDog/dd-trace-js#1217]
**Describe the bug**

The `dd-trace` doesn't support all the fastify' syntax to define routes.
Calling this endpoint:

```js
require('dd-trace').init({
  logInjection: true
})

const fastify = require('fastify')({ logger: true })

fastify.get('/', {
  handler: function doSomething (request, reply) {  // <-------- handler as an option and not as a parameter
    reply.send('hello')
  },
  schema: {
    headers: {
      foo: { type: 'string' }
    }
  }
})

fastify.listen(8080)
```

Will lead to a server crash:

```
{"level":30,"time":1611150379908,"pid":34636,"hostname":"MSPIGOLON5591","msg":"Server listening at http://127.0.0.1:8080","dd":{"service":"foo","version":"1.0.0"},"v":1}
{"level":30,"time":1611150404386,"pid":34636,"hostname":"MSPIGOLON5591","reqId":1,"req":{"method":"GET","url":"/","hostname":"localhost:8080","remoteAddress":"127.0.0.1","remotePort":51157},"msg":"incoming request","dd":{"trace_id":"5804212036515455345","span_id":"5804212036515455345","service":"api_races_2","version":"1.0.0"},"v":1}
FOOO\node_modules\dd-trace\packages\dd-trace\src\scope\base.js:18
      throw e
      ^

TypeError: handler.apply is not a function
    at FOOO\node_modules\dd-trace\packages\datadog-plugin-fastify\src\fastify.js:93:46
    at Scope._activate (FOOO\node_modules\dd-trace\packages\dd-trace\src\scope\async_hooks.js:54:14)
    at Scope.activate (FOOO\node_modules\dd-trace\packages\dd-trace\src\scope\base.js:12:19)
    at reactivate (FOOO\node_modules\dd-trace\packages\dd-trace\src\plugins\util\web.js:342:35)
    at Object.reactivate (FOOO\node_modules\dd-trace\packages\dd-trace\src\plugins\util\web.js:79:12)
    at Object.handlerWithTrace (FOOO\node_modules\dd-trace\packages\datadog-plugin-fastify\src\fastify.js:93:16)
    at preHandlerCallback (FOOO\node_modules\fastify\lib\handleRequest.js:117:30)
    at next (FOOO\node_modules\fastify\lib\hooks.js:145:7)
    at Object.preHandler (FOOO\node_modules\dd-trace\packages\datadog-plugin-fastify\src\fastify.js:51:3)
    at hookIterator (FOOO\node_modules\fastify\lib\hooks.js:204:10)
```

I notice that to solve should be necessary to add:

```diff
function wrapHandler (handler) {
+  if(typeof handler === 'object') {
+    handler = handler.handler
+  }
```

https://github.com/DataDog/dd-trace-js/blob/99140c8a8acbed4c775c936a80e19fdb9ec5e09d/packages/datadog-plugin-fastify/src/fastify.js#L86

But I don't have time to a complete PR with tests right now

**Environment**

* **Operation system:** win 10
* **Node version:** node 14
* **Tracer version:** `0.30.4` with `fastify: 2.x`
* **Agent version:** N/A

**Comment by rochdev** [comment]
Fix released in 0.30.5
