### ISSUE TITLE
Mocha plugin: "this.timeout is not a function"

### ISSUE THREAD

**Issue by peterwj** [DataDog/dd-trace-js#1222]
**Describe the bug**
Hello,

I'm upgrading an app at work from `dd-trace` 0.26.1 to 0.30.2 in order [to resolve a vulnerability in the axios package](https://github.com/advisories/GHSA-4w2v-q235-vp99).  We use Mocha for our unit tests.  I noticed that a big diff adding specific Mocha support (https://github.com/DataDog/dd-trace-js/pull/1162) is included in that upgrade.

When we run our tests now, many tests fail to pass.  Specifically, any tests making use of [Mocha's `timeout` method](https://mochajs.org/#test-level) have started failing with a stacktrace looking like this:

```
     TypeError: this.timeout is not a function
      at /backend/transpiled/test/controllers/users.spec.js:18:1089
      at Context.<anonymous> (node_modules/dd-trace/packages/datadog-plugin-mocha/src/index.js:79:28)
      at /backend/node_modules/dd-trace/packages/dd-trace/src/tracer.js:94:56
      at /backend/node_modules/dd-trace/packages/dd-trace/src/tracer.js:45:56
      at async_hooks.js:300:14
      at AsyncResource.runInAsyncScope (async_hooks.js:189:9)
      at AsyncLocalStorage.run (async_hooks.js:298:35)
      at Scope._activate (node_modules/dd-trace/packages/dd-trace/src/scope/async_local_storage.js:25:26)
      at Scope.activate (node_modules/dd-trace/packages/dd-trace/src/scope/base.js:12:19)
      at DatadogTracer.trace (node_modules/dd-trace/packages/dd-trace/src/tracer.js:45:35)
      at Context.<anonymous> (node_modules/dd-trace/packages/dd-trace/src/tracer.js:94:23)
      at Runner.runTestWithTrace [as runTest] (node_modules/dd-trace/packages/datadog-plugin-mocha/src/index.js:95:22)
```

Removing the tracer initialization code (`require('dd-trace').init(ddTraceOptions)`) from the app resolves the issue.

My hypothesis is that the above PR didn't include support for the `timeout` method.  

**Environment**

* **Operation system:**
* Debian buster, run as the `node:12-buster` docker image
* **Node version:**
* v12.20.1
* **Tracer version:**
* 0.30.2
* **Agent version:**
* N/A

**Comment by rochdev** [comment]
@peterwj Can you try with the Mocha plugin disabled? It has been introduced since then and may interact with your tests. The plugin can be disabled with `tracer.use('mocha', false)`

@juan-fernandez Could this be a regression introduced by the plugin?

**Comment by peterwj** [comment]
hey!  Thanks for the lickety-split quick response.  I added the `tracer.use` line right after the initialization line (see below), but I'm still seeing the same `this.timeout is not a function` TypeError. 

```
    const tracer = require('dd-trace').init(ddTraceOptions)
    tracer.use('mocha', false)
```

**Comment by rochdev** [comment]
Can you share the stack trace with the plugin disabled? From the previous stack trace it definitely seemed like the plugin was involved so I wonder if it's not disabling properly somehow.

Maybe a safer way would be using environment variables so I would suggest trying `DD_TRACE_DISABLED_PLUGINS=mocha`. Since Mocha is a runner it's possible that it behaves differently.

**Comment by peterwj** [comment]
Yes, happy to!  Here is the trace with `tracer.use('mocha', false)` added to our app startup code.  It certainly looks like the plugin hasn't properly disabled, since the trace looks nearly identical to me (only difference is the column number in our code, which isn't a big surprise since it's generated by the typescript compiler):
```
     TypeError: this.timeout is not a function
      at /backend/transpiled/test/controllers/users.spec.js:18:1047
      at Context.<anonymous> (node_modules/dd-trace/packages/datadog-plugin-mocha/src/index.js:79:28)
      at /backend/node_modules/dd-trace/packages/dd-trace/src/tracer.js:94:56
      at /backend/node_modules/dd-trace/packages/dd-trace/src/tracer.js:45:56
      at async_hooks.js:300:14
      at AsyncResource.runInAsyncScope (async_hooks.js:189:9)
      at AsyncLocalStorage.run (async_hooks.js:298:35)
      at Scope._activate (node_modules/dd-trace/packages/dd-trace/src/scope/async_local_storage.js:25:26)
      at Scope.activate (node_modules/dd-trace/packages/dd-trace/src/scope/base.js:12:19)
      at DatadogTracer.trace (node_modules/dd-trace/packages/dd-trace/src/tracer.js:45:35)
      at Context.<anonymous> (node_modules/dd-trace/packages/dd-trace/src/tracer.js:94:23)
      at Runner.runTestWithTrace [as runTest] (node_modules/dd-trace/packages/datadog-plugin-mocha/src/index.js:95:22)
```

Running with `DD_TRACE_DISABLED_PLUGINS=mocha` resolves the issue!

**Comment by rochdev** [comment]
Perfect! Then for now I would say to use that as a workaround and we'll look into the Mocha plugin since it shouldn't cause this issue.

**Comment by peterwj** [comment]
Incredible!  Thank you for the assistance :)
