### ISSUE TITLE
Support for Express v5

### ISSUE THREAD

**Issue by arminm** [DataDog/dd-trace-js#1245]
**Describe the bug**
The `express` plugin doesn't work with [express v5](https://github.com/expressjs/express/releases/tag/5.0.0-alpha.8). It is currently a pre-release version, but I wanted to raise this issue so we can hopefully fix it before the stable version is released.
I upgraded my express to `v5.0.0-alpha.8` and the dd traces do not show up anymore. Downgrading to `4.17.1` fixes it.

**Comment by rochdev** [comment]
It looks like there are 2 years between `alpha.7` and `alpha.8`, with `alpha.8` itself being a few months old. Do you know if Express v5 is actually actively being worked on or was it abandoned?

**Comment by JaneJeon** [comment]
It is "technically" still being worked on - last I heard, they're working out the kinks in the router. Most of the work is going on https://github.com/pillarjs but let's be real - it's not coming out until next year.

**Comment by tlhunter** [comment]
Looks like express hit beta status a year ago:
https://github.com/expressjs/express/blob/5.0/History.md#500-beta1--2022-02-14

> 5.0.0-beta.1 / 2022-02-14

Once Express v5 is fully released we'll be able to consider adding support. But until then it's just too likely that the API changes. Please reopen this issue or leave comments once that happens, though I'm sure the whole Node.js community (us included) will know when that happens.

**Comment by vernak2539** [comment]
Hello there! [Express v5](https://github.com/expressjs/express/releases/tag/v5.0.0) was just released. It'd be great if we could get support for this as we're encountering errors when running with dd-trace instrumented.

I've tried to put a bunch of information below, but let me know if more is needed.

## Extra Information

- `express`: v5.0.0
- `dd-trace`: v5.22.0 (tried also with 5.12.0 prior to upgrading)

We run our app using this command:
```
node -r ./.env/development.cjs --import ./src/node-instrumentation.mjs .
```

* `./.env/development.cjs` - uses `dotenv-extended` to load environment variables
* `./src/node-instrumentation.mjs` - imports our datadog tracing, more below
* `.` runs the main file in the `package.json`

The `./src/node-instrumentation.mjs` looks something like this:

```js
import tracer from 'dd-trace';

const hostname = process.env.STATSD_HOST;

if (hostname) {
  tracer.init({
    hostname: process.env.STATSD_HOST,
    service: appName,
    debug: process.env.DATADOG_DEBUG_ENABLED === 'true',
  });
  tracer.use('express', {
    service: `${appName}/express`,
    hooks: {
        // hook stuff, nothing too interesting other than setting span tags
      },
    },
  });
  tracer.use('http', { service: `${appName}/http-client` });
  tracer.use('dns', { service: `${appName}/dns` });
  tracer.use('net', { service: `${appName}/tcp` });
}
```


This is the error we get when running the application.

```
TypeError: Cannot read properties of undefined (reading 'fast_star')
    at isFastStar (/Users/testuser/repo/node_modules/dd-trace/packages/datadog-instrumentations/src/router.js:124:22)
    at Object.test (/Users/testuser/repo/node_modules/dd-trace/packages/datadog-instrumentations/src/router.js:116:17)
    at errorMiddleware (/Users/testuser/repo/node_modules/dd-trace/packages/datadog-instrumentations/src/router.js:39:27)
    at errorMiddleware (/Users/testuser/repo/node_modules/dd-trace/packages/datadog-shimmer/src/shimmer.js:31:21)
    at Layer.handleError (/Users/testuser/repo/node_modules/router/lib/layer.js:113:17)
    at trimPrefix (/Users/testuser/repo/node_modules/router/index.js:335:13)
    at /Users/testuser/repo/node_modules/router/index.js:295:9
    at processParams (/Users/testuser/repo/node_modules/router/index.js:575:12)
    at next (/Users/testuser/repo/node_modules/router/index.js:289:5)
    at Layer.handleError (/Users/testuser/repo/node_modules/router/lib/layer.js:122:5)
    at trimPrefix (/Users/testuser/repo/node_modules/router/index.js:335:13)
    at /Users/testuser/repo/node_modules/router/index.js:295:9
    at processParams (/Users/testuser/repo/node_modules/router/index.js:575:12)
    at next (/Users/testuser/repo/node_modules/router/index.js:289:5)
    at Layer.handleError (/Users/testuser/repo/node_modules/router/lib/layer.js:108:12)
    at trimPrefix (/Users/testuser/repo/node_modules/router/index.js:335:13)
    at /Users/testuser/repo/node_modules/router/index.js:295:9
    at processParams (/Users/testuser/repo/node_modules/router/index.js:575:12)
    at next (/Users/testuser/repo/node_modules/router/index.js:289:5)
    at Layer.handleError (/Users/testuser/repo/node_modules/router/lib/layer.js:108:12)
    at trimPrefix (/Users/testuser/repo/node_modules/router/index.js:335:13)
    at /Users/testuser/repo/node_modules/router/index.js:295:9
    at processParams (/Users/testuser/repo/node_modules/router/index.js:575:12)
    at next (/Users/testuser/repo/node_modules/router/index.js:289:5)
    at Layer.handleError (/Users/testuser/repo/node_modules/router/lib/layer.js:108:12)
    at trimPrefix (/Users/testuser/repo/node_modules/router/index.js:335:13)
    at /Users/testuser/repo/node_modules/router/index.js:295:9
    at processParams (/Users/testuser/repo/node_modules/router/index.js:575:12)
    at next (/Users/testuser/repo/node_modules/router/index.js:289:5)
    at Layer.handleError (/Users/testuser/repo/node_modules/router/lib/layer.js:108:12)
    at trimPrefix (/Users/testuser/repo/node_modules/router/index.js:335:13)
    at /Users/testuser/repo/node_modules/router/index.js:295:9
    at processParams (/Users/testuser/repo/node_modules/router/index.js:575:12)
    at next (/Users/testuser/repo/node_modules/router/index.js:289:5)
    at Layer.handleError (/Users/testuser/repo/node_modules/router/lib/layer.js:108:12)
    at trimPrefix (/Users/testuser/repo/node_modules/router/index.js:335:13)
    at /Users/testuser/repo/node_modules/router/index.js:295:9
    at processParams (/Users/testuser/repo/node_modules/router/index.js:575:12)
    at next (/Users/testuser/repo/node_modules/router/index.js:289:5)
    at Layer.handleError (/Users/testuser/repo/node_modules/router/lib/layer.js:108:12)
    at trimPrefix (/Users/testuser/repo/node_modules/router/index.js:335:13)
    at /Users/testuser/repo/node_modules/router/index.js:295:9
    at processParams (/Users/testuser/repo/node_modules/router/index.js:575:12)
    at next (/Users/testuser/repo/node_modules/router/index.js:289:5)
    at Layer.handleError (/Users/testuser/repo/node_modules/router/lib/layer.js:108:12)
    at trimPrefix (/Users/testuser/repo/node_modules/router/index.js:335:13)
    at /Users/testuser/repo/node_modules/router/index.js:295:9
    at processParams (/Users/testuser/repo/node_modules/router/index.js:575:12)
    at next (/Users/testuser/repo/node_modules/router/index.js:289:5)
    at Layer.handleRequest (/Users/testuser/repo/node_modules/router/lib/layer.js:154:5)
```
