### ISSUE TITLE
Socket hang up at v0.31.3 caused crashing

### ISSUE THREAD

**Issue by superwesker1988** [DataDog/dd-trace-js#1300]
**Describe the bug**
We are using axios v0.21.1 to making a POST request in our Node.js service, and an endpoint we called happen to be faulted, therefore the axios aborts the request at timeout. Right after it, our service crashes even thought we caught the error from axios in our catch block without issue. Below is a log at crashing:
```
/srv/package/node_modules/dd-trace/packages/dd-trace/src/scope/base.js:18
      throw e
      ^

Error: socket hang up
    at connResetException (internal/errors.js:607:14)
    at Socket.socketCloseListener (_http_client.js:443:25)
    at /srv/package/node_modules/dd-trace/packages/dd-trace/src/scope/base.js:54:19
    at Scope._activate (/srv/package/node_modules/dd-trace/packages/dd-trace/src/scope/async_resource.js:47:14)
    at Scope.activate (/srv/package/node_modules/dd-trace/packages/dd-trace/src/scope/base.js:12:19)
    at Socket.bound (/srv/package/node_modules/dd-trace/packages/dd-trace/src/scope/base.js:53:20)
    at Socket.emit (events.js:327:22)
    at Socket.EventEmitter.emit (domain.js:467:12)
    at TCP.<anonymous> (net.js:673:12)
    at TCP.callbackTrampoline (internal/async_hooks.js:131:14)
Emitted 'error' event on Writable instance at:
    at ClientRequest.eventHandlers.<computed> (/srv/package/node_modules/follow-redirects/index.js:13:24)
    at /srv/package/node_modules/dd-trace/packages/dd-trace/src/scope/base.js:54:19
    at Scope._activate (/srv/package/node_modules/dd-trace/packages/dd-trace/src/scope/async_resource.js:47:14)
    at Scope.activate (/srv/package/node_modules/dd-trace/packages/dd-trace/src/scope/base.js:12:19)
    at ClientRequest.bound (/srv/package/node_modules/dd-trace/packages/dd-trace/src/scope/base.js:53:20)
    at ClientRequest.emit (events.js:327:22)
    at ClientRequest.EventEmitter.emit (domain.js:467:12)
    at ClientRequest.req.emit (/srv/package/node_modules/dd-trace/packages/datadog-plugin-http/src/client.js:106:21)
    at Socket.socketCloseListener (_http_client.js:443:11)
    at /srv/package/node_modules/dd-trace/packages/dd-trace/src/scope/base.js:54:19
    [... lines matching original stack trace ...]
    at TCP.callbackTrampoline (internal/async_hooks.js:131:14) {
  code: 'ECONNRESET'
}
```
**Environment**

* **Operation system:**
* GNU/Linux 4.14.209
* **Node version:**
* v14.16.0
* **Tracer version:**
* 0.31.3
* **Agent version:**
* 7.26.0

**Comment by superwesker1988** [comment]
The issue seems fairly similar to what was fixed in: https://github.com/DataDog/dd-trace-js/issues/1253. Not sure if it is related.

**Comment by superwesker1988** [comment]
I sincerely apologize for this report, it turns out we deployed a service version which didn't have the  `dd-trace` 0.31.1+ by mistake. Close the bug report.
