### ISSUE TITLE
cannot run in NodeJS 14.x

### ISSUE THREAD

**Issue by chaoyangnz** [DataDog/dd-trace-js#1319]
**Describe the bug**

`dd-trace-js` has a dependency `read-pkg-up` which cause the below error

```
   TypeError: Object prototype may only be an Object or null: undefined
        at Function.setPrototypeOf (<anonymous>)

      at ../../node_modules/graceful-fs/polyfills.js:139:39
      at patch (../../node_modules/graceful-fs/polyfills.js:141:5)
      at patch (../../node_modules/graceful-fs/graceful-fs.js:104:3)
      at Object.<anonymous> (../../node_modules/graceful-fs/graceful-fs.js:96:18)
      at Object.<anonymous> (../../node_modules/load-json-file/index.js:3:12)
```

**Environment**

* **Operation system:**
* **Node version:**
* **Tracer version:**
* **Agent version:**

**Comment by bengl** [comment]
This was fixed by #1323
