### ISSUE TITLE
run into error `TypeError: fs.existsSync is not a function`

### ISSUE THREAD

**Issue by chaoyangnz** [DataDog/dd-trace-js#1329]
**Describe the bug**
When I add `dd-trace` into package.json  (0.32.2)
and `import ddtracer from 'dd-trace'` . Run my Jest test, then I got the error

```
  TypeError: fs.existsSync is not a function

      at findUp (../../node_modules/dd-trace/packages/dd-trace/src/pkg.js:30:12)
      at findPkg (../../node_modules/dd-trace/packages/dd-trace/src/pkg.js:14:20)
      at Object.<anonymous> (../../node_modules/dd-trace/packages/dd-trace/src/pkg.js:37:18)
      at Object.<anonymous> (../../node_modules/dd-trace/packages/dd-trace/src/config.js:4:13)
```

**Environment**

* **Operation system:**
* **Node version: 14.10.0
* **Tracer version: 0.32.2
* **Agent version:**

**Comment by rochdev** [comment]
What ended up being the issue? Did you need a workaround or was the issue not caused by `dd-trace` in the end?

**Comment by chaoyangnz** [comment]
@rochdev that is irrelevant to datadog. So I closed this
