### ISSUE TITLE
bytes.map is not a function

### ISSUE THREAD

**Issue by matehuszarik** [DataDog/dd-trace-js#1349]
Since v0.33.0 release our services using dd-trace spam these kind of log messages: `bytes.map is not a function`.

Stack trace:
```
TypeError: bytes.map is not a function
    at /app/node_modules/dd-trace/packages/dd-trace/src/encode/0.4.js:34:62
    at processMsg (/app/node_modules/dd-trace/packages/dd-trace/src/log.js:44:38)
    at /app/node_modules/dd-trace/packages/dd-trace/src/log.js:99:41
    at Scope._activate (/app/node_modules/dd-trace/packages/dd-trace/src/scope/async_resource.js:53:14)
    at Scope.activate (/app/node_modules/dd-trace/packages/dd-trace/src/scope/base.js:12:19)
    at withNoop (/app/node_modules/dd-trace/packages/dd-trace/src/log.js:51:25)
    at Object.debug (/app/node_modules/dd-trace/packages/dd-trace/src/log.js:99:7)
    at AgentEncoder.encode (/app/node_modules/dd-trace/packages/dd-trace/src/encode/0.4.js:34:9)
    at Writer._encode (/app/node_modules/dd-trace/packages/dd-trace/src/exporters/agent/writer.js:71:29)
    at Writer.append (/app/node_modules/dd-trace/packages/dd-trace/src/exporters/agent/writer.js:25:10)
    at AgentExporter.export (/app/node_modules/dd-trace/packages/dd-trace/src/exporters/agent/index.js:30:18)
    at SpanProcessor.process (/app/node_modules/dd-trace/packages/dd-trace/src/span_processor.js:24:28)
    at DatadogSpan._finish (/app/node_modules/dd-trace/packages/dd-trace/src/opentracing/span.js:135:21)
    at DatadogSpan.Span.finish (/app/node_modules/opentracing/lib/span.js:160:14)
```

I tracked down the issue to this [line](https://github.com/DataDog/dd-trace-js/blob/master/packages/dd-trace/src/encode/0.4.js#L34) but I'm not familiar with the internals of the package.

Can somebody give me a hand here?

**Environment**

* **Operation system:** linux
* **Node version:** 14.x.x
* **Tracer version:**
* **Agent version:**

**Comment by rochdev** [comment]
Looks like a bug in what `bytes` is versus what the debug logs expect. I would say to disable debug logs for now and I will release a fix shortly.
