### ISSUE TITLE
TypeError: Cannot read property 'span' of undefined

### ISSUE THREAD

**Issue by awilson1801** [DataDog/dd-trace-js#1535]
After updating `dd-trace-js` to any version > 0.33.2 I am getting this error in my nextjs service while running the service locally. The local setup does use cloud resources in our dev environment, and if I remove these cloud resources it does work. However, this wasn't an issue with tracer versions < 0.33.2.

Error message:
```
TypeError: Cannot read property 'span' of undefined
    at addPage (/Users/aaronwilson/repos/agent-client/node_modules/dd-trace/packages/datadog-plugin-next/src/index.js:87:21)
    at DevServer.renderToHTMLWithComponentsWithTrace (/Users/aaronwilson/repos/agent-client/node_modules/dd-trace/packages/datadog-plugin-next/src/index.js:42:7)
    at DevServer.renderErrorToHTML (/Users/aaronwilson/repos/agent-client/node_modules/next/dist/next-server/server/next-server.js:139:516)
TypeError: Cannot read property 'span' of undefined
    at addPage (/Users/aaronwilson/repos/agent-client/node_modules/dd-trace/packages/datadog-plugin-next/src/index.js:87:21)
    at DevServer.renderToHTMLWithComponentsWithTrace (/Users/aaronwilson/repos/agent-client/node_modules/dd-trace/packages/datadog-plugin-next/src/index.js:42:7)
    at DevServer.renderToHTML (/Users/aaronwilson/repos/agent-client/node_modules/next/dist/next-server/server/next-server.js:138:533)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

**Environment**
local environment which uses some cloud resources

* **Operation system:**
macos
* **Node version:**
 10.24.1
* **Tracer version:**
0.36.2
* **Agent version:**
7

**Comment by havenchyk** [comment]
@rochdev I have the same problem with 2.5.0

```
TypeError: Cannot read property 'span' of undefined
    at /home/runner/work/server/node_modules/dd-trace/packages/datadog-plugin-http/src/client.js:60:38
    at Subscription._handler (/home/runner/work/server/node_modules/dd-trace/packages/dd-trace/src/plugins/plugin.js:12:9)
    at Channel.publish (diagnostics_channel.js:54:9)
    at finish (/home/runner/work/server/node_modules/dd-trace/packages/datadog-instrumentations/src/http/client.js:67:28)
    at /home/runner/work/server/node_modules/dd-trace/packages/datadog-instrumentations/src/http/client.js:90:15
    at exports.AsyncResource.runInAsyncScope (async_hooks.js:197:9)
    at ClientRequest.req.emit (/home/runner/work/server/node_modules/dd-trace/packages/datadog-instrumentations/src/http/client.js:72:12)
    at TLSSocket.socketCloseListener (_http_client.js:434:9)
    at TLSSocket.emit (events.js:412:35)
    at TLSSocket.emit (domain.js:475:12)
```

**Comment by rochdev** [comment]
@havenchyk Do you also have the same issue with the latest version?

**Comment by havenchyk** [comment]
@rochdev I'll try to update and check. It's flaky, so I can't say exactly
