### ISSUE TITLE
uncaughtException: Cannot read property 'resume' of undefined

### ISSUE THREAD

**Issue by iAnomaly** [DataDog/dd-trace-js#1536]
**Describe the bug**
We've been seeing `uncaughtException: Cannot read property 'resume' of undefined` since upgrading to the profiler alpha tracer version below. It's unclear how to reproduce this or when/why it's occurring.

Stack:
```
TypeError: Cannot read property 'resume' of undefined,
    at ClientRequest.<anonymous> (/app/node_modules/dd-trace/packages/dd-trace/src/profiling/exporters/agent.js:85:13),
    at ClientRequest.callback (/app/node_modules/dd-trace/node_modules/form-data/lib/form_data.js:475:19),
    at /app/node_modules/dd-trace/packages/dd-trace/src/scope/base.js:54:19,
    at Scope._activate (/app/node_modules/dd-trace/packages/dd-trace/src/scope/async_resource.js:57:14),
    at Scope.activate (/app/node_modules/dd-trace/packages/dd-trace/src/scope/base.js:12:19),
    at ClientRequest.bound (/app/node_modules/dd-trace/packages/dd-trace/src/scope/base.js:53:20),
    at ClientRequest.emit (events.js:375:28),
    at ClientRequest.emit (domain.js:470:12),
    at ClientRequest.req.emit (/app/node_modules/dd-trace/packages/datadog-plugin-http/src/client.js:106:21),
    at Socket.socketOnEnd (_http_client.js:499:9),
    at /app/node_modules/dd-trace/packages/dd-trace/src/scope/base.js:54:19,
    at Scope._activate (/app/node_modules/dd-trace/packages/dd-trace/src/scope/async_resource.js:57:14),
    at Scope.activate (/app/node_modules/dd-trace/packages/dd-trace/src/scope/base.js:12:19),
    at Socket.bound (/app/node_modules/dd-trace/packages/dd-trace/src/scope/base.js:53:20),
    at Socket.emit (events.js:387:35),
    at Socket.emit (domain.js:470:12),
    at endReadableNT (internal/streams/readable.js:1317:12),
    at processTicksAndRejections (internal/process/task_queues.js:82:21)
```

Trace:
```
{"column":13,"line":85,"file":"/app/node_modules/dd-trace/packages/dd-trace/src/profiling/exporters/agent.js","native":false}
--
{"function":"ClientRequest.callback","column":19,"file":"/app/node_modules/dd-trace/node_modules/form-data/lib/form_data.js","line":475,"method":"callback","native":false}
{"column":19,"line":54,"file":"/app/node_modules/dd-trace/packages/dd-trace/src/scope/base.js","native":false}
{"function":"Scope._activate","column":14,"file":"/app/node_modules/dd-trace/packages/dd-trace/src/scope/async_resource.js","line":57,"method":"_activate","native":false}
{"function":"Scope.activate","column":19,"file":"/app/node_modules/dd-trace/packages/dd-trace/src/scope/base.js","line":12,"method":"activate","native":false}
{"function":"ClientRequest.bound","column":20,"file":"/app/node_modules/dd-trace/packages/dd-trace/src/scope/base.js","line":53,"method":"bound","native":false}
{"function":"ClientRequest.emit","column":28,"file":"events.js","line":375,"method":"emit","native":false}
{"function":"ClientRequest.emit","column":12,"file":"domain.js","line":470,"method":"emit","native":false}
{"function":"ClientRequest.req.emit","column":21,"file":"/app/node_modules/dd-trace/packages/datadog-plugin-http/src/client.js","line":106,"method":"emit","native":false}
{"function":"Socket.socketOnEnd","column":9,"file":"_http_client.js","line":499,"method":"socketOnEnd","native":false}
{"column":19,"line":54,"file":"/app/node_modules/dd-trace/packages/dd-trace/src/scope/base.js","native":false}
{"function":"Scope._activate","column":14,"file":"/app/node_modules/dd-trace/packages/dd-trace/src/scope/async_resource.js","line":57,"method":"_activate","native":false}
{"function":"Scope.activate","column":19,"file":"/app/node_modules/dd-trace/packages/dd-trace/src/scope/base.js","line":12,"method":"activate","native":false}
{"function":"Socket.bound","column":20,"file":"/app/node_modules/dd-trace/packages/dd-trace/src/scope/base.js","line":53,"method":"bound","native":false}
{"function":"Socket.emit","column":35,"file":"events.js","line":387,"method":"emit","native":false}
{"function":"Socket.emit","column":12,"file":"domain.js","line":470,"method":"emit","native":false}
{"function":"endReadableNT","column":12,"line":1317,"file":"internal/streams/readable.js","native":false}
{"function":"processTicksAndRejections","column":21,"line":82,"file":"internal/process/task_queues.js","native":false}
```

**Environment**

* **Operation system: Linux**
* **Node version: 14.17.3**
* **Tracer version: 0.35.0-profiler.**
* **Agent version: 7.29.0**

**Comment by Qard** [comment]
That should already be fixed. Please upgrade to `1.1.0-profiler.0` to confirm.

**Comment by iAnomaly** [comment]
`1.1.0-profiler.0` looking good! Thanks @Qard. Closing.
