### ISSUE TITLE
bunyan patching fails with Error: No target object provided.

### ISSUE THREAD

**Issue by dominicfollett** [DataDog/dd-trace-js#1932]
**Describe the bug**
During loading, an error is returned:

```
/Users/admin/project/node_modules/dd-trace/packages/datadog-shimmer/src/shimmer.js:108
    throw new Error('No target object provided.')
          ^

Error: No target object provided.
    at assertMethod (/Users/admin/project/node_modules/dd-trace/packages/datadog-shimmer/src/shimmer.js:108:11)
    at wrapMethod (/Users/admin/project/node_modules/dd-trace/packages/datadog-shimmer/src/shimmer.js:35:3)
    at Object.wrap (/Users/admin/project/node_modules/dd-trace/packages/datadog-shimmer/src/shimmer.js:65:7)
    at /Users/admin/project/node_modules/dd-trace/packages/datadog-instrumentations/src/bunyan.js:11:11
    at cjsPostLoad (/Users/admin/project/node_modules/dd-trace/packages/datadog-instrumentations/src/helpers/instrument.js:84:5)
    at addHook (/Users/admin/project/node_modules/dd-trace/packages/datadog-instrumentations/src/helpers/instrument.js:33:3)
    at Object.<anonymous> (/Users/admin/project/node_modules/dd-trace/packages/datadog-instrumentations/src/bunyan.js:9:1)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
```

**Environment**

* **Operation system:**
* * MacOs Monterey & node:14-alpine docker container
* **Node version:**
* * v14.19.0
* **Tracer version:**
* * "^2.4.0"
* **Agent version:**
* * 7

**Index.js**
```
import tracer from 'dd-trace';
tracer.init({service: 'myservice', plugins: true, logInjection: true});
import bunyan from 'bunyan';

const logger = bunyan.createLogger({
  name: 'myservice-logger',
  stream: process.stdout,
})
```

**package.json**
```
  "name": "myservice",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "type": "module"
  "dependencies": {
    "bunyan": "^1.8.15",
    "dd-trace": "^2.4.0"
  },
...
```

**Comment by dominicfollett** [comment]
Hi, thank you so much for looking into this.

I'm not running in a test environment. I tried reproducing it without using `type: 'module'` and that works just fine:

```
const tracer = require('dd-trace').init({
    logInjection: true,
    plugins: true,
    service: 'myservice',
  })
const bunyan = require('bunyan');

const logger = bunyan.createLogger({
    level: 'debug',
    name: 'my-service',
    stream: process.stdout,
})
```

But as soon as I convert it to a module, like it is in my first comment, then it throws the error when I run `node index.js`. Unfortunately I have to use type 'module' for this project. I'm not sure what else could help in reproducing this issue.

**Comment by rochdev** [comment]
Completely missed that in the `package.json`. I'll try again with that option.
