### ISSUE TITLE
Automatic instrumentation of rhea generates TypeError

### ISSUE THREAD

**Issue by fxalgrain** [DataDog/dd-trace-js#2043]
**Expected behaviour**
App should not crash due to error in dd-trace instrumentation

**Actual behaviour**
When dd-trace is imported, event if DD_TRACE_ENABLED is set to false, after a delay, our app crash du to 
```
/app/node_modules/dd-trace/packages/datadog-instrumentations/src/rhea.js:163
const asyncResource = context.asyncResource
TypeError: Cannot read properties of undefined (reading 'asyncResource')

at /app/node_modules/dd-trace/packages/datadog-instrumentations/src/rhea.js:163:45
at exports.AsyncResource.runInAsyncScope (node:async_hooks:202:9)
at bound (/app/node_modules/dd-trace/packages/datadog-instrumentations/src/helpers/instrument.js:71:26)
at CircularBuffer.pop_if (/app/node_modules/rhea/lib/session.js:62:25)
at CircularBuffer.pop_if (/app/node_modules/dd-trace/packages/datadog-instrumentations/src/rhea.js:180:26)
at Incoming.process (/app/node_modules/rhea/lib/session.js:379:21)
at Session._process (/app/node_modules/rhea/lib/session.js:619:23)
at Connection._process (/app/node_modules/rhea/lib/connection.js:748:32)
at processTicksAndRejections (node:internal/process/task_queues:78:11)
```

**Context**

We don't have direct dependency to rhea. 
This error appear only in our container that process events from Azure Event Hub
Looking the dependency tree, rhea is used by @azure/core-amqp. And this one is used by @azure/event-hubs

By the way, app is located in a Kubernetes cluster, with APM disabled on the Datadog Agent.

**Environment**

* **Operation system:**
* **Node.js version:** 16
* **Tracer version:**. 2.6.0
* **Agent version:** unknow
* **Relevant library versions:**
  - rhea: 2.0.8
  - @azure/core-amqp: 3.1.0
  - @azure/event-hubs: 5.6.0

**Comment by rochdev** [comment]
The fix for this was released in 2.8.0.
