### ISSUE TITLE
Errors when using with Firebase

### ISSUE THREAD

**Issue by daniestrijdom** [DataDog/dd-trace-js#206]
HI, 

We have an koa app that uses firebase realtime database, but when we [initialise the firebase application in the project](https://firebase.google.com/docs/admin/setup), then we get the following trace in our logs;

```
MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 close listeners added. Use emitter.setMaxListeners() to increase limit
    at _addListener (events.js:280:19)
    at TLSSocket.addListener (events.js:297:10)
    at TLSSocket.Readable.on (_stream_readable.js:772:35)
    at ClientRequest.req.on.socket (/pipeline/source/node_modules/dd-trace/src/plugins/http.js:50:16)
    at emitOne (events.js:121:20)
    at ClientRequest.emit (events.js:211:7)
    at tickOnSocket (_http_client.js:652:7)
    at onSocketNT (_http_client.js:668:5)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
```

**Comment by daniestrijdom** [comment]
Just saw the issue on another app that doesn't have firebase, just a new microservice we're created with that also uses the newest version of dd-trace, other applications with older versions are not showing this error, so it is likely not isolated to firebase

**Comment by rochdev** [comment]
Which versions of `dd-trace` and Node are you using?

**Comment by rochdev** [comment]
Also, what was the version that didn't have the warning? Does the application still work or is this throwing an exception?

**Comment by daniestrijdom** [comment]
hi @rochdev ; 

Node version is 8.11.3 in every case

dd-trace version is 0.5.1 which is giving us issues - previous version we were on which didn't give the node warning is 0.3.2

The application still works and it's not an exception or error that crashes the app, however looking at the kubernetes pod today I can see that there was 1 restart in the last 24 hrs, not sure if related. What happens is that it prints out the warning below about once every hour or so. 

```(node:16) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 close listeners added. Use emitter.setMaxListeners() to increase limit```

**Comment by rochdev** [comment]
This seems to happen because `http` reuses sockets from a pool when used with `keepAlive: true` and we attach an event handler to the socket on every request. I'll try to see if the listener could be removed sooner, and also if it would be possible to simply remove it.

**Comment by daniestrijdom** [comment]
thanks @rochdev !!!!

**Comment by rochdev** [comment]
Released in 0.5.3
