### ISSUE TITLE
Getting `TypeError: Cannot convert undefined or null to object` error when starting Meteor app

### ISSUE THREAD

**Issue by sig-bo** [DataDog/dd-trace-js#2090]
**Expected behaviour**
dd-trace initialization should work without errors.

**Actual behaviour**
Getting this runtime error upon starting Meteor application:
```
I20220529-15:38:47.853(8)? Meteor APM: completed instrumenting the app
I20220529-15:38:48.038(8)? ---
I20220529-15:38:48.038(8)? Application is starting up
W20220529-15:38:48.072(8)? (STDERR) TypeError: Cannot convert undefined or null to object
W20220529-15:38:48.073(8)? (STDERR)     at hasOwnProperty (<anonymous>)
W20220529-15:38:48.074(8)? (STDERR)     at AsyncResourceStorage._init (/Users/bohan/cs/codesignal/node_modules/dd-trace/packages/datadog-core/src/storage/async_resource.js:66:41)
W20220529-15:38:48.074(8)? (STDERR)     at emitInitNative (internal/async_hooks.js:203:43)
W20220529-15:38:48.074(8)? (STDERR)     at emitInitScript (internal/async_hooks.js:493:3)
W20220529-15:38:48.074(8)? (STDERR)     at process.nextTick (internal/process/task_queues.js:133:5)
W20220529-15:38:48.075(8)? (STDERR)     at ConnectionPool.checkIn (/Users/bohan/.meteor/packages/npm-mongo/.4.3.1.udxozx.x3fz++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/mongodb/lib/cmap/connection_pool.js:163:17)
W20220529-15:38:48.075(8)? (STDERR)     at /Users/bohan/.meteor/packages/npm-mongo/.4.3.1.udxozx.x3fz++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/mongodb/lib/cmap/connection_pool.js:277:26
W20220529-15:38:48.075(8)? (STDERR)     at handleOperationResult (/Users/bohan/.meteor/packages/npm-mongo/.4.3.1.udxozx.x3fz++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/mongodb/lib/sdam/server.js:363:9)
W20220529-15:38:48.075(8)? (STDERR)     at MessageStream.messageHandler (/Users/bohan/.meteor/packages/npm-mongo/.4.3.1.udxozx.x3fz++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/mongodb/lib/cmap/connection.js:474:9)
W20220529-15:38:48.075(8)? (STDERR)     at MessageStream.emit (events.js:400:28)
W20220529-15:38:48.075(8)? (STDERR)     at MessageStream.emit (domain.js:475:12)
W20220529-15:38:48.076(8)? (STDERR)     at processIncomingData (/Users/bohan/.meteor/packages/npm-mongo/.4.3.1.udxozx.x3fz++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/mongodb/lib/cmap/message_stream.js:108:16)
W20220529-15:38:48.076(8)? (STDERR)     at MessageStream._write (/Users/bohan/.meteor/packages/npm-mongo/.4.3.1.udxozx.x3fz++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/mongodb/lib/cmap/message_stream.js:28:9)
W20220529-15:38:48.076(8)? (STDERR)     at writeOrBuffer (internal/streams/writable.js:358:12)
W20220529-15:38:48.076(8)? (STDERR)     at MessageStream.Writable.write (internal/streams/writable.js:303:10)
W20220529-15:38:48.076(8)? (STDERR)     at Socket.ondata (internal/streams/readable.js:731:22)
W20220529-15:38:48.077(8)? (STDERR) TypeError: Cannot convert undefined or null to object
W20220529-15:38:48.077(8)? (STDERR)     at hasOwnProperty (<anonymous>)
W20220529-15:38:48.077(8)? (STDERR)     at AsyncResourceStorage._init (/Users/bohan/cs/codesignal/node_modules/dd-trace/packages/datadog-core/src/storage/async_resource.js:66:41)
W20220529-15:38:48.077(8)? (STDERR)     at emitInitNative (internal/async_hooks.js:203:43)
W20220529-15:38:48.077(8)? (STDERR)     at emitInitScript (internal/async_hooks.js:493:3)
W20220529-15:38:48.077(8)? (STDERR)     at promiseInitHook (internal/async_hooks.js:323:3)
W20220529-15:38:48.078(8)? (STDERR)     at Function.reject (<anonymous>)
W20220529-15:38:48.078(8)? (STDERR)     at process.<anonymous> (packages/inter-process-messaging.js:227:47)
W20220529-15:38:48.078(8)? (STDERR)     at process.emit (events.js:400:28)
W20220529-15:38:48.078(8)? (STDERR)     at process.emit (domain.js:475:12)
W20220529-15:38:48.078(8)? (STDERR)     at process.exit (internal/process/per_thread.js:173:15)
W20220529-15:38:48.078(8)? (STDERR)     at fatalError (internal/async_hooks.js:176:11)
W20220529-15:38:48.078(8)? (STDERR)     at emitInitNative (internal/async_hooks.js:210:5)
W20220529-15:38:48.078(8)? (STDERR)     at emitInitScript (internal/async_hooks.js:493:3)
W20220529-15:38:48.079(8)? (STDERR)     at process.nextTick (internal/process/task_queues.js:133:5)
W20220529-15:38:48.079(8)? (STDERR)     at ConnectionPool.checkIn (/Users/bohan/.meteor/packages/npm-mongo/.4.3.1.udxozx.x3fz++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/mongodb/lib/cmap/connection_pool.js:163:17)
```

**Steps to reproduce**
Added `const tracer = require('dd-trace').init();` to the app startup logic.

**Environment**

* **Operation system:** OSX
* **Node.js version:** 14.19.1
* **Tracer version:** 2.8.0
* **Agent version:** 7
* **Relevant library versions:**

**Comment by rochdev** [comment]
Unfortunately we do not support Meteor since it uses fibers which are incompatible with a few Node built-in modules that we need to use for tracing. You can find more information about the issue in our [documentation](https://docs.datadoghq.com/tracing/setup_overview/compatibility_requirements/nodejs/#unsupported-libraries).

We look forward to support Meteor when https://github.com/meteor/meteor/discussions/11505 is resolved.

**Comment by Twisterking** [comment]
Sorry to "hijack" this issue, but I am also trying to implement tracing into our Meteor application. I got as far as, both the meteor app AND `dd-agent` are starting up correctly. No errors, nothing.

But I also always see in the logs of `dd-agent` the following: `TRACE | INFO | (run.go:243 in Info) | No data received`

So, no data seems to be received and thus I am stuck on the "setup" screen in the datadog dashboard.

What am I doing wrong? I get that meteor is not fully supported, but since everything seems to startup correctly, I am still very surprised to be totally stuck with no errors and no data.

**Comment by sig-bo** [comment]
@Twisterking did you end up finding a solution? we ended up implementing our own utility that sends traces to the Datadog Agent using https://docs.datadoghq.com/tracing/guide/send_traces_to_agent_by_api/.
