### ISSUE TITLE
instrumentation error on Fastify version 4

### ISSUE THREAD

**Issue by inaiat** [DataDog/dd-trace-js#2118]
**Expected behaviour**
simple request must retun http 200 status

**Actual behaviour**
any request return an error 500 with erro message: '"next is not a function"

**Steps to reproduce**
add import import './tracer' on entry point of app

tracer.ts:
```
import tracer from 'dd-trace'
tracer.init({ logInjection: true })
tracer.use('http', {
  blocklist: ['/health'],
})
export default tracer
```

**Environment**

* **Operation system: linux - kernel 5.15.41-1-MANJARO**
* **Node.js version: v16.15.0**
* **Tracer version: 2.9.0**
* **Relevant library versions: fastify v4**

"dependencies": {
    "@fastify/autoload": "^5.0.0",
    "@fastify/awilix": "^3.0.0",
    "@fastify/sensible": "^5.0.0",
    "@fastify/swagger": "^7.2.0",
    "@fastify/type-provider-typebox": "^1.0.0",
    "@sinclair/typebox": "^0.23.5",
    "awilix": "7.0.3",
    "dd-trace": "^2.9.0",
    "env-schema": "5.0.0",
    "fastify": "4.0.0",
    "fastify-plugin": "^3.0.1",
    "nanoid": "^3.0.0"
  }

```
"type": "TypeError",
      "message": "next is not a function",
      "stack":
          TypeError: next is not a function
              at /inaiat/node_modules/dd-trace/packages/datadog-instrumentations/src/fastify.js:129:41
              at exports.AsyncResource.runInAsyncScope (node:async_hooks:202:9)
              at Object.preParsing (/inaiat/node_modules/dd-trace/packages/datadog-instrumentations/src/fastify.js:129:19)
              at next (/inaiat/node_modules/fastify/lib/route.js:501:16)
              at preParsingHookRunner (/inaiat/node_modules/fastify/lib/route.js:524:3)
              at runPreParsing (/inaiat/node_modules/fastify/lib/route.js:475:5)
              at next (/inaiat/node_modules/fastify/lib/hooks.js:168:7)
              at /inaiat/node_modules/dd-trace/packages/datadog-instrumentations/src/fastify.js:62:29
              at exports.AsyncResource.runInAsyncScope (node:async_hooks:202:9)
              at arguments.<computed> (/inaiat/node_modules/dd-trace/packages/datadog-instrumentations/src/fastify.js:61:38)
```

**Comment by rochdev** [comment]
This was fixed in #2114 and we're in the process of shipping a new patch release.
