### ISSUE TITLE
Bind the init()

### ISSUE THREAD

**Issue by gajus** [DataDog/dd-trace-js#222]
```js
import {
  init
} from 'dd-trace';

init({
  hostname: process.env.DD_AGENT_SERVICE_HOST,
  port: process.env.DD_AGENT_SERVICE_PORT
});

```

Results in:

```
/srv/node_modules/dd-trace/src/proxy.js:49
    if (this._tracer === noop) {
             ^

TypeError: Cannot read property '_tracer' of undefined
    at init (/srv/node_modules/dd-trace/src/proxy.js:49:14)
    at Object.<anonymous> (/srv/dist/bin/index.js:12:21)
    at Module._compile (internal/modules/cjs/loader.js:678:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:689:10)
    at Module.load (internal/modules/cjs/loader.js:589:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:528:12)
    at Function.Module._load (internal/modules/cjs/loader.js:520:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:719:10)
    at startup (internal/bootstrap/node.js:228:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:576:3)

```

Solution:

Bind `init` method to the dd-trace object prior to exporting it.

**Comment by rochdev** [comment]
Thanks for the tip! In the meantime, you can use `import * as tracer from 'dd-trace'` as a workaround.

**Comment by rochdev** [comment]
We have now released official support for TypeScript. However, you can't import individual methods, and instead have to do:

```js
import tracer from 'dd-trace';
```

@gajus Would you still prefer to be able to use individual methods as bound functions? I wonder if that would make it confusing since it would be unclear what object the functions are operating on?

**Comment by andrewardito** [comment]
Hey @gajus we're going to close this issue out, but please reach out if you have any further issues!
