### ISSUE TITLE
loading request-promise crashes on 2.13.0

### ISSUE THREAD

**Issue by jinroh** [DataDog/dd-trace-js#2307]
**Expected behaviour**
Project should start and be instrumented.

**Actual behaviour**
Crashes on start

```js
'use strict'
const ddtracer = require('dd-trace').init()
const rp = require('request-promise')
console.log('bye bye.')

/* package.json:
{
  "dependencies": {
    "request": "2.88.2",
    "request-promise": "4.2.6"
  }
}*/
```

Crashes with the following trace:

```
TypeError: instrumentations[packageName] is not iterable
    at /XXX/node_modules/dd-trace/packages/datadog-instrumentations/src/helpers/register.js:25:66
    at safeHook (/XXX/node_modules/dd-trace/packages/datadog-instrumentations/src/helpers/hook.js:20:12)
    at Hook.Module.require (/XXX/node_modules/dd-trace/packages/dd-trace/src/ritm.js:114:33)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/XXX/node_modules/tough-cookie/lib/cookie.js:32:11)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Module._load (node:internal/modules/cjs/loader:827:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at Hook.Module.require (/XXX/node_modules/dd-trace/packages/dd-trace/src/ritm.js:72:33)
    at require (node:internal/modules/cjs/helpers:102:18)
    at /XXX/node_modules/request-promise/lib/rp.js:14:9
    at module.exports (/XXX/node_modules/stealthy-require/lib/index.js:38:9)
    at Object.<anonymous> (/XXX/node_modules/request-promise/lib/rp.js:10:19)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Module._load (node:internal/modules/cjs/loader:827:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at Hook.Module.require (/XXX/node_modules/dd-trace/packages/dd-trace/src/ritm.js:72:33)
    at require (node:internal/modules/cjs/helpers:102:18)
```

**Environment**

* **Operation system:**
* **Node.js version:** v18.2.0
* **Tracer version:** v2.13.0
* **Agent version:** N/A
* **Relevant library versions:** see below

**Comment by rochdev** [comment]
It looks like `request-promise` uses [stealthy-require](https://www.npmjs.com/package/stealthy-require) which is causing issues with how we intercept modules when required. I'm looking into how to fix this, but in the meantime it should be possible to use dd-trace 2.12.1 or older which was using a different logic for loading integrations.
