### ISSUE TITLE
TypeError: 'getOwnPropertyDescriptor': property 'dd' that is incompatible with the existing property

### ISSUE THREAD

**Issue by almorelle** [DataDog/dd-trace-js#2322]
Hello,

I've tried upgrading past the 2.0.0 but our app crashes for any version past that one (3.0.0 equally). Any insight on how we could solve this or if there's an issue somewhere?

It looks related to #1830 but not sure it's the same.

Thank you very much in advancce for your answers.

**Bug Description**
After upgrading to dd-trace@2.x.x (same in 3.0.0), programs started crashing on their first log calls with this stack trace:

```
/home/node/redacted/node_modules/winston/lib/winston/logger.js:307
      throw ex;
      ^

TypeError: 'getOwnPropertyDescriptor' on proxy: trap returned descriptor for property 'dd' that is incompatible with the existing property in the proxy target
    at Function.assign (<anonymous>)
    at Console._write (/home/node/redacted/winston-transport/index.js:91:50)
    at doWrite (/home/node/redacted/node_modules/winston-transport/node_modules/readable-stream/lib/_stream_writable.js:428:64)
    at writeOrBuffer (/home/node/redacted/node_modules/winston-transport/node_modules/readable-stream/lib/_stream_writable.js:417:5)
    at Console.Writable.write (/home/node/redacted/node_modules/winston-transport/node_modules/readable-stream/lib/_stream_writable.js:334:11)
    at DerivedLogger.ondata (/home/node/redacted/node_modules/readable-stream/lib/_stream_readable.js:681:20)
    at DerivedLogger.emit (events.js:400:28)
    at DerivedLogger.emit (domain.js:475:12)
    at addChunk (/home/node/redacted/node_modules/readable-stream/lib/_stream_readable.js:298:12)
    at readableAddChunk (/home/node/redacted/node_modules/readable-stream/lib/_stream_readable.js:280:11)
    at DerivedLogger.Readable.push (/home/node/redacted/node_modules/readable-stream/lib/_stream_readable.js:241:10)
    at DerivedLogger.Transform.push (/home/node/redacted/node_modules/readable-stream/lib/_stream_transform.js:139:32)
    at DerivedLogger._transform (/home/node/redacted/node_modules/winston/lib/winston/logger.js:305:12)
    at DerivedLogger.Transform._read (/home/node/redacted/node_modules/readable-stream/lib/_stream_transform.js:177:10)
    at DerivedLogger.Transform._write (/home/node/redacted/node_modules/readable-stream/lib/_stream_transform.js:164:83)
    at doWrite (/home/node/redacted/node_modules/readable-stream/lib/_stream_writable.js:409:139)
    at writeOrBuffer (/home/node/redacted/node_modules/readable-stream/lib/_stream_writable.js:398:5)
    at DerivedLogger.Writable.write (/home/node/redacted/node_modules/readable-stream/lib/_stream_writable.js:307:11)
    at DerivedLogger.<anonymous> (/home/node/redacted/node_modules/dd-trace/packages/datadog-instrumentations/src/winston.js:20:20)
    at DerivedLogger.log (/home/node/redacted/node_modules/winston/lib/winston/logger.js:210:12)
    at ExceptionHandler._uncaughtException (/home/node/redacted/node_modules/winston/lib/winston/exception-handler.js:220:17)
    at process.emit (events.js:412:35)
    at process.emit (/home/node/redacted/node_modules/source-map-support/source-map-support.js:485:21)
    at process._fatalException (internal/process/execution.js:167:25)
```

Also here's an example of some small custom instrumentation in the tracer we have:

```
apm = tracer.init({
   service: "redacted",
   env: process.env.NODE_ENV,
   tags: defaultTags,
   logInjection: true,
   runtimeMetrics: true,
});
apm.use("http", {
   blocklist: ["/health-check", "/metrics", "/security/report/csp"],
});
```

**Environment**

* **Operation system:**
* **Runs inside node:** 14.18.2-buster-slim
* **Tracer version:** tested from 2.0.0 to 3.0.0
* **Agent version:** 7
* **Winston version:** 3.2.1

**Comment by rochdev** [comment]
Can you provide a reproduction snippet? I can reproduce this with a regular object when using a proxy with non-configurable properties or a non-extensible object, but I'm unable to make it fail with Winston because it seems it copies the properties internally since 3.0.

**Comment by rochdev** [comment]
I added some safety nets which hopefully will cover your issue.

**Comment by almorelle** [comment]
Thank you very much @rochdev, I'll try this out and let you know.
