### ISSUE TITLE
Graphql plugin doesn't work with apollo schema stitching

### ISSUE THREAD

**Issue by Alfarlost** [DataDog/dd-trace-js#235]
I'm using apollo schema stitching and receive next error: 
```
TypeError: Cannot redefine property: _datadog_operation
    at Function.defineProperties (<anonymous>)
    at Object.executeWithTrace (/home/node/node_modules/dd-trace/src/plugins/graphql.js:29:14)
    at /home/node/node_modules/graphql-tools/dist/stitching/delegateToSchema.js:84:52
    at step (/home/node/node_modules/graphql-tools/dist/stitching/delegateToSchema.js:32:23)
    at Object.next (/home/node/node_modules/graphql-tools/dist/stitching/delegateToSchema.js:13:53)
    at /home/node/node_modules/graphql-tools/dist/stitching/delegateToSchema.js:7:71
    at new Promise (<anonymous>)
    at __awaiter (/home/node/node_modules/graphql-tools/dist/stitching/delegateToSchema.js:3:12)
    at delegateToSchemaImplementation (/home/node/node_modules/graphql-tools/dist/stitching/delegateToSchema.js:57:12)
    at Object.delegateToSchema [as default] (/home/node/node_modules/graphql-tools/dist/stitching/delegateToSchema.js:53:12)
```
I wonder if just adding `writable: true` to line 29 `defineProperties` will be enough.

**Comment by Alfarlost** [comment]
@rochdev, you can use the full example described in official docs
https://www.apollographql.com/docs/graphql-tools/schema-stitching.html
Just checked, it throws the same error.

**Comment by rochdev** [comment]
Thanks for the reference! I'll take a look.
