### ISSUE TITLE
DD_AGENT_HOST is not used properly when ipv6 address

### ISSUE THREAD

**Issue by clhuang** [DataDog/dd-trace-js#2449]
**Expected behaviour**
In an IPv6 EKS cluster, $DD_AGENT_HOST is set to an IPv6 address, and requests should be sent to http://[$DD_AGENT_HOST]:8126

**Actual behaviour**
URLs are constructed using code like https://github.com/DataDog/dd-trace-js/blame/master/packages/dd-trace/src/exporters/agent/index.js#L11, this results in invalid URLs such as http://2602:fb33:0:1::deed:8126

example error:
```
TypeError [ERR_INVALID_URL]: Invalid URL
    at new NodeError (node:internal/errors:372:5)
    at URL.onParseError (node:internal/url:553:9)
    at new URL (node:internal/url:629:5)
    at new AgentExporter (/app/dist/server/node_modules/dd-trace/packages/dd-trace/src/exporters/agent/index.js:10:24)
    at new DatadogTracer (/app/dist/server/node_modules/dd-trace/packages/dd-trace/src/opentracing/tracer.js:42:22)
    at new DatadogTracer (/app/dist/server/node_modules/dd-trace/packages/dd-trace/src/tracer.js:18:5)
    at Tracer.init (/app/dist/server/node_modules/dd-trace/packages/dd-trace/src/proxy.js:54:26)
    at Object.<anonymous> (/app/dist/server/node_modules/@scale/shared/dist/src/tracer.js:21:22)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10) {
  input: 'http://2602:fb33:0:1::deed:8126',
  code: 'ERR_INVALID_URL'
}
```

**Steps to reproduce**

**Environment**

* **Operation system:**
* **Node.js version:**
* **Tracer version:**
* **Agent version:**
* **Relevant library versions:**

**Comment by clhuang** [comment]
suggest using `require('url').format`-- while it is a legacy function, they have decided not to deprecate it as there is no suitable replacement as of yet.

**Comment by clhuang** [comment]
@rochdev can we reopen this? This still breaks, as noted in my comments in #2486 with the error:
```
Request to the agent: {"path":"/v0.4/traces","method":"PUT","headers":{"Content-Type":"application/msgpack","Datadog-Meta-Tracer-Version":"3.9.3","X-Datadog-Trace-Count":"5","Datadog-Meta-Lang":"nodejs","Datadog-Meta-Lang-Version":"v16.16.0","Datadog-Meta-Lang-Interpreter":"v8"},"url":"http://[2602:fb33::348d]:8126/"}
Error: getaddrinfo ENOTFOUND [2602:fb33::348d]
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:71:26)
    at GetAddrInfoReqWrap.callbackTrampoline (node:internal/async_hooks:130:17) {
  errno: -3008,
  code: 'ENOTFOUND',
  syscall: 'getaddrinfo',
  hostname: '[2602:fb33::348d]'
}
```

**Comment by Qard** [comment]
#2691 should hopefully solve this properly. :)

**Comment by jcarvalho** [comment]
Did a little digging here, and I believe I've found the cause of the issue. In the code introduced in https://github.com/DataDog/dd-trace-js/pull/2691, the `request` function is only calling `urlToOptions` when the given URL is a string. However, from what I could tell, by the point the Tracer goes to flush the traces, it invokes `request` with a fully-built `URL` object, so the normalization step is not applied.

By changing [this line](https://github.com/DataDog/dd-trace-js/blob/v3.17.1/packages/dd-trace/src/exporters/common/request.js#L57) as follows,it all seems to work fine:

```diff
- const url = typeof options.url === 'object' ? options.url : fromUrlString(options.url)
+ const url = typeof options.url === 'object' ? urlToOptions(options.url) : fromUrlString(options.url)
```

**Comment by jcarvalho** [comment]
@tlhunter I can confirm this is now working as expected, thanks for the fix!
