### ISSUE TITLE
dd-trace errors when nodejs upgraded to 19.0.0

### ISSUE THREAD

**Issue by farahhameedDev** [DataDog/dd-trace-js#2484]
**Expected behaviour**
dd-trace 3.6.0 should work with nodejs 19.0.0
**Actual behaviour** Following errors shows up when nodejs version upgraded to 19.0.0
```
 [ERR_INVALID_ARG_TYPE]: The "this" argument must be an instance of Performance. Received undefined
    at now (node:internal/perf/performance:139:5)
    at DatadogSpan._createContext (/app/node_modules/dd-trace/packages/dd-trace/src/opentracing/span.js:164:60)
    at new DatadogSpan (/app/node_modules/dd-trace/packages/dd-trace/src/opentracing/span.js:36:30)
    at DatadogTracer.startSpan (/app/node_modules/dd-trace/packages/dd-trace/src/opentracing/tracer.js:56:18)
    at DNSPlugin.startSpan (/app/node_modules/dd-trace/packages/datadog-plugin-dns/src/index.js:26:30)
    at DNSPlugin.addSubs.span.span (/app/node_modules/dd-trace/packages/datadog-plugin-dns/src/index.js:39:25)
    at Subscription._handler (/app/node_modules/dd-trace/packages/dd-trace/src/plugins/plugin.js:12:9)
    at Channel.publish (node:diagnostics_channel:56:9)
    at /app/node_modules/dd-trace/packages/datadog-instrumentations/src/dns.js:72:15
    at AsyncResource.runInAsyncScope (node:async_hooks:203:9)
TypeError: Cannot destructure property 'span' of 'storage.getStore(...)' as it is undefined.
    at /app/node_modules/dd-trace/packages/datadog-plugin-dns/src/index.js:45:15
    at Subscription._handler (/app/node_modules/dd-trace/packages/dd-trace/src/plugins/plugin.js:12:9)
    at Channel.publish (node:diagnostics_channel:56:9)
    at /app/node_modules/dd-trace/packages/datadog-instrumentations/src/dns.js:78:18
    at AsyncResource.runInAsyncScope (node:async_hooks:203:9)
    at bound (node:async_hooks:235:16)
    at process.processTicksAndRejections (node:internal/process/task_queues:83:21)
{"level":30,"time":1667309354619,"pid":1,"hostname":"smough-7b89c6d4d4-dbkrx","created":1667309354445,"started":1667309354583,"host":"0.0.0.0","port":80,"protocol":"http","id":"smough-7b89c6d4d4-dbkrx:1:l9y8xvil","uri":"http://0.0.0.0:80","address":"0.0.0.0","msg":"server started"}
{"level":30,"time":1667309354620,"pid":1,"hostname":"smough-7b89c6d4d4-dbkrx","tags":[],"data":"Listening on http://0.0.0.0:80"}
TypeError [ERR_INVALID_ARG_TYPE]: The "this" argument must be an instance of Performance. Received undefined
    at now (node:internal/perf/performance:139:5)
    at DatadogSpan._createContext (/app/node_modules/dd-trace/packages/dd-trace/src/opentracing/span.js:164:60)
    at new DatadogSpan (/app/node_modules/dd-trace/packages/dd-trace/src/opentracing/span.js:36:30)
    at DatadogTracer.startSpan (/app/node_modules/dd-trace/packages/dd-trace/src/opentracing/tracer.js:56:18)
    at /app/node_modules/dd-trace/packages/datadog-plugin-http/src/client.js:37:32
    at Subscription._handler (/app/node_modules/dd-trace/packages/dd-trace/src/plugins/plugin.js:12:9)
    at Channel.publish (node:diagnostics_channel:56:9)
    at /app/node_modules/dd-trace/packages/datadog-instrumentations/src/http/client.js:52:23
    at AsyncResource.runInAsyncScope (node:async_hooks:203:9)
    at Object.request (/app/node_modules/dd-trace/packages/datadog-instrumentations/src/http/client.js:51:28)
TypeError [ERR_INVALID_ARG_TYPE]: The "this" argument must be an instance of Performance. Received undefined
    at now (node:internal/perf/performance:139:5)
    at DatadogSpan._createContext (/app/node_modules/dd-trace/packages/dd-trace/src/opentracing/span.js:164:60)
    at new DatadogSpan (/app/node_modules/dd-trace/packages/dd-trace/src/opentracing/span.js:36:30)
    at DatadogTracer.startSpan (/app/node_modules/dd-trace/packages/dd-trace/src/opentracing/tracer.js:56:18)
    at /app/node_modules/dd-trace/packages/datadog-plugin-net/src/index.js:45:32
    at Subscription._handler (/app/node_modules/dd-trace/packages/dd-trace/src/plugins/plugin.js:12:9)
    at Channel.publish (node:diagnostics_channel:56:9)
    at /app/node_modules/dd-trace/packages/datadog-instrumentations/src/net.js:48:20
    at AsyncResource.runInAsyncScope (node:async_hooks:203:9)
    at TLSSocket.connect (/app/node_modules/dd-trace/packages/datadog-instrumentations/src/net.js:43:26)
TypeError [ERR_INVALID_ARG_TYPE]: The "this" argument must be an instance of Performance. Received undefined
    at now (node:internal/perf/performance:139:5)
    at DatadogSpan._createContext (/app/node_modules/dd-trace/packages/dd-trace/src/opentracing/span.js:164:60)
    at new DatadogSpan (/app/node_modules/dd-trace/packages/dd-trace/src/opentracing/span.js:36:30)
    at DatadogTracer.startSpan (/app/node_modules/dd-trace/packages/dd-trace/src/opentracing/tracer.js:56:18)
    at DNSPlugin.startSpan (/app/node_modules/dd-trace/packages/datadog-plugin-dns/src/index.js:26:30)
    at DNSPlugin.addSubs.span.span (/app/node_modules/dd-trace/packages/datadog-plugin-dns/src/index.js:39:25)
    at Subscription._handler (/app/node_modules/dd-trace/packages/dd-trace/src/plugins/plugin.js:12:9)
    at Channel.publish (node:diagnostics_channel:56:9)
    at /app/node_modules/dd-trace/packages/datadog-instrumentations/src/dns.js:72:15
    at AsyncResource.runInAsyncScope (node:async_hooks:203:9)
TypeError: Cannot destructure property 'span' of 'storage.getStore(...)' as it is undefined.
    at /app/node_modules/dd-trace/packages/datadog-plugin-dns/src/index.js:45:15
    at Subscription._handler (/app/node_modules/dd-trace/packages/dd-trace/src/plugins/plugin.js:12:9)
    at Channel.publish (node:diagnostics_channel:56:9)
    at GetAddrInfoReqWrap.<anonymous> (/app/node_modules/dd-trace/packages/datadog-instrumentations/src/dns.js:78:18)
    at AsyncResource.runInAsyncScope (node:async_hooks:203:9)
    at GetAddrInfoReqWrap.bound [as callback] (node:async_hooks:235:16)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:109:8)
    at GetAddrInfoReqWrap.callbackTrampoline (node:internal/async_hooks:132:17)
TypeError: Cannot read properties of undefined (reading 'span')
    at /app/node_modules/dd-trace/packages/datadog-plugin-net/src/index.js:68:38
    at Subscription._handler (/app/node_modules/dd-trace/packages/dd-trace/src/plugins/plugin.js:12:9)
    at Channel.publish (node:diagnostics_channel:56:9)
    at TLSSocket.<anonymous> (/app/node_modules/dd-trace/packages/datadog-instrumentations/src/net.js:110:18)
    at AsyncResource.runInAsyncScope (node:async_hooks:203:9)
    at TLSSocket.bound (node:async_hooks:235:16)
    at Object.onceWrapper (node:events:627:28)
    at TLSSocket.emit (node:events:525:35)
    at TLSSocket.emit (node:domain:489:12)
    at /app/node_modules/dd-trace/packages/datadog-instrumentations/src/net.js:58:27
TypeError: Cannot read properties of undefined (reading 'span')
    at defaultFinish (/app/node_modules/dd-trace/packages/datadog-plugin-net/src/index.js:78:21)
    at Subscription._handler (/app/node_modules/dd-trace/packages/dd-trace/src/plugins/plugin.js:12:9)
    at Channel.publish (node:diagnostics_channel:56:9)
    at TLSSocket.<anonymous> (/app/node_modules/dd-trace/packages/datadog-instrumentations/src/net.js:106:71)
    at AsyncResource.runInAsyncScope (node:async_hooks:203:9)
    at TLSSocket.bound (node:async_hooks:235:16)
    at Object.onceWrapper (node:events:627:28)
    at TLSSocket.emit (node:events:525:35)
    at TLSSocket.emit (node:domain:489:12)
    at /app/node_modules/dd-trace/packages/datadog-instrumentations/src/net.js:58:27
TypeError: Cannot read properties of undefined (reading 'span')
    at /app/node_modules/dd-trace/packages/datadog-plugin-http/src/client.js:58:38
    at Subscription._handler (/app/node_modules/dd-trace/packages/dd-trace/src/plugins/plugin.js:12:9)
    at Channel.publish (node:diagnostics_channel:56:9)
    at finish (/app/node_modules/dd-trace/packages/datadog-instrumentations/src/http/client.js:68:28)
    at IncomingMessage.<anonymous> (/app/node_modules/dd-trace/packages/datadog-instrumentations/src/http/client.js:77:59)
    at AsyncResource.runInAsyncScope (node:async_hooks:203:9)
    at IncomingMessage.bound (node:async_hooks:235:16)
    at IncomingMessage.emit (node:events:525:35)
    at IncomingMessage.emit (node:domain:489:12)
    at endReadableNT (node:internal/streams/readable:1359:12)


```
**Steps to reproduce**
Upgrade nodejs version to 19.0.0

**Environment**

* **Operation system:** Alpine 3.15
* **Node.js version:** 19.0.0
* **Tracer version:** 3.6.0
* **Agent version:** 
* **Relevant library versions:**

**Comment by cirosantilli** [comment]
OK just extracting the solution of the PR here for Google:

```
const { performance } = require('perf_hooks')
const now = performance.now.bind(performance)
const t0 = now()
for (i = 0; i < 1000000; i++)
  ;
console.log((now() - t0)/1000.0)
```
