### ISSUE TITLE
Failure to enable mongo tracing

### ISSUE THREAD

**Issue by matehuszarik** [DataDog/dd-trace-js#2610]
**Expected behaviour**
Mongo tracing should work fine.

**Actual behaviour**
Keep getting these errors when trace init is called and spans are not showing up in APM.
```
No original method query.
Error: No original method query.
    at assertMethod (/app/node_modules/@ghostmonitor/lib-datadog-trace/node_modules/dd-trace/packages/datadog-shimmer/src/shimmer.js:116:11)
    at wrapMethod (/app/node_modules/@ghostmonitor/lib-datadog-trace/node_modules/dd-trace/packages/datadog-shimmer/src/shimmer.js:35:3)
    at Object.wrap (/app/node_modules/@ghostmonitor/lib-datadog-trace/node_modules/dd-trace/packages/datadog-shimmer/src/shimmer.js:65:7)
    at /app/node_modules/@ghostmonitor/lib-datadog-trace/node_modules/dd-trace/packages/datadog-instrumentations/src/mongodb-core.js:31:11
    at /app/node_modules/@ghostmonitor/lib-datadog-trace/node_modules/dd-trace/packages/datadog-instrumentations/src/helpers/register.js:35:29
    at safeHook (/app/node_modules/@ghostmonitor/lib-datadog-trace/node_modules/dd-trace/packages/datadog-instrumentations/src/helpers/hook.js:20:12)
    at Module.Hook.Module.require (/app/node_modules/@ghostmonitor/lib-datadog-trace/node_modules/dd-trace/packages/dd-trace/src/ritm.js:123:33
```

```
No original method maybePromise.
Error: No original method maybePromise.
    at assertMethod (/app/node_modules/@ghostmonitor/lib-datadog-trace/node_modules/dd-trace/packages/datadog-shimmer/src/shimmer.js:116:11)
    at wrapMethod (/app/node_modules/@ghostmonitor/lib-datadog-trace/node_modules/dd-trace/packages/datadog-shimmer/src/shimmer.js:35:3)
    at Object.wrap (/app/node_modules/@ghostmonitor/lib-datadog-trace/node_modules/dd-trace/packages/datadog-shimmer/src/shimmer.js:65:7)
    at /app/node_modules/@ghostmonitor/lib-datadog-trace/node_modules/dd-trace/packages/datadog-instrumentations/src/mongodb-core.js:50:11
    at /app/node_modules/@ghostmonitor/lib-datadog-trace/node_modules/dd-trace/packages/datadog-instrumentations/src/helpers/register.js:35:29
    at safeHook (/app/node_modules/@ghostmonitor/lib-datadog-trace/node_modules/dd-trace/packages/datadog-instrumentations/src/helpers/hook.js:20:12)
    at Module.Hook.Module.require (/app/node_modules/@ghostmonitor/lib-datadog-trace/node_modules/dd-trace/packages/dd-trace/src/ritm.js
```
**Code**
```
...
const tracer = require('dd-trace').init({
    env: environment,
    hostname: hostName,
    port: parseInt(port),
    tags: {
      hostName: os.hostname(),
      env: environment
    },
    service,
    plugins: false
  })

tracer.use('mongodb', {
    service: 'mongo'
  })
```

**Environment**

* **Operation system:** linux
* **Node.js version:** 16.18.1
* **Tracer version:** 3.9.3
* **Agent version:**
* **Relevant library versions:**
  * mongoose 6.8.0
  * mongodb 4.12.1 (indirect dependency)

**Comment by bengl** [comment]
Usually this sort of error happens when the library's structure changes so that our instrumentation code no longer works. That being said, we test with that version and it seems to work. Is there any chance you could provide a small reproduction example?

**Comment by matehuszarik** [comment]
I spent some time understanding the problem and in our case, I had to change the plugin name.

```
tracer.use('mongodb-core', {
    service: 'mongo'
  })
```

I'm not sure if this is intended and the changelog is unclear between major versions but I'm closing the issue.

**Comment by francois-spectre** [comment]
I do have the same error with the dd-trace v3.13.0 but with not with v3.12.0...
