### ISSUE TITLE
(node:54) Warning: Accessing non-existent property 'RedisClient' of module exports inside circular dependency

### ISSUE THREAD

**Issue by jeremysf** [DataDog/dd-trace-js#2658]
**Expected behaviour**
Node should not print any warnings on startup when dd-trace is imported.

**Actual behaviour**
The following warning is printed when node starts up when dd-trace is imported:
```
(node:54) Warning: Accessing non-existent property 'RedisClient' of module exports inside circular dependency
    at emitCircularRequireWarning (node:internal/modules/cjs/loader:755:11)
    at Object.get (node:internal/modules/cjs/loader:771:5)
    at /workspaces/circuitly/node_modules/dd-trace/packages/datadog-instrumentations/src/redis.js:49:22
    at /workspaces/circuitly/node_modules/dd-trace/packages/datadog-instrumentations/src/helpers/register.js:35:29
    at safeHook (/workspaces/circuitly/node_modules/dd-trace/packages/datadog-instrumentations/src/helpers/hook.js:20:12)
    at Module.Hook.Module.require (/workspaces/foo/node_modules/dd-trace/packages/dd-trace/src/ritm.js:128:33)
    at require (node:internal/modules/cjs/helpers:103:18)
    at Object.<anonymous> (/workspaces/circuitly/node_modules/redis/lib/debug.js:3:13)
    at Module._compile (node:internal/modules/cjs/loader:1159:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1213:10)
```

When updating to redis > 3.1.2 node hangs on startup (i.e. prints no logs at all).

**Steps to reproduce**
Make a node project that imports `dd-trace`. It doesn't even need to initialize it, just import it. Make sure your node project also imports redis. 

The problem occurs even with `DD_TRACE_DISABLED_PLUGINS=redis` is set. Also if you do initialize the tracer and pass the option `plugins: false`, it still occurs. 

It appears plugins are loaded regardless of the environment variable or options.

**Environment**
Docker: 

```
FROM --platform=linux/amd64 buildpack-deps:jammy
ENV NODE_VERSION 18.12.1
```

* **Operation system:**
Docker linux/amd64 buildpack-deps:jammy
* **Node.js version:**
18.12.1
* **Tracer version:**
`dd-trace: 3.10.0`
* **Agent version:**
7.40.1
* **Relevant library versions:**
`"redis": "3.1.2"`

**Comment by jeremysf** [comment]
FYI, my project is ESM and TypeScript 4.3.5 and using esbuild 0.15.6 to bundle (not the node_modules, just the TypeScript source code of my app).

I am not using the experimental loader, but the problem occurs either way.

**Comment by Qard** [comment]
Neither ESM nor bundling is supported currently. ESM has experimental support with the loader, but no support guarantees are promised there yet. Without the loader it will not work at all.

**Comment by Qard** [comment]
As far as I can tell it seems the patches are trying to apply too early due to some sort of circular module import. Strangely though this doesn't happen when using either CJS or ESM on its own, so probably something weird going on in the bundling. I don't know why the bundler would cause something like that though, especially if you're not bundling dependencies. Very strange. 🤔 

Any more you can share on what the code itself is doing? Can you provide a reduced reproduction case to demonstrate what you did that triggered the error?

**Comment by CarlosCondor** [comment]
I have the same problem. node 16.15.1,  dd-trace 2.4.2, redis 3.1.2

**Comment by khanayan123** [comment]
Hi @jeremysf & @CarlosCondor I have just tested this locally, the bug is still there for redis versions 3.x.x but not for version 4.x.x. So for a quick fix you can switch to redis version 4.x.x

**Comment by khanayan123** [comment]
/remind me about this issue in 1 week

**Comment by khanayan123** [comment]
Closing due to inactivity, if you are still having this problem please feel free to reopen
