### ISSUE TITLE
dd-trace breaks mocha.run(...).on(...)

### ISSUE THREAD

**Issue by vincentcr** [DataDog/dd-trace-js#2690]
**Expected behaviour**
`dd-trace/init` should monkey patch packages transparently.

**Actual behaviour**

`dd-trace/init` changes `mocha.run` to return `undefined` instead of the `Mocha.Runner` like the underlying implementation.

See doc: https://mochajs.org/api/mocha#run

**Steps to reproduce**
```
import 'dd-trace/init'
import Mocha from 'mocha'
const mocha = new Mocha()

mocha
  .run((numFailures) => {
    console.log('mocha finished with', numFailures, 'failures')
  })
  .on('fail', (test) => {
    console.log('test failed', test.fullTitle)
  }) 
```

Throws: 
```
     Uncaught TypeError: Cannot read properties of undefined (reading 'on')
      at Object.<anonymous> (scripts/test_case.ts:14:5)
      at Module._compile (node:internal/modules/cjs/loader:1159:14)
      at Module.m._compile (node_modules/ts-node/src/index.ts:1056:23)
      at Module._extensions..js (node:internal/modules/cjs/loader:1213:10)
      at Object.require.extensions.<computed> [as .ts] (node_modules/ts-node/src/index.ts:1059:12)
      at Module.load (node:internal/modules/cjs/loader:1037:32)
      at Function.Module._load (node:internal/modules/cjs/loader:878:12)
      at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
      at main (node_modules/ts-node/src/bin.ts:198:14)
      at Object.<anonymous> (node_modules/ts-node/src/bin.ts:288:3)
```
This script runs without error when the dd-trace import is commented out.

**Environment**

* **Operation system:** Mac
* **Node.js version:** 18
* **Tracer version:** v2 and v3. works on v1
* **Agent version:**
* **Relevant library versions:**

**Comment by juan-fernandez** [comment]
hi @vincentcr! Thanks for finding the bug and attaching a reproducible case. I fix the bug in this PR: https://github.com/DataDog/dd-trace-js/pull/2694

**Comment by juan-fernandez** [comment]
Just as a note, I realise that you might not be attempting to use CI visibility, but if you do, keep in mind that CI visibility is initialized by passing `NODE_OPTIONS='-r dd-trace/ci/init'`: https://docs.datadoghq.com/continuous_integration/tests/javascript/?tab=onpremisesciproviderdatadogagent#instrument-your-tests 😄

**Comment by vincentcr** [comment]
@juan-fernandez thanks for the quick fix! What would the timeline look like for that fix to find its way into an npm release? (Just so I know if it's worth it for us to look for workarounds in the meantime).

And also thanks for the doc I wasn't aware of a different import path for CI 🙂

**Comment by juan-fernandez** [comment]
> @juan-fernandez thanks for the quick fix! What would the timeline look like for that fix to find its way into an npm release? (Just so I know if it's worth it for us to look for workarounds in the meantime).
> 
> And also thanks for the doc I wasn't aware of a different import path for CI 🙂

you're welcome! We don't have a fixed timeline, but it's highly likely that it either happens this week or early next week
