### ISSUE TITLE
validateStatus is not called for Hapi errors 

### ISSUE THREAD

**Issue by BrettHoutz** [DataDog/dd-trace-js#2780]
**Expected behaviour**
When a Boom error is thrown in a Hapi route handler, 4xx client errors are not reported as errors. Only 5xx server errors should be reported as such.

**Actual behaviour**
When a Boom error is thrown in a Hapi route handler, the `validateStatus` function provided to the hapi plugin is not invoked. This makes it so that 4xx client errors are reported as errors.

**Steps to reproduce**

This example app demonstrates the issue. The `code` log message in validateStatus is printed when `/ok` is hit, but not when `/bad` is hit.

```js
const dd = require('dd-trace');

dd.tracer.init({
  service: 'my-terrible-service',
  logInjection: true,
});
dd.tracer.use('hapi', {
  validateStatus(code) {
    console.log('code', code);
    return code < 500;
  },
});

const Hapi = require('@hapi/hapi');
const Boom = require('@hapi/boom');

const server = Hapi.server({
  port: 8080,
});

server.route([{
  method: 'GET',
  path: '/bad',
  handler: async () => {
    throw Boom.badRequest('Bad Request');
  },
}, {
  method: 'GET',
  path: '/ok',
  handler: async () => {
    return { message: 'OK' };
  },
}]);

server.start().then(() => {
  console.log('server listening');
});
```

This is the debug log that's printed when the `/bad` endpoint is hit (`error: 1` is set).

```
{"trace_id":"4b476df7b5f97635","span_id":"4b476df7b5f97635","parent_id":"0000000000000000","name":"hapi.request","resource":"GET /bad","error":1,"meta":{"_dd.p.dm":"-0","service":"my-terrible-service","version":"1.0.0","runtime-id":"5a0cd9cc-b227-41db-9558-0feac16acb51","component":"hapi","error.message":"Bad Request","error.type":"Error","error.stack":"Error: Bad Request\n    at handler (/Users/bretthoutz/test/index.js:25:16)\n    at exports.Manager.execute (/Users/bretthoutz/test/node_modules/@hapi/hapi/lib/toolkit.js:57:29)\n    at internals.handler (/Users/bretthoutz/test/node_modules/@hapi/hapi/lib/handler.js:46:48)\n    at exports.execute (/Users/bretthoutz/test/node_modules/@hapi/hapi/lib/handler.js:31:36)\n    at /Users/bretthoutz/test/node_modules/dd-trace/packages/datadog-instrumentations/src/hapi.js:104:22\n    at AsyncResource.runInAsyncScope (node:async_hooks:204:9)\n    at /Users/bretthoutz/test/node_modules/dd-trace/packages/datadog-instrumentations/src/hapi.js:101:26\n    at Request._lifecycle (/Users/bretthoutz/test/node_modules/@hapi/hapi/lib/request.js:370:68)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async Request._execute (/Users/bretthoutz/test/node_modules/@hapi/hapi/lib/request.js:280:9)","http.url":"http://localhost:8080/bad","http.method":"GET","span.kind":"server","http.useragent":"PostmanRuntime/7.30.1","http.route":"/bad","http.status_code":"400","language":"javascript"},"metrics":{"_dd.agent_psr":1,"_dd.top_level":1,"_dd.measured":1,"process_id":20792,"_sampling_priority_v1":1},"start":1675809968425027000,"duration":16759766,"service":"my-terrible-service","type":"web"}
```

**Environment**

* **Operation system:** MacOS, Alpine Linux
* **Node.js version:** 18.14.0
* **Tracer version:** 3.13.2
* **Agent version:** 7.42.0
* **@hapi/hapi version:** 21.2.1
* **@hapi/boom version:** 10.0.0

**Other Details**

From my testing, this appears to have been introduced in v2.8.0.

**Comment by BrettHoutz** [comment]
Confirmed that it's fixed on my end. Thank you!
