### ISSUE TITLE
Non-existing methods wrapped by mongo plugin

### ISSUE THREAD

**Issue by matehuszarik** [DataDog/dd-trace-js#2790]
**Expected behaviour**
Tracing lib should not wrap non-existing methods.

**Actual behaviour**
Enabling mongo plugin throws the following exceptions:
```
Error: No original method maybePromise.
    at assertMethod (.../node_modules/@ghostmonitor/lib-logger/node_modules/dd-trace/packages/datadog-shimmer/src/shimmer.js:116:11)
    at wrapMethod (.../node_modules/@ghostmonitor/lib-logger/node_modules/dd-trace/packages/datadog-shimmer/src/shimmer.js:35:3)
    at Object.wrap (.../node_modules/@ghostmonitor/lib-logger/node_modules/dd-trace/packages/datadog-shimmer/src/shimmer.js:65:7)
    at .../node_modules/@ghostmonitor/lib-logger/node_modules/dd-trace/packages/datadog-instrumentations/src/mongodb-core.js:50:11
    at .../node_modules/@ghostmonitor/lib-logger/node_modules/dd-trace/packages/datadog-instrumentations/src/helpers/register.js:35:29
    at safeHook (.../node_modules/@ghostmonitor/lib-logger/node_modules/dd-trace/packages/datadog-instrumentations/src/helpers/hook.js:20:12)
    at Module.Hook.Module.require (.../node_modules/@ghostmonitor/lib-logger/node_modules/dd-trace/packages/dd-trace/src/ritm.js:134:33)
    at require (node:internal/modules/cjs/helpers:103:18)
```

```
Error: No original method query.
    at assertMethod (.../node_modules/@ghostmonitor/lib-logger/node_modules/dd-trace/packages/datadog-shimmer/src/shimmer.js:116:11)
    at wrapMethod (.../node_modules/@ghostmonitor/lib-logger/node_modules/dd-trace/packages/datadog-shimmer/src/shimmer.js:35:3)
    at Object.wrap (.../node_modules/@ghostmonitor/lib-logger/node_modules/dd-trace/packages/datadog-shimmer/src/shimmer.js:65:7)
    at .../node_modules/@ghostmonitor/lib-logger/node_modules/dd-trace/packages/datadog-instrumentations/src/mongodb-core.js:31:11
    at .../node_modules/@ghostmonitor/lib-logger/node_modules/dd-trace/packages/datadog-instrumentations/src/helpers/register.js:35:29
    at safeHook (.../node_modules/@ghostmonitor/lib-logger/node_modules/dd-trace/packages/datadog-instrumentations/src/helpers/hook.js:20:12)
    at Module.Hook.Module.require (.../node_modules/@ghostmonitor/lib-logger/node_modules/dd-trace/packages/dd-trace/src/ritm.js:134:33)
    at require (node:internal/modules/cjs/helpers:103:18)
```

**Steps to reproduce**
Install mongoose v6.9.1 and enable tracing. It relies on [mongodb v4.13.0](https://github.com/Automattic/mongoose/blob/master/package.json#L24).

```
tracer.use('mongodb-core', {
  service: 'mongo'
})
```

This version of mongodb has no [lib/utils.js](https://github.com/DataDog/dd-trace-js/blob/111036bdf51b1214b67ecd6b953ff57fd3c83a23/packages/datadog-instrumentations/src/mongodb-core.js#L49) file and neither `query` fn in [lib/cmap/connection.js](https://github.com/DataDog/dd-trace-js/blob/111036bdf51b1214b67ecd6b953ff57fd3c83a23/packages/datadog-instrumentations/src/mongodb-core.js#L31).

**Environment**

* **Operation system:** linux
* **Node.js version:** 16.18.1
* **Tracer version:** 3.9.10
* **Agent version:**
* **Relevant library versions:**

**Comment by kvin97** [comment]
I'm getting this issue in dev environment...but locally it's working fine. What are the possible solutions to avoid this issue ?

**Comment by kvin97** [comment]
Additionally, I didn't explicitly enable mongoose tracing. Can you please tell me how to disable it ?

**Comment by josecabral-afs** [comment]
I also have this issue. 
I have tried versions 3.12.1, 3.13.0 and 3.13.2.

I temporarily moved to `version 3.12.0` ,doesn't happen on this one.

**Comment by niji-DamienA** [comment]
same error

**Comment by matehuszarik** [comment]
Can you update us on when the fix is being released?
