### ISSUE TITLE
Jest instrumentation fails since 3.13.0 with "TypeError: Cannot read properties of null (reading 'toString')"

### ISSUE THREAD

**Issue by cgatt** [DataDog/dd-trace-js#2847]
**Expected behaviour**

The test should run successfully while instrumented with dd-trace, and output appropriate trace metrics.

**Actual behaviour**

The tests crash with the following stack trace:
```
<path_to_workdir>/node_modules/dd-trace/packages/datadog-plugin-jest/src/index.js:195
      suiteTags[TEST_MODULE_ID] = testSuiteSpan.context()._parentId.toString(10)
                                                                   ^

TypeError: Cannot read properties of null (reading 'toString')
    at JestPlugin.startTestSpan (<path_to_workdir>/node_modules/dd-trace/packages/datadog-plugin-jest/src/index.js:195:68)
    at <path_to_workdir>/node_modules/dd-trace/packages/datadog-plugin-jest/src/index.js:159:25
    at Subscription._handler (<path_to_workdir>/node_modules/dd-trace/packages/dd-trace/src/plugins/plugin.js:14:9)
    at Channel.publish (node:diagnostics_channel:56:9)
    at <path_to_workdir>/node_modules/dd-trace/packages/datadog-instrumentations/src/jest.js:115:23
    at exports.AsyncResource.runInAsyncScope (node:async_hooks:202:9)
    at DatadogEnvironment.handleTestEvent (<path_to_workdir>/node_modules/dd-trace/packages/datadog-instrumentations/src/jest.js:114:23)
    at dispatch (<path_to_workdir>/node_modules/jest-circus/build/state.js:66:11)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at _runTest (<path_to_workdir>/node_modules/jest-circus/build/run.js:146:3)
    at _runTestsForDescribeBlock (<path_to_workdir>/node_modules/jest-circus/build/run.js:86:9)
    at run (<path_to_workdir>/node_modules/jest-circus/build/run.js:26:3)
    at runAndTransformResultsToJestFormat (<path_to_workdir>/node_modules/jest-circus/build/legacy-code-todo-rewrite/jestAdapterInit.js:120:21)
    at jestAdapter (<path_to_workdir>/node_modules/jest-circus/build/legacy-code-todo-rewrite/jestAdapter.js:79:19)
    at runTestInternal (<path_to_workdir>/node_modules/jest-runner/build/runTest.js:367:16)
    at runTest (<path_to_workdir>/node_modules/jest-runner/build/runTest.js:444:34)
```

**Steps to reproduce**

Clone the repo at https://github.com/cgatt/dd-trace-exception-demo and run `npm test` on node version 16.16.0

**Environment**

* **Operation system:** Ubuntu 20.04.5 LTS
* **Node.js version:** v16.16.0
* **Tracer version:** >= 3.13.0
* **Agent version:** N/A
* **Relevant library versions:**

See https://github.com/cgatt/dd-trace-exception-demo for MVP reproduction.

**Comment by juan-fernandez** [comment]
hi @cgatt ! Thanks for the report and the reproducible case! I'll keep you posted with updates 😄

**Comment by juan-fernandez** [comment]
hey @cgatt I noticed the following issue: 

Using jest's `testEnvironment` to initialize CI Visibility, as you do here: https://github.com/cgatt/dd-trace-exception-demo/blob/main/.jestEnvironment.js#L1-L4 is _not_ the currently supported way of using CI Visibility: 

```javascript
require('dd-trace').init({
  service: 'dd-trace-test',
  flushInterval: 300000
})

module.exports = require('jest-environment-node')
```

The way to use the `jest` instrumentation is by passing `NODE_OPTIONS='-r dd-trace/ci/init'`, as shown in the docs: https://docs.datadoghq.com/continuous_integration/tests/javascript/?tab=onpremisesciproviderdatadogagent#instrument-your-tests

In any case, I'll push a fix for the error because even if the init is not done correctly we shouldn't throw an error.
