### ISSUE TITLE
Cannot read properties of undefined (reading 'span')

### ISSUE THREAD

**Issue by MatthewMaclean** [DataDog/dd-trace-js#2915]
**Expected behaviour**
Tracer shouldn't crash the server on failure. Is there a

**Actual behaviour**
The tracer crashed our server with the following error:
```
uncaughtException: Cannot read properties of undefined (reading 'span')
TypeError: Cannot read properties of undefined (reading 'span')
    at /opt/render/project/src/node_modules/dd-trace/packages/datadog-plugin-http2/src/client.js:75:38
    at Subscription._handler (/opt/render/project/src/node_modules/dd-trace/packages/dd-trace/src/plugins/plugin.js:14:9)
    at Channel.publish (node:diagnostics_channel:56:9)
    at /opt/render/project/src/node_modules/dd-trace/packages/datadog-instrumentations/src/http2/client.js:17:29
    at exports.AsyncResource.runInAsyncScope (node:async_hooks:202:9)
    at ClientHttp2Stream.emit (/opt/render/project/src/node_modules/dd-trace/packages/datadog-instrumentations/src/http2/client.js:14:23)
    at emit (node:internal/http2/core:328:3)
    at processTicksAndRejections (node:internal/process/task_queues:86:22)
```

I'm not familiar enough with the codebase, but it's weird that https://github.com/DataDog/dd-trace-js/blob/v3.14.1/packages/dd-trace/src/plugins/plugin.js#L13 would call into a function that expects the store to exist: https://github.com/DataDog/dd-trace-js/blob/v3.14.1/packages/datadog-plugin-http2/src/client.js#L74

**Steps to reproduce**
Happened randomly on server startup, haven't seen it reproduce. There were no recent library upgrades.

**Environment**

* **Operation system:**
* **Node.js version:** 16.16.0
* **Tracer version:** 3.14.1
* **Agent version:** v7
* **Relevant library versions:**

**Comment by ZebGirouard** [comment]
+1, I'm seeing this error this week on some of our Jest CI runs

**Comment by gratus-acuitymd** [comment]
+1, encountered this as well - was intermittent and went undetected during development.

**Comment by MatthewMaclean** [comment]
My solution here is:
`tracer.use('http2', { enabled: false });`

It's not ideal, but I prefer it over my application crashing.
