### ISSUE TITLE
Possibility to pass custom `lookup` function to internal `dd-trace` udp socket

### ISSUE THREAD

**Issue by svsool** [DataDog/dd-trace-js#2958]
Hi,

Context: NodeJS v18.15.0, ESM modules and dd-trace 3.15.0.

We have quite a bunch of `dns.lookup` calls originating from `dd-trace` and showing up in APM tracing under `dns.lookup` span, perhaps happening somewhere [here](https://github.com/DataDog/dd-trace-js/blob/deda0c85c32418fae880aab01897e1dd87ebbb86/packages/dd-trace/src/dogstatsd.js#L91).

A similar issue https://github.com/DataDog/dd-trace-js/issues/1044 and volumes https://github.com/DataDog/dd-trace-js/issues/1044#issuecomment-673135596.

This is the full trace:

```
Trace at dns.lookup (startWebApi.js:4:19)
at UDP.lookup4 (node:internal/dgram:24:10)
at Socket.send (node:dgram:670:18)
at /app/node_modules/dd-trace/packages/dd-trace/src/dogstatsd.js:91:14
at Array.forEach (<anonymous>)
at Client._sendUdpFromQueue (/app/node_modules/dd-trace/packages/dd-trace/src/dogstatsd.js:89:11)
at Client._sendUdp (/app/node_modules/dd-trace/packages/dd-trace/src/dogstatsd.js:77:12)
at Client.flush (/app/node_modules/dd-trace/packages/dd-trace/src/dogstatsd.js:52:12)
at Timeout._onTimeout (/app/node_modules/dd-trace/packages/dd-trace/src/metrics.js:78:16)
at listOnTimeout (node:internal/timers:569:17)
```

Would it be possible to pass custom `lookup` to `dgram.createSocket()` (it seems it doesn't get propagated up to `_sendUdpFromQueue` socket although this option is present and can be passed via `dd-trace` init)?

https://github.com/DataDog/dd-trace-js/blob/36524c857c5b5a785d6b37c843499a5e3d7d262d/packages/dd-trace/src/dogstatsd.js#L128-L136

[This article](https://hermanradtke.com/send-udp-messages-in-nodejs-without-dns-lookup/) describes the problem fairly well.

That's how our `dd-trace` gets initialized for reference:

```typescript
ddTrace.init({
    logInjection: true,
    plugins: true,
    lookup: (hostname, options, callback) => {
	    if (hostname === statsDHost || hostname === ddAgentHost) {
	      process.nextTick(callback, null, hostname, ipV4Family);
	    } else {
          dns.lookup(hostname, options, callback);
       }
  	},
  })
```

See for example `hot-shots`: https://github.com/brightcove/hot-shots/blob/b4422446831b47873637b43ff6d111b1cef1b5d5/lib/transport.js#L47 that accepts `dgram.SocketOptions` directly with possibility to pass also `lookup` vs just `type` https://github.com/brightcove/hot-shots/blob/b4422446831b47873637b43ff6d111b1cef1b5d5/types.d.ts#LL35C36-L35C36

It seems that this UDP/dgram behaviour originates from the implementation decision on the NodeJS side https://github.com/nodejs/node/issues/39468, nevertheless it would be good to have less "no-op" traces in APM by providing a custom `lookup` function that doesn't hit `dns.lookup` instrumentation at all.

Thanks!

**Comment by schmod** [comment]
If you look at the Node issue that I opened, there seems to be some speculation that the fact that `dns.lookup` is being called on an IP address isn't actually resulting in any real UDP I/O happening.  

We only think it's happening because we've instrumented `dns.lookup`, and aren't smart enough to know that the call is technically a no-op.

**Comment by svsool** [comment]
This FR is about possibility of reducing udp i/o from `dd-trace` itself and `dns.lookup` traces not resulting in `getaddrinfo` system call and i/o inside `dns.lookup` (there is [an early return](https://github.com/nodejs/node/blob/main/lib/dns.js#L204-L213) avoiding expensive calls when ip is passed). The following `dns.lookup` traces drop observed after providing mentioned custom `lookup` function to `hot-shots`, but it seems there is still a portion of `dns.lookup` traces originating from `dd-trace` itself because it doesn't seem to engage `lookup` function passed via `ddTrace.init` for its udp socket.

<img src="https://user-images.githubusercontent.com/1452141/229273424-23bf51a0-a341-48e1-b6a2-614e80323240.png" width="400" />

These "no-op" traces clutter APM & Live Tracing, also show up as a primary operation in APM where `<framework>.request` expected to be one instead. At certain volumes there is not much value in seeing them, there seems to be an extra `dns.lookup` trace for every udp `socket.send()` which might be many if telemetry and dd integrations are used extensively.

**Comment by Raynos** [comment]
I would love to get this fixed too.

**Comment by JaydenMaalouf** [comment]
Also looking for a solution for this
We are seeing around 11 DNS lookups every 10 seconds on our hosts with dd-tracer-js

**Comment by af-andy** [comment]
I would also love to see a solution for this, I'm seeing DNS lookup traces for the 127.0.0.1 when setting DD_AGENT_HOST to 127.0.0.1

**Comment by BridgeAR** [comment]
This is an old issue where we luckily did not receive any new comments for more than two years. Thus, I guess we fixed that in the meanwhile and I'll close this. If that is not the case, I kindly ask to open a new issue or even better to reach out to our official support https://www.datadoghq.com/support for it. The official support is always able to escalate issues properly while it is not possible to provide regular support through github.
