### ISSUE TITLE
Readme does not contain correct information to contribute / run tests

### ISSUE THREAD

**Issue by comp615** [DataDog/dd-trace-js#3084]
**Expected behaviour**
According to the readme, after running `yarn`. One should be able to test an individual plugin by running `PLUGINS="express|bluebird" yarn test:plugins` 
https://github.com/DataDog/dd-trace-js#unit-tests

**Actual behaviour**
Running the command yields an error from what appears to be missing sub-dependencies:
```
➜  dd-trace-js git:(master) PLUGINS="pg" yarn test:plugins
yarn run v1.22.19
$ mocha --colors --exit -r "packages/dd-trace/test/setup/mocha.js" "packages/datadog-instrumentations/test/@($(echo $PLUGINS)).spec.js" "packages/datadog-plugin-@($(echo $PLUGINS))/test/**/*.spec.js"
Warning: Cannot find any files matching pattern "packages/datadog-instrumentations/test/@(pg).spec.js"

Error: could not find pg/package.json
    at requirePackageJson (/Users/charlie.croom/workspace/dd-trace-js/packages/dd-trace/src/require-package-json.js:30:9)
    at Object.version (/Users/charlie.croom/workspace/dd-trace-js/versions/pg@>=8.0.3/index.js:8:23)
    at /Users/charlie.croom/workspace/dd-trace-js/packages/dd-trace/test/setup/mocha.js:113:82
    at Array.forEach (<anonymous>)
    at /Users/charlie.croom/workspace/dd-trace-js/packages/dd-trace/test/setup/mocha.js:111:12
    at Array.forEach (<anonymous>)
    at /Users/charlie.croom/workspace/dd-trace-js/packages/dd-trace/test/setup/mocha.js:108:8
    at Array.forEach (<anonymous>)
    at withVersions (/Users/charlie.croom/workspace/dd-trace-js/packages/dd-trace/test/setup/mocha.js:103:11)
    at Suite.<anonymous> (/Users/charlie.croom/workspace/dd-trace-js/packages/datadog-plugin-pg/test/index.spec.js:23:5)
    at Object.create (/Users/charlie.croom/workspace/dd-trace-js/node_modules/mocha/lib/interfaces/common.js:148:19)
    at context.describe.context.context (/Users/charlie.croom/workspace/dd-trace-js/node_modules/mocha/lib/interfaces/bdd.js:42:27)
    at Suite.<anonymous> (/Users/charlie.croom/workspace/dd-trace-js/packages/datadog-plugin-pg/test/index.spec.js:22:3)
    at Object.create (/Users/charlie.croom/workspace/dd-trace-js/node_modules/mocha/lib/interfaces/common.js:148:19)
    at context.describe.context.context (/Users/charlie.croom/workspace/dd-trace-js/node_modules/mocha/lib/interfaces/bdd.js:42:27)
    at Object.<anonymous> (/Users/charlie.croom/workspace/dd-trace-js/packages/datadog-plugin-pg/test/index.spec.js:17:1)
    at Module._compile (node:internal/modules/cjs/loader:1126:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1180:10)
    at Module.load (node:internal/modules/cjs/loader:1004:32)
    at Function.Module._load (node:internal/modules/cjs/loader:839:12)
    at Module.require (node:internal/modules/cjs/loader:1028:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.exports.requireOrImport (/Users/charlie.croom/workspace/dd-trace-js/node_modules/mocha/lib/esm-utils.js:42:12)
    at Object.exports.loadFilesAsync (/Users/charlie.croom/workspace/dd-trace-js/node_modules/mocha/lib/esm-utils.js:55:34)
    at Mocha.loadFilesAsync (/Users/charlie.croom/workspace/dd-trace-js/node_modules/mocha/lib/mocha.js:473:19)
    at singleRun (/Users/charlie.croom/workspace/dd-trace-js/node_modules/mocha/lib/cli/run-helpers.js:125:15)
    at exports.runMocha (/Users/charlie.croom/workspace/dd-trace-js/node_modules/mocha/lib/cli/run-helpers.js:190:10)
    at Object.exports.handler (/Users/charlie.croom/workspace/dd-trace-js/node_modules/mocha/lib/cli/run.js:362:11)
    at /Users/charlie.croom/workspace/dd-trace-js/node_modules/yargs/build/index.cjs:443:71
error Command failed with exit code 1.
```

Running the CI command first causes this to work but causes an exhaustive dependency installation which takes many minutes. I'm not sure this is the intent, either:
- Docs should be updated to note this requirement and that `yarn install` is not enough
- Setup code should be updated to magically install the correct subset of deps as needed (preferred)

**Steps to reproduce**
Checkout clean environment, run commands above

**Environment**

* **Operation system:** MacOS 12
* **Node.js version:** 16
* **Tracer version:** master
* **Agent version:** N/A
* **Relevant library versions:** N/A

**Comment by rorybakerfmr** [comment]
Hello, my firm is holding an internal workshop to make our associates aware of our process for contributing to open source projects. We will hold our workshop on May 16th and hope to create our public pull requests shortly after that. In the interest of sourcing "good first issue" contribution opportunities for our participants, may we earmark this issue, as well as #3063 ? 

If you feel these issues are more complex than what is appropriate for a first time contributor, or have any suggestions for other items that would be good first issues, please let me know!

**Comment by BridgeAR** [comment]
This is fixed in newer versions.
