### ISSUE TITLE
TypeError when running Playwright test (this.rootDir undefined?)

### ISSUE THREAD

**Issue by dst87** [DataDog/dd-trace-js#3176]
**Expected behaviour**
Tracing should work when running a test with Playwright

**Actual behaviour**
When starting, I get a TypeError:

```
Running 3 tests using 3 workers

node:internal/errors:465
		ErrorCaptureStackTrace(err);
		^

TypeError: The "from" argument must be of type string. Received undefined
		at new NodeError (node:internal/errors:372:5)
		at validateString (node:internal/validators:120:11)
		at Object.relative (node:path:1191:5)
		at getTestSuitePath (/Users/duncan/e2e/node_modules/dd-trace/packages/dd-trace/src/plugins/util/test.js:215:36)
		at /Users/duncan/e2e/node_modules/dd-trace/packages/datadog-plugin-playwright/src/index.js:38:25
		at Subscription._handler (/Users/duncan/e2e/node_modules/dd-trace/packages/dd-trace/src/plugins/plugin.js:14:9)
		at Channel.publish (node:diagnostics_channel:56:9)
		at /Users/duncan/e2e/node_modules/dd-trace/packages/datadog-instrumentations/src/playwright.js:95:24
		at exports.AsyncResource.runInAsyncScope (node:async_hooks:202:9)
		at testBeginHandler (/Users/duncan/e2e/node_modules/dd-trace/packages/datadog-instrumentations/src/playwright.js:94:28)
		at WorkerHost.<anonymous> (/Users/duncan/e2e/node_modules/dd-trace/packages/datadog-instrumentations/src/playwright.js:192:7)
		at WorkerHost.emit (node:events:539:35)
		at ChildProcess.<anonymous> (/Users/duncan/e2e/node_modules/@playwright/test/lib/processHost.js:84:16)
		at ChildProcess.emit (node:events:527:28)
		at emit (node:internal/child_process:938:14) {
	code: 'ERR_INVALID_ARG_TYPE'
}

```

**Steps to reproduce**
This repros every time I run the tests running locally:

`NODE_OPTIONS="-r dd-trace/ci/init" npx playwright test`

From a colleague who found time to attempt to debug this:

> From my debugging it looks like the dd-trace handler for ci:playwright:session:start isn't called before the handler for ci:playwright:test-suite:start  but this.rootDir is only being set in ci:playwright:session:start which is why it is coming back with an error saying it is undefined.

**Environment**

* **Operation system:** macOS 13.4 (22F66)
* **Node.js version:**  v16.16.0.
* **Tracer version:**  "^3.21.0"
* **Agent version:**  N/A - running agentless

**Comment by juan-fernandez** [comment]
hey @dst87 , thanks for the report. 

> From my debugging it looks like the dd-trace handler for ci:playwright:session:start isn't called before the handler for ci:playwright:test-suite:start but this.rootDir is only being set in ci:playwright:session:start which is why it is coming back with an error saying it is undefined.

this is likely the issue we're seeing here, so good debugging! 😄 . To solve this I'd like to: 

1. Understand why `ci:playwright:session:start` is not being emitted. For this it'd be very helpful to have the playwright config file, removing anything you think it's sensitive. Also, what version of `playwright` are you using?
2. I'll make sure there's no crash if `ci:playwright:test-suite:start` is emitted before the session starts. That should be an easy fix :-)

**Comment by juan-fernandez** [comment]
thanks! I don't see anything that could cause issues, and I can't reproduce in 1.30.0. 

Next step is to look at debug logs: could you share what you see when you run
```
DD_TRACE_DEBUG=1 DD_TRACE_LOG_LEVEL=error NODE_OPTIONS="-r dd-trace/ci/init" npx playwright test
```

feel free to remove stack traces' lines that do not contain `dd-trace`

**Comment by fedorareis** [comment]
Here is what I got from running that command.

```
Error: ENOENT: no such file or directory, open 'repo/e2e/git.properties'
    at Object.openSync (node:fs:590:3)
    at Object.readFileSync (node:fs:458:35)
    at maybeFile (repo/e2e/node_modules/dd-trace/packages/dd-trace/src/config.js:24:15)
    at new Config (repo/e2e/node_modules/dd-trace/packages/dd-trace/src/config.js:548:37)
    at Tracer.init (repo/e2e/node_modules/dd-trace/packages/dd-trace/src/proxy.js:27:22)
    at Object.<anonymous> (repo/e2e/node_modules/dd-trace/ci/init.js:45:10)
    at Module._compile (node:internal/modules/cjs/loader:1267:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1321:10)
    at Module.load (node:internal/modules/cjs/loader:1125:32)
    at Module._load (node:internal/modules/cjs/loader:965:12) {
  errno: -2,
  syscall: 'open',
  code: 'ENOENT',
  path: 'repo/e2e/git.properties'
}
Error: ENOENT: no such file or directory, open 'repo/e2e/git.properties'
    at Object.openSync (node:fs:590:3)
    at Object.readFileSync (node:fs:458:35)
    at maybeFile (repo/e2e/node_modules/dd-trace/packages/dd-trace/src/config.js:24:15)
    at new Config (repo/e2e/node_modules/dd-trace/packages/dd-trace/src/config.js:548:37)
    at Tracer.init (repo/e2e/node_modules/dd-trace/packages/dd-trace/src/proxy.js:27:22)
    at Object.<anonymous> (repo/e2e/node_modules/dd-trace/ci/init.js:45:10)
    at Module._compile (node:internal/modules/cjs/loader:1267:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1321:10)
    at Module.load (node:internal/modules/cjs/loader:1125:32)
    at Module._load (node:internal/modules/cjs/loader:965:12) {
  errno: -2,
  syscall: 'open',
  code: 'ENOENT',
  path: 'repo/e2e/git.properties'
}

Running 111 tests using 5 workers

     1 [chromium] › account_changes.spec.ts:121:5 › Change Account Type
node:internal/errors:490
    ErrorCaptureStackTrace(err);
    ^

TypeError: The "from" argument must be of type string. Received undefined
    at new NodeError (node:internal/errors:399:5)
    at validateString (node:internal/validators:163:11)
    at Object.relative (node:path:1195:5)
    at getTestSuitePath (repo/e2e/node_modules/dd-trace/packages/dd-trace/src/plugins/util/test.js:215:36)
    at repo/e2e/node_modules/dd-trace/packages/datadog-plugin-playwright/src/index.js:38:25
    at Subscription._handler (repo/e2e/node_modules/dd-trace/packages/dd-trace/src/plugins/plugin.js:14:9)
    at Channel.publish (node:diagnostics_channel:142:9)
    at repo/e2e/node_modules/dd-trace/packages/datadog-instrumentations/src/playwright.js:95:24
    at AsyncResource.runInAsyncScope (node:async_hooks:206:9)
    at testBeginHandler (repo/e2e/node_modules/dd-trace/packages/datadog-instrumentations/src/playwright.js:94:28)
    at WorkerHost.<anonymous> (repo/e2e/node_modules/dd-trace/packages/datadog-instrumentations/src/playwright.js:192:7)
    at WorkerHost.emit (node:events:523:35)
    at ChildProcess.<anonymous> (repo/e2e/node_modules/@playwright/test/lib/processHost.js:84:16)
    at ChildProcess.emit (node:events:511:28)
    at emit (node:internal/child_process:944:14) {
  code: 'ERR_INVALID_ARG_TYPE'
}

Node.js v20.0.0
```

just a couple notes on this in case it is important. I adjusted the paths in the trace to use `repo` instead of `/Users/<username>/...`. Also `repo` is the root of a monorepo, so the test suite is in an `e2e` folder with it's own `package.json`

**Comment by juan-fernandez** [comment]
thanks for the info! I think I found the issue: there's a silly bug where specifically 1.30.0 is mistakenly ignored as a supported version for playwright, but only for session level info. See https://github.com/DataDog/dd-trace-js/pull/3180 if you're interested. I thought I had tested 1.30.0 manually but there must've been some installation issue I missed. 

I'd really appreciate it if you could this specific branch `juan-fernandez/fix-playwright-support` via 
```
yarn add --dev https://github.com/DataDog/dd-trace-js/tarball/juan-fernandez/fix-playwright-support
```
(or via whatever package you use 😄).

The contents of the branch are https://github.com/DataDog/dd-trace-js/pull/3180/files if you want to check

**Comment by fedorareis** [comment]
I just gave it a try and it looks like that fixed the issue and everything is running normally. Thank you for the quick support on this
