### ISSUE TITLE
Cannot destructure property '_ddTestSessionId' of 'testEnvironmentOptions' as it is undefined

### ISSUE THREAD

**Issue by cameronscottseequent** [DataDog/dd-trace-js#3197]
Cannot for the life of me figure out what is going on. Trying to move our repo over from CRA to Vite. however this part of the code base has not been migrated as it never used CRA, we are in a rush mono repo using pnpm. all of the Jest & friends package version numbers are the same so thats not an issue. 

I have tried moving our jest config from jest.config.js into the package.json to no avail 

occurs when we are running tests in the pipeline. but works successfully locally

```
FAIL state-domains/domain/authentication/shim/central/oauth2.test.ts
  ● Test suite failed to run
    TypeError: The "from" argument must be of type string. Received undefined
      at getTestSuitePath (../../common/temp/node_modules/.pnpm/dd-trace@4.0.0/node_modules/dd-trace/packages/dd-trace/src/plugins/util/test.js:215:36)
      at ../../common/temp/node_modules/.pnpm/dd-trace@4.0.0/node_modules/dd-trace/packages/datadog-instrumentations/src/jest.js:327:28
          at Array.map (<anonymous>)
      at ../../common/temp/node_modules/.pnpm/dd-trace@4.0.0/node_modules/dd-trace/packages/datadog-instrumentations/src/jest.js:327:12
/home/runner/work/app-name/app-name/common/temp/node_modules/.pnpm/dd-trace@4.0.0/node_modules/dd-trace/packages/datadog-plugin-jest/src/index.js:50
            const { _ddTestSessionId: testSessionId, _ddTestCommand: testCommand, _ddTestModuleId: testModuleId } = testEnvironmentOptions;
                                      ^
TypeError: Cannot destructure property '_ddTestSessionId' of 'testEnvironmentOptions' as it is undefined.
```

**Expected behaviour**
Tests should run as normal

**Steps to reproduce**

**Environment**

* **Operation system:**
Ubuntu
 22.04.2
  LTS
* **Node.js version:**
* https://github.com/actions/runner-images/blob/ubuntu22/20230507.1/images/linux/Ubuntu2204-Readme.md
* **Tracer version:**
* **Agent version:**
* https://github.com/actions/runner-images/blob/ubuntu22/20230507.1/images/linux/Ubuntu2204-Readme.md
* **Relevant library versions:**

    },
    "devDependencies": {
        "@svgr/webpack": "^6.5.1",
        "@testing-library/jest-dom": "^5.16.5",
        "@testing-library/react": "^14.0.0",
        "@testing-library/user-event": "^14.4.3",
        "@types/c3": "0.7.4",
        "@types/classnames": "^2.2.9",
        "@types/d3": "7.0.0",
        "@types/d3-color": "1.4.1",
        "@types/file-saver": "^2.0.3",
        "@types/filesize": "^5.0.0",
        "@types/history": "^4.7.11",
        "@types/jest": "^29.0.3",
        "@types/jest-when": "^3.5.0",
        "@types/js-cookie": "^2.2.7",
        "@types/leaflet": "1.7.5",
        "@types/lodash-es": "^4.17.5",
        "@types/node": "^16.11.27",
        "@types/react": "^18.0.18",
        "@types/react-color": "^3.0.6",
        "@types/react-csv": "~1.1.2",
        "@types/react-dom": "^18.0.6",
        "@types/react-intl": "^3.0.0",
        "@types/react-lines-ellipsis": "^0.15.0",
        "@types/react-mentions": "^3.3.1",
        "@types/react-redux": "^7.1.18",
        "@types/react-router-dom": "^5.1.9",
        "@types/react-test-renderer": "^18.0.0",
        "@types/react-window": "^1.8.5",
        "@types/store": "^2.0.2",
        "@types/testing-library__jest-dom": "5.14.5",
        "@types/uuid": "^8.3.4",
        "cross-spawn": "^7.0.3",
        "date-fns-tz": "^1.3.7",
        "dd-trace": "~4.0.0",
        "del-cli": "^4.0.1",
        "eslint": "^8.41.0",
        "eslint-import-resolver-typescript": "^2.7.1",
        "jest": "^29.0.3",
        "jest-environment-jsdom": "^29.0.3",
        "jest-fetch-mock": "^3.0.3",
        "jest-launchdarkly-mock": "^1.0.3",
        "jest-slow-test-reporter": "1.0.0",
        "jest-when": "^3.5.1",
        "lint-staged": "^11.1.2",
        "moment": "^2.29.4",
        "nock": "^13.1.3",
        "react-test-renderer": "^17.0.2",
        "rimraf": "^3.0.2",
        "ts-jest": "^29.0.1",
        "tsc-watch": "^6.0.0",
        "typescript": "^4.8.4",
        "xmlhttprequest": "1.8.0",
        "yargs": "^17.2.1",
        "tsc-alias": "1.7.0",
        "copyfiles": "^2.4.1",
        "msw": "^1.2.1",
        "whatwg-fetch": "^3.6.2"
    },
    
        "jest":{
        "testEnvironment": "jsdom",
        "transformIgnorePatterns": [
          "<rootDir>/node_modules/(?!.*(d3(-.+)?|internmap|delaunator|robust-predicates|lodash-es|react-leaflet)/)"
        ],
        "resolver": "<rootDir>/testUtils/resolver.ts",
        "reporters": [
          "default",
          "github-actions",
          [
            "jest-slow-test-reporter",
            {
              "numTests": 8,
              "warnOnSlowerThan": 300,
              "color": true
            }
          ]
        ],
        "testEnvironmentOptions": {
          "url": "https://test.seequent.com"
        }
      }

**Comment by cameronscottseequent** [comment]
Turns out i had a corrupt pnpm lock file. a team member reverted to the last successful commit. merged master. deleted lock file. regenerated lock file and all was well. time wasted!
