### ISSUE TITLE
dbmPropagationMode error on v3.24.0

### ISSUE THREAD

**Issue by rifflock** [DataDog/dd-trace-js#3296]
Hello!

We use datadog in our node application (k8s+postgres) and our last deploy bumped us up to v3.24.0. As soon as this code went live we started seeing a ton of errors in the logs
```javascript
errorMessage[Cannot read properties of null (reading 'dbmPropagationMode')](javascript:void(0);)errorStackTypeError: Cannot read properties of null (reading 'dbmPropagationMode')
    at PGPlugin.injectDbmQuery (/usr/src/app/node_modules/dd-trace/packages/dd-trace/src/plugins/database.js:41:71)
    at PGPlugin.start (/usr/src/app/node_modules/dd-trace/packages/datadog-plugin-pg/src/index.js:30:23)
    at /usr/src/app/node_modules/dd-trace/packages/dd-trace/src/plugins/tracing.js:17:12
    at Subscription._handler (/usr/src/app/node_modules/dd-trace/packages/dd-trace/src/plugins/plugin.js:14:9)
    at Channel.publish (node:diagnostics_channel:56:9)
    at /usr/src/app/node_modules/dd-trace/packages/datadog-instrumentations/src/pg.js:40:15
    at exports.AsyncResource.runInAsyncScope (node:async_hooks:202:9)
    at Client.query (/usr/src/app/node_modules/dd-trace/packages/datadog-instrumentations/src/pg.js:39:26)
    at query (/usr/src/app/node_modules/sequelize/lib/dialects/postgres/query.js:47:227)
    at new Promise (<anonymous>)
    at Query.run (/usr/src/app/node_modules/sequelize/lib/dialects/postgres/query.js:47:183)
    at /usr/src/app/node_modules/sequelize/lib/sequelize.js:315:28
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

**Expected behaviour**
No error should be occurring jumping from v3.23.0 to 3.24.0

**Actual behaviour**
An error is occurring

**Steps to reproduce**
I don't have a sample app to provide, but running our code (express+TS+sequelize) immediately starts throwing this error. I downgraded to v3.23 and the issue went away.

**Environment**

* **Operation system:** Debian GNU/Linux 10 (buster)
* **Node.js version:** 16.15.1
* **Yarn version:** 1.22.19
* **Tracer version:** 3.24.0

**Comment by tlhunter** [comment]
This must be related to #3235.

Apparently `this._tracerConfig` in the Pg plugin is null. `PluginManager` must have been instantiated, which initializes the config to null, and then `PluginManager#loadPlugin` was called (reading the config) before `PluginManager#configure` was called (which sets the config).

Can you share your tracer configuration? Like are you using any `tracer.use` calls? Also, is the tracer initialization the first thing that happens in the app?

**Comment by Marouann** [comment]
Same problem, I've downgraded to v3.23.0

**Comment by sprak3000** [comment]
@tlhunter 

> Can you share your tracer configuration? Like are you using any `tracer.use` calls? Also, is the tracer initialization the first thing that happens in the app?

Having the same issue. Here is our init code:

```
export const initTracer = async () => {
  if (process.env['ECS_CONTAINER_METADATA_URI_V4']) {
    const taskMetadata = await axios.get(
      `${process.env['ECS_CONTAINER_METADATA_URI_V4']}/task`,
    );

    tracer.init({
      tags: {
        task_arn: taskMetadata.data['TaskARN'],
      },
    });
    tracer.use('http', {
      blocklist: [new RegExp('.*/health')],
    });
    tracer.use('amqplib', {
      service: '---redacted---',
    });
  }
};
```

If it helps, this function gets called just before the `bootstrap();` call in our NestJS 10.X application. We are also connecting to a Postgres DB in AWS RDS.

**Comment by tlhunter** [comment]
This fix should now be available in these versions of the tracer: v2.39.0, v3.26.0, and v4.5.0.

**Comment by rifflock** [comment]
Amazing, thanks for the quick turnaround

**Comment by GeoffreyPlitt** [comment]
Still happening for me in 4.7.0

**Comment by tlhunter** [comment]
@GeoffreyPlitt can you provide the stacktrace?

**Comment by GeoffreyPlitt** [comment]
Uncaught TypeError: Cannot read properties of null (reading 'dogstatsd')
      at Object.module.exports.init (node_modules/.pnpm/dd-trace@4.7.0/node_modules/dd-trace/packages/datadog-plugin-openai/src/services.js:13:20)
      at new OpenApiPlugin (node_modules/.pnpm/dd-trace@4.7.0/node_modules/dd-trace/packages/datadog-plugin-openai/src/index.js:22:42)
      at PluginManager.loadPlugin (node_modules/.pnpm/dd-trace@4.7.0/node_modules/dd-trace/packages/dd-trace/src/plugin_manager.js:76:35)
      at PluginManager._loadedSubscriber (node_modules/.pnpm/dd-trace@4.7.0/node_modules/dd-trace/packages/dd-trace/src/plugin_manager.js:65:12)
      at Channel.publish (node:diagnostics_channel:56:9)
      at <SNIPPED>/node_modules/.pnpm/dd-trace@4.7.0/node_modules/dd-trace/packages/datadog-instrumentations/src/helpers/register.js:47:25
      at safeHook (node_modules/.pnpm/dd-trace@4.7.0/node_modules/dd-trace/packages/datadog-instrumentations/src/helpers/hook.js:28:12)
      at Module.Hook.Module.require (node_modules/.pnpm/dd-trace@4.7.0/node_modules/dd-trace/packages/dd-trace/src/ritm.js:134:33)
      at require (node:internal/modules/cjs/helpers:110:18)
      at Object.<anonymous> (node_modules/.pnpm/openai@3.2.1_debug@4.3.4/node_modules/openai/dist/index.js:26:14)
      at Module._compile (node:internal/modules/cjs/loader:1256:14)
      at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
      at Object.newLoader [as .js] (node_modules/.pnpm/pirates@4.0.5/node_modules/pirates/lib/index.js:141:7)
      at Module.load (node:internal/modules/cjs/loader:1119:32)
      at Module._load (node:internal/modules/cjs/loader:960:12)
      at Function.updatedLoad [as _load] (app/lib/ts-require-patch.ts:59:20)
      at Module.require (node:internal/modules/cjs/loader:1143:19)
      at Module.Hook.Module.require (node_modules/.pnpm/dd-trace@4.7.0/node_modules/dd-trace/packages/dd-trace/src/ritm.js:85:33)
      at require (node:internal/modules/cjs/helpers:110:18)
      at Object.<anonymous> (app/controllers/generative.ts:16:17)
      at Module._compile (node:internal/modules/cjs/loader:1256:14)
      at Module._compile (node_modules/.pnpm/pirates@4.0.5/node_modules/pirates/lib/index.js:136:24)
      at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
      at Object.newLoader [as .ts] (node_modules/.pnpm/pirates@4.0.5/node_modules/pirates/lib/index.js:141:7)
      at Module.load (node:internal/modules/cjs/loader:1119:32)
      at Module._load (node:internal/modules/cjs/loader:960:12)
      at Function.updatedLoad [as _load] (app/lib/ts-require-patch.ts:59:20)
      at Module.require (node:internal/modules/cjs/loader:1143:19)
      at Module.Hook.Module.require (node_modules/.pnpm/dd-trace@4.7.0/node_modules/dd-trace/packages/dd-trace/src/ritm.js:85:33)

**Comment by tlhunter** [comment]
Ah, that was due to the other github issue, unrelated to this one.
