### ISSUE TITLE
Add support for ES modules

### ISSUE THREAD

**Issue by rochdev** [DataDog/dd-trace-js#349]
Right now we rely on `require` to patch modules automatically. We should also support [ES modules](https://nodejs.org/api/esm.html) as well as the [esm](https://www.npmjs.com/package/esm) module.

**Comment by luax** [comment]
Any news on this?  🙂 

We're experiencing some issues instrumenting `redis` using a node app with only native ES modules (`package.json` has type "module") 

`app.js`:
```js
import 'dotenv/config.js';
import './ddTracer.js'; // This line must come before importing any instrumented module.
import redis from 'redis';
const app = express()
// redis stuff
....
```

`ddTracer.js`:
```js
import trace from 'dd-trace';
const tracer = trace.init({ plugins: true });
export default tracer;
```

Manually enabling redis does not work either:
```
tracer.use('redis', { service: 'redis' });
```

The plugins `http-client`, `dns`, `tcp` and `express` seemingly works.

Thanks 🙏

**Comment by rochdev** [comment]
This is still on our roadmap but we're not actively working on it. What is your use case for using ES modules?

**Comment by luax** [comment]
Thank you @rochdev. I would not say that there is one particular use case but the app is only running modern native Node.js and JS functionality and not any transpiled code.

**Comment by provstevi** [comment]
We're having a similar issue when using koa and redis. 

It seems I can either `require` and `init` dd-trace in the main server.js file and get redis tracing but lose endpoints being tagged automatically, 
OR 
I can `import './datadog';` a file with `import datadogTrace from 'dd-trace';` and get automatic endpoint tagged as expected, but redis will be disabled with the trace error `TypeError: Cannot read property 'prototype' of undefined
    at Instrumenter.patch (/app/app/node_modules/dd-trace/packages/datadog-plugin-redis/src/index.js:57:35)`
    
For now we're erring on the side of actually getting redis tracing, but I'd really like to not have to manually tag my endpoints, too.

**Comment by rochdev** [comment]
@provstevi Can you clarify what the issue is when _not_ using `import`? When using `require` everything should work out of the box. What is not tagged automatically? (assuming here that tagged means traced)

**Comment by provstevi** [comment]
OK, to restate, for our services that use koa, we also use esm. 

If I have the following, I get everything **_except_** redis out of the box, including desired resource names from the route, and other expected plugins, e.g. servicename-http-client, servicename-tcp, servicename-dns.
```
// startServer.js
require = require('esm')(module);
module.exports = require('./server.js');

// server.js
import './datadog';

// datadog.js
const datadogTrace = require('dd-trace');
const tracer = datadogTrace.init();
const opentracing = require('opentracing');
opentracing.initGlobalTracer(tracer);
```

Debug reports the following error:
```
TypeError: Cannot read property 'prototype' of undefined
    at Instrumenter.patch (/app/app/node_modules/dd-trace/packages/datadog-plugin-redis/src/index.js:57:35)
    at Instrumenter.patch (/app/app/node_modules/dd-trace/packages/dd-trace/src/instrumenter.js:219:36)
    at /app/app/node_modules/dd-trace/packages/dd-trace/src/platform/node/loader.js:101:52
    at Array.forEach (<anonymous>)
    at /app/app/node_modules/dd-trace/packages/dd-trace/src/platform/node/loader.js:97:14
    at Map.forEach (<anonymous>)
    at Loader._hookModule (/app/app/node_modules/dd-trace/packages/dd-trace/src/platform/node/loader.js:92:8)
    at Object.Module.require (/app/app/node_modules/require-in-the-middle/index.js:83:30)
    at Object.t (/app/app/node_modules/esm/esm.js:1:279775)
    at n (/app/app/node_modules/esm/esm.js:1:279589)
    at Object.<anonymous> (/app/app/node_modules/redis/lib/debug.js:3:13)
    at Object.<anonymous> (/app/app/node_modules/esm/esm.js:1:251206)
    at Object.<anonymous> (/app/app/node_modules/esm/esm.js:1:287446)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Object.Ph (/app/app/node_modules/esm/esm.js:1:286187)
    at p (/app/app/node_modules/esm/esm.js:1:287490)
TypeError: Cannot read property 'prototype' of undefined
    at Instrumenter.unpatch (/app/app/node_modules/dd-trace/packages/datadog-plugin-redis/src/index.js:60:37)
    at /app/app/node_modules/dd-trace/packages/dd-trace/src/instrumenter.js:229:35
    at Set.forEach (<anonymous>)
    at Instrumenter.unpatch (/app/app/node_modules/dd-trace/packages/dd-trace/src/instrumenter.js:227:20)
    at /app/app/node_modules/dd-trace/packages/dd-trace/src/instrumenter.js:197:14
    at Array.forEach (<anonymous>)
    at Instrumenter.unload (/app/app/node_modules/dd-trace/packages/dd-trace/src/instrumenter.js:196:8)
    at /app/app/node_modules/dd-trace/packages/dd-trace/src/platform/node/loader.js:106:30
    at Map.forEach (<anonymous>)
    at Loader._hookModule (/app/app/node_modules/dd-trace/packages/dd-trace/src/platform/node/loader.js:92:8)
    at Object.Module.require (/app/app/node_modules/require-in-the-middle/index.js:83:30)
    at Object.t (/app/app/node_modules/esm/esm.js:1:279775)
    at n (/app/app/node_modules/esm/esm.js:1:279589)
    at Object.<anonymous> (/app/app/node_modules/redis/lib/debug.js:3:13)
    at Object.<anonymous> (/app/app/node_modules/esm/esm.js:1:251206)
    at Object.<anonymous> (/app/app/node_modules/esm/esm.js:1:287446)
Error while trying to patch redis. The plugin has been disabled.
```

and I get the following integrations loaded
```
"integrations_loaded":["http","https","fs","net","dns","koa@2.13.0","http2","winston@3.3.3","bluebird@3.7.2","koa-router@10.0.0","aws-sdk@2.799.0"]
```

If I instead do the following, I get **_only_** redis out of the box. I added logic to manually tag the endpoints so I got that to mostly work, but no tracing of any other upstream calls, which really clouds my observations:
```
// server.js
const datadogTrace = require('dd-trace');
const tracer = datadogTrace.init();
const opentracing = require('opentracing');
opentracing.initGlobalTracer(tracer);
```
and I get the following integrations:
```
"integrations_loaded":["aws-sdk@2.799.0","bluebird@3.7.2","koa@2.13.0","koa-router@10.0.0","redis@3.0.2","winston@3.3.3"]
```
With this config, I had to manually setting the http.route tag to get the resources to show up in APM, and I really don't want to have to try to manually tag the other plugins, but at the moment I have half the picture of what's going on in my service. 

In our services that use express, which do not use esm, we are getting redis, express, and the other plugins we expect with no issue.

**Comment by provstevi** [comment]
I also have a support ticket open for this - 426982

**Comment by rochdev** [comment]
@provstevi Gotcha, thanks for the clarification! I expected an all or nothing situation, not individual plugins working and other not working. Definitely something we'll be looking into at some point.

One thing we've been trying to understand is the use case for using ESM over CommonJS. Can you share why you're using ESM?

**Comment by provstevi** [comment]
@rochdev it was a technical decision made by one our teams, and is now baked pretty deeply into several supporting packages. Same reason we have some services using koa and some using express.

NB: [ES Modules are stable in node as of 15.3](https://nodejs.org/docs/latest-v15.x/api/esm.html#esm_modules_ecmascript_modules).

**Comment by DaedalusX** [comment]
We also just ran into this issue as well. A potential workaround would be to migrate to Typescript (there's some tooling for this) but support for ESM would be fantastic until we can do that.

**Comment by richard-riverford** [comment]
I've also hit this issue. We have some isomorphic code that uses ESM both in Node and in modern browsers (without transpilation), so we just use ESM throughout the project. It would be too much work to revisit that decision now just to get Datadog tracing to work.

**Comment by rochdev** [comment]
We're working on a plan right now to support ESM soon. Since ESM in Node only supports a single loader hook, it's a bit complicated because it means we need to figure out a way to basically hook into any existing hook. While there is work to address that in Node itself, we still need a workaround that can land beforehand, especially since we support older versions of Node. Supporting this also means a rewrite of some core components of the tracer which will be non-trivial. However, we'll be prioritizing this soon as usage of ESM has been increasing. I will update this issue as progress is made.

**Comment by bengl** [comment]
Experimental support for ESM is in `dd-trace@>=1.3.0`. Simply add the loader hook hook using the following CLI argument to Node.js.

`--experimental-loader dd-trace/loader-hook.mjs`

Please contact us directly at `support@datadoghq.com` if any issues arise.

**Comment by luokuning** [comment]
> Experimental support for ESM is in `dd-trace@>=1.3.0`. Simply add the loader hook hook using the following CLI argument to Node.js.
> 
> `--experimental-loader dd-trace/loader-hook.mjs`
> 
> Please contact us directly at `support@datadoghq.com` if any issues arise.

I think this information should includes somewhere in the doc.

**Comment by rochdev** [comment]
> I think this information should includes somewhere in the doc.

We're still working on the functionality which is still in experimental stage, but we'll definitely add it to the doc once it's stable. There are a few known issues right now that can cause problems which we are actively working on. We definitely recommend testing this thoroughly before going to production with the loader, and to contact us if there are any issues.

**Comment by richard-riverford** [comment]
Great; thanks folks.
________________________________

**Comment by robaca** [comment]
When can we expect support for Node >= 16.12.1 where the loader API changed? Trying to add the hook on Node 16.13.1 outputs
```
(node:391569) DeprecationWarning: Obsolete loader hook(s) supplied and will be ignored: getFormat, getSource
```
...and the process exits immediately.

**Comment by rochdev** [comment]
@robaca I believe that was fixed a little while ago, maybe it was just not released. We're releasing 2.0 soon which will include everything on master, so I'd say to try that version when it lands (should be later today).

**Comment by robaca** [comment]
Hi @rochdev it seems that the immediate exit of our service has nothing to do with the deprecation warning. It's also happening with the older Node 16.11.0 as soon as we add the loader argument - difficult to troubleshoot.

**Comment by robaca** [comment]
We found the root cause of the immediate exit: we had a circular dependency between module files. After fixing that, the server started as expected. 
It would be great if the loader could at least render some descriptive error message in such a case.

**Comment by duki994** [comment]
For example I cannot even start my project with `--experimental-loader` hook. It just gets stuck. Other loaders work ok.
Though this may be due to TypeScript 4.7.4, top level `await` and usage of `reflect-metadata` and libraries dependent on `reflect-metadata`.

Most NodeJS ESM projects have packages which are compiled as CommonJS modules.
I have pinpointed issues in profiler. It gets stuck on `ritm.js: 51:56` when trying to process `@aws-sdk` v3.
However it everything works ok on old CommonJS Node 12 project with aws sdk v2 written in pure JS..

**Comment by duki994** [comment]
@rochdev 

There are no `dd-trace` startup logs when using standard Node ESM loader.
When using experimental, there are logs, but service won't start.


dd-trace: 3.3.1,
Node: 16.17.0

**Comment by rochdev** [comment]
@duki994 We're working on refactoring our tests so that eventually we can test each integration with ESM, but this is a several months long project. In the meantime, can you provide a reproduction so we can at least address the immediate issue?

**Comment by duki994** [comment]
@rochdev 

I can give you V8 profiling logs during startup of project.

Raw log
[v8-10-4-22_2-44-50-PM-.log](https://github.com/DataDog/dd-trace-js/files/9707244/v8-10-4-22_2-44-50-PM-.log)

Parsed txt statistics
[v8_statistics.txt](https://github.com/DataDog/dd-trace-js/files/9707246/v8_statistics.txt)


Generally, sample project I made to try and demonstrate issue cannot demonstrate it, because it doesn't occur in sample project.

**Comment by khanayan123** [comment]
Closing due to inactivity, if you are still having this problem please feel free to reopen
