### ISSUE TITLE
admission.datadoghq.com/js-lib.version 4.15.0 (latest) is causing pods to crash loop

### ISSUE THREAD

**Issue by omarkalloush** [DataDog/dd-trace-js#3625]
I'm using the following annotation on my pod `admission.datadoghq.com/js-lib.version: "latest"` and the pods keeps on crash looping with the following error
```
 /datadog-lib/node_modules/dd-trace/packages/dd-trace/src/plugins/tracing.js:58
     this.activeSpan?.finish()
                     ^

 SyntaxError: Unexpected token '.'
     at wrapSafe (internal/modules/cjs/loader.js:915:16)
     at Module._compile (internal/modules/cjs/loader.js:963:27)
     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
     at Module.load (internal/modules/cjs/loader.js:863:32)
     at Function.Module._load (internal/modules/cjs/loader.js:708:14)
     at Module.require (internal/modules/cjs/loader.js:887:19)
     at Module.Hook.Module.require (/datadog-lib/node_modules/dd-trace/packages/dd-trace/src/ritm.js:85:33)
     at require (internal/modules/cjs/helpers.js:74:18)
     at Object.<anonymous> (/datadog-lib/node_modules/dd-trace/packages/dd-trace/src/plugins/outbound.js:9:23)
     at Module._compile (internal/modules/cjs/loader.js:999:30)
```
But when I pinned the version to `4.14.0` its working fine.

**Environment**

* **Operation system: Ubuntu**
* **Node.js version: v12.18.3**
* **Relevant library versions: v4.15.0**

**Comment by omarkalloush** [comment]
This issue apperantly happens because the node version doesn't have the `?` method in it.
