### ISSUE TITLE
Playwright integration breaks with version 1.39.0

### ISSUE THREAD

**Issue by Meemaw** [DataDog/dd-trace-js#3721]
**Expected behaviour**
Playwright integration works on version 1.39.0

**Actual behaviour**
Playwright integration is broken on version 1.39.0

**Steps to reproduce**
```js
/home/runner/work/web-app-template/web-app-template/node_modules/dd-trace/packages/datadog-instrumentations/src/playwright.js:191
      const { test } = dispatcher._testById.get(testId)
                                            ^

TypeError: Cannot read properties of undefined (reading 'get')
    at WorkerHost.<anonymous> (/home/runner/work/web-app-template/web-app-template/node_modules/dd-trace/packages/datadog-instrumentations/src/playwright.js:191:45)
    at WorkerHost.emit (node:events:526:35)
    at ChildProcess.<anonymous> (/home/runner/work/web-app-template/web-app-template/node_modules/playwright/lib/runner/processHost.js:101:16)
    at ChildProcess.emit (node:events:514:28)
    at emit (node:internal/child_process:951:14)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
```

**Environment**

* **Operation system:** N/A
* **Node.js version:** N/A
* **Tracer version:** 4.16.0
* **Agent version:** N/A
* **Relevant library versions:** N/A

**Comment by juan-fernandez** [comment]
I'll close the issue and let you know when we release (should happen today or tomorrow) 😄

**Comment by juan-fernandez** [comment]
https://github.com/DataDog/dd-trace-js/releases/tag/v4.17.0 should include the fix. Let me know if it works for you 😄

**Comment by Meemaw** [comment]
@juan-fernandez that works. Thanks!
