### ISSUE TITLE
`http` plugin fails when added via `use` on disabled tracers

### ISSUE THREAD

**Issue by Nysosis** [DataDog/dd-trace-js#378]
Now, you might be wondering why I'd be calling `use` on a disabled tracer, well it's because I'm relying on the `DD_ENABLED` environment variable to control whether it was enabled or not, as opposed to specifiying it manually. So when I create my tracer, I can just have a simple initialisation without the need to check that env variable myself.

I've created a repro-repo at [dd-trace-js-gist](https://github.com/Nysosis/dd-trace-js-gist). This fails when it runs with:

```
TypeError: Cannot read property 'href' of undefined
    at Object.requestTrace [as request] (D:\GitHub\dd-trace-js-gist\node_modules\dd-trace\src\plugins\http.js:20:34)
    at RedirectableRequest._performRequest (D:\GitHub\dd-trace-js-gist\node_modules\follow-redirects\index.js:158:24)
    at new RedirectableRequest (D:\GitHub\dd-trace-js-gist\node_modules\follow-redirects\index.js:55:8)
    at Object.wrappedProtocol.request (D:\GitHub\dd-trace-js-gist\node_modules\follow-redirects\index.js:296:14)
    at dispatchHttpRequest (D:\GitHub\dd-trace-js-gist\node_modules\axios\lib\adapters\http.js:141:25)
    at new Promise (<anonymous>)
    at httpAdapter (D:\GitHub\dd-trace-js-gist\node_modules\axios\lib\adapters\http.js:18:10)
    at dispatchRequest (D:\GitHub\dd-trace-js-gist\node_modules\axios\lib\core\dispatchRequest.js:59:10)
    at process._tickCallback (internal/process/next_tick.js:68:7)
    at Function.Module.runMain (internal/modules/cjs/loader.js:744:11)
```

First shot solution that comes to mind would be to just return early out of `use` if the tracer isn't enabled?

**Comment by rochdev** [comment]
This is indeed a use case I didn't think about when implementing this. Your recommended solution is probably correct, as basically everything should be a no-op when the tracer is disabled. My only worry with returning early is if `.use()` is called before `.init()`. I will try to see if it's possible to still support this use case by registering plugins but not using them until the tracer is enabled. If it ends up being too involved I'll just return early.

In the meantime, a workaround would be to put all calls to `.use()` in a condition on the environment variable.
