### ISSUE TITLE
DataDog agent breaks VScode Remote SSH development

### ISSUE THREAD

**Issue by slyapustin** [DataDog/dd-trace-js#3856]
This issue, first reported in the VScode repository (https://github.com/microsoft/vscode/issues/196300), has been confirmed by several users to be related to the DataDog agent. Specifically, after installing the DataDog agent on a remote host, core extensions in VScode fail to activate during remote sessions.

```
2023-10-23 16:52:14.291 [error] Activating extension vscode.tunnel-forwarding failed due to an error:
2023-10-23 16:52:14.292 [error] Error: Cannot find module 'vscode'
Require stack:
- /home/userA/.vscode-server/bin/f1b07bd25dfad64b0167beb15359ae573aecd2cc/extensions/tunnel-forwarding/dist/extension.js
- /home/userA/.vscode-server/bin/f1b07bd25dfad64b0167beb15359ae573aecd2cc/out/vs/loader.js
- /home/userA/.vscode-server/bin/f1b07bd25dfad64b0167beb15359ae573aecd2cc/out/bootstrap-amd.js
- /home/userA/.vscode-server/bin/f1b07bd25dfad64b0167beb15359ae573aecd2cc/out/bootstrap-fork.js
	at Module._resolveFilename (node:internal/modules/cjs/loader:1075:15)
	at Hook.Module.require (/opt/datadog/apm/library/nodejs/node_modules/dd-trace/packages/dd-trace/src/ritm.js:54:29)
	at require (node:internal/modules/cjs/helpers:110:18)
	at 496 (/home/userA/.vscode-server/bin/f1b07bd25dfad64b0167beb15359ae573aecd2cc/extensions/tunnel-forwarding/dist/extension.js:1:1010)
	at s (/home/userA/.vscode-server/bin/f1b07bd25dfad64b0167beb15359ae573aecd2cc/extensions/tunnel-forwarding/dist/extension.js:1:1240)
	at /home/userA/.vscode-server/bin/f1b07bd25dfad64b0167beb15359ae573aecd2cc/extensions/tunnel-forwarding/dist/extension.js:1:1393
	at /home/userA/.vscode-server/bin/f1b07bd25dfad64b0167beb15359ae573aecd2cc/extensions/tunnel-forwarding/dist/extension.js:1:5981
	at Object.<anonymous> (/home/userA/.vscode-server/bin/f1b07bd25dfad64b0167beb15359ae573aecd2cc/extensions/tunnel-forwarding/dist/extension.js:1:6087)
	at Module._compile (node:internal/modules/cjs/loader:1254:14)
	at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
	at Module.load (node:internal/modules/cjs/loader:1117:32)
	at Module._load (node:internal/modules/cjs/loader:958:12)
	at u._load (/home/userA/.vscode-server/bin/f1b07bd25dfad64b0167beb15359ae573aecd2cc/out/vs/workbench/api/node/extensionHostProcess.js:154:5631)
	at c._load (/home/userA/.vscode-server/bin/f1b07bd25dfad64b0167beb15359ae573aecd2cc/out/vs/workbench/api/node/extensionHostProcess.js:151:29196)
	at t._load (/home/userA/.vscode-server/bin/f1b07bd25dfad64b0167beb15359ae573aecd2cc/out/vs/workbench/api/node/extensionHostProcess.js:118:35261)
	at Module.require (node:internal/modules/cjs/loader:1141:19)
	at Hook.Module.require (/opt/datadog/apm/library/nodejs/node_modules/dd-trace/packages/dd-trace/src/ritm.js:85:33)
	at require (node:internal/modules/cjs/helpers:110:18)
	at Function.i [as __$__nodeRequire] (/home/userA/.vscode-server/bin/f1b07bd25dfad64b0167beb15359ae573aecd2cc/out/vs/loader.js:5:98)
	at s.vb (/home/userA/.vscode-server/bin/f1b07bd25dfad64b0167beb15359ae573aecd2cc/out/vs/workbench/api/node/extensionHostProcess.js:151:30375)
	at async Promise.all (index 0)
2023-10-23 16:52:14.293 [error] Activating extension vscode.emmet failed due to an error:
2023-10-23 16:52:14.293 [error] Error: Cannot find module 'vscode'
Require stack:
- /home/userA/.vscode-server/bin/f1b07bd25dfad64b0167beb15359ae573aecd2cc/extensions/emmet/dist/node/emmetNodeMain.js
- /home/userA/.vscode-server/bin/f1b07bd25dfad64b0167beb15359ae573aecd2cc/out/vs/loader.js
- /home/userA/.vscode-server/bin/f1b07bd25dfad64b0167beb15359ae573aecd2cc/out/bootstrap-amd.js
- /home/userA/.vscode-server/bin/f1b07bd25dfad64b0167beb15359ae573aecd2cc/out/bootstrap-fork.js
	at Module._resolveFilename (node:internal/modules/cjs/loader:1075:15)
	at Hook.Module.require (/opt/datadog/apm/library/nodejs/node_modules/dd-trace/packages/dd-trace/src/ritm.js:54:29)
	at require (node:internal/modules/cjs/helpers:110:18)
	at 9496 (/home/userA/.vscode-server/bin/f1b07bd25dfad64b0167beb15359ae573aecd2cc/extensions/emmet/dist/node/emmetNodeMain.js:1:168136)
	at n (/home/userA/.vscode-server/bin/f1b07bd25dfad64b0167beb15359ae573aecd2cc/extensions/emmet/dist/node/emmetNodeMain.js:1:239837)
	at /home/userA/.vscode-server/bin/f1b07bd25dfad64b0167beb15359ae573aecd2cc/extensions/emmet/dist/node/emmetNodeMain.js:1:240309
	at /home/userA/.vscode-server/bin/f1b07bd25dfad64b0167beb15359ae573aecd2cc/extensions/emmet/dist/node/emmetNodeMain.js:1:240573
	at Object.<anonymous> (/home/userA/.vscode-server/bin/f1b07bd25dfad64b0167beb15359ae573aecd2cc/extensions/emmet/dist/node/emmetNodeMain.js:1:240679)
	at Module._compile (node:internal/modules/cjs/loader:1254:14)
	at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
	at Module.load (node:internal/modules/cjs/loader:1117:32)
	at Module._load (node:internal/modules/cjs/loader:958:12)
	at u._load (/home/userA/.vscode-server/bin/f1b07bd25dfad64b0167beb15359ae573aecd2cc/out/vs/workbench/api/node/extensionHostProcess.js:154:5631)
	at c._load (/home/userA/.vscode-server/bin/f1b07bd25dfad64b0167beb15359ae573aecd2cc/out/vs/workbench/api/node/extensionHostProcess.js:151:29196)
	at t._load (/home/userA/.vscode-server/bin/f1b07bd25dfad64b0167beb15359ae573aecd2cc/out/vs/workbench/api/node/extensionHostProcess.js:118:35261)
	at Module.require (node:internal/modules/cjs/loader:1141:19)
	at Hook.Module.require (/opt/datadog/apm/library/nodejs/node_modules/dd-trace/packages/dd-trace/src/ritm.js:85:33)
	at require (node:internal/modules/cjs/helpers:110:18)
	at Function.i [as __$__nodeRequire] (/home/userA/.vscode-server/bin/f1b07bd25dfad64b0167beb15359ae573aecd2cc/out/vs/loader.js:5:98)
	at s.vb (/home/userA/.vscode-server/bin/f1b07bd25dfad64b0167beb15359ae573aecd2cc/out/vs/workbench/api/node/extensionHostProcess.js:151:30375)
	at async Promise.all (index 0)
2023-10-23 16:52:14.293 [error] Activating extension vscode.git-base failed due to an error:
2023-10-23 16:52:14.293 [error] Error: Cannot find module 'vscode'
Require stack:
- /home/userA/.vscode-server/bin/f1b07bd25dfad64b0167beb15359ae573aecd2cc/extensions/git-base/dist/extension.js
- /home/userA/.vscode-server/bin/f1b07bd25dfad64b0167beb15359ae573aecd2cc/out/vs/loader.js
- /home/userA/.vscode-server/bin/f1b07bd25dfad64b0167beb15359ae573aecd2cc/out/bootstrap-amd.js
- /home/userA/.vscode-server/bin/f1b07bd25dfad64b0167beb15359ae573aecd2cc/out/bootstrap-fork.js
	at Module._resolveFilename (node:internal/modules/cjs/loader:1075:15)
	at Hook.Module.require (/opt/datadog/apm/library/nodejs/node_modules/dd-trace/packages/dd-trace/src/ritm.js:54:29)
	at require (node:internal/modules/cjs/helpers:110:18)
	at 496 (/home/userA/.vscode-server/bin/f1b07bd25dfad64b0167beb15359ae573aecd2cc/extensions/git-base/dist/extension.js:1:6494)
	at r (/home/userA/.vscode-server/bin/f1b07bd25dfad64b0167beb15359ae573aecd2cc/extensions/git-base/dist/extension.js:1:6611)
	at 699 (/home/userA/.vscode-server/bin/f1b07bd25dfad64b0167beb15359ae573aecd2cc/extensions/git-base/dist/extension.js:1:115)
	at r (/home/userA/.vscode-server/bin/f1b07bd25dfad64b0167beb15359ae573aecd2cc/extensions/git-base/dist/extension.js:1:6611)
	at /home/userA/.vscode-server/bin/f1b07bd25dfad64b0167beb15359ae573aecd2cc/extensions/git-base/dist/extension.js:1:6749
	at /home/userA/.vscode-server/bin/f1b07bd25dfad64b0167beb15359ae573aecd2cc/extensions/git-base/dist/extension.js:1:6868
	at Object.<anonymous> (/home/userA/.vscode-server/bin/f1b07bd25dfad64b0167beb15359ae573aecd2cc/extensions/git-base/dist/extension.js:1:6974)
	at Module._compile (node:internal/modules/cjs/loader:1254:14)
	at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
	at Module.load (node:internal/modules/cjs/loader:1117:32)
	at Module._load (node:internal/modules/cjs/loader:958:12)
	at u._load (/home/userA/.vscode-server/bin/f1b07bd25dfad64b0167beb15359ae573aecd2cc/out/vs/workbench/api/node/extensionHostProcess.js:154:5631)
	at c._load (/home/userA/.vscode-server/bin/f1b07bd25dfad64b0167beb15359ae573aecd2cc/out/vs/workbench/api/node/extensionHostProcess.js:151:29196)
	at t._load (/home/userA/.vscode-server/bin/f1b07bd25dfad64b0167beb15359ae573aecd2cc/out/vs/workbench/api/node/extensionHostProcess.js:118:35261)
	at Module.require (node:internal/modules/cjs/loader:1141:19)
	at Hook.Module.require (/opt/datadog/apm/library/nodejs/node_modules/dd-trace/packages/dd-trace/src/ritm.js:85:33)
	at require (node:internal/modules/cjs/helpers:110:18)
	at Function.i [as __$__nodeRequire] (/home/userA/.vscode-server/bin/f1b07bd25dfad64b0167beb15359ae573aecd2cc/out/vs/loader.js:5:98)
	at s.vb (/home/userA/.vscode-server/bin/f1b07bd25dfad64b0167beb15359ae573aecd2cc/out/vs/workbench/api/node/extensionHostProcess.js:151:30375)
	at async Promise.all (index 0)
2023-10-23 16:52:14.588 [info] ExtensionService#_doActivateExtension hashicorp.terraform, startup: true, activationEvent: 'workspaceContains:**/*.tf,**/*.tfvars'
2023-10-23 16:52:14.624 [error] Activating extension hashicorp.terraform failed due to an error:
2023-10-23 16:52:14.624 [error] Error: Cannot find module 'vscode'
Require stack:
- /home/userA/.vscode-server/extensions/hashicorp.terraform-2.28.2/out/extension.js
- /home/userA/.vscode-server/bin/f1b07bd25dfad64b0167beb15359ae573aecd2cc/out/vs/loader.js
- /home/userA/.vscode-server/bin/f1b07bd25dfad64b0167beb15359ae573aecd2cc/out/bootstrap-amd.js
- /home/userA/.vscode-server/bin/f1b07bd25dfad64b0167beb15359ae573aecd2cc/out/bootstrap-fork.js
	at Module._resolveFilename (node:internal/modules/cjs/loader:1075:15)
	at Hook.Module.require (/opt/datadog/apm/library/nodejs/node_modules/dd-trace/packages/dd-trace/src/ritm.js:54:29)
	at require (node:internal/modules/cjs/helpers:110:18)
	at 9496 (/home/userA/.vscode-server/extensions/hashicorp.terraform-2.28.2/out/extension.js:1:712219)
	at n (/home/userA/.vscode-server/extensions/hashicorp.terraform-2.28.2/out/extension.js:1:713400)
	at /home/userA/.vscode-server/extensions/hashicorp.terraform-2.28.2/out/extension.js:1:713885
	at /home/userA/.vscode-server/extensions/hashicorp.terraform-2.28.2/out/extension.js:1:717774
	at Object.<anonymous> (/home/userA/.vscode-server/extensions/hashicorp.terraform-2.28.2/out/extension.js:1:717795)
	at Module._compile (node:internal/modules/cjs/loader:1254:14)
	at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
	at Module.load (node:internal/modules/cjs/loader:1117:32)
	at Module._load (node:internal/modules/cjs/loader:958:12)
	at u._load (/home/userA/.vscode-server/bin/f1b07bd25dfad64b0167beb15359ae573aecd2cc/out/vs/workbench/api/node/extensionHostProcess.js:154:5631)
	at c._load (/home/userA/.vscode-server/bin/f1b07bd25dfad64b0167beb15359ae573aecd2cc/out/vs/workbench/api/node/extensionHostProcess.js:151:29196)
	at t._load (/home/userA/.vscode-server/bin/f1b07bd25dfad64b0167beb15359ae573aecd2cc/out/vs/workbench/api/node/extensionHostProcess.js:118:35261)
	at Module.require (node:internal/modules/cjs/loader:1141:19)
	at Hook.Module.require (/opt/datadog/apm/library/nodejs/node_modules/dd-trace/packages/dd-trace/src/ritm.js:85:33)
	at require (node:internal/modules/cjs/helpers:110:18)
	at Function.i [as __$__nodeRequire] (/home/userA/.vscode-server/bin/f1b07bd25dfad64b0167beb15359ae573aecd2cc/out/vs/loader.js:5:98)
	at s.vb (/home/userA/.vscode-server/bin/f1b07bd25dfad64b0167beb15359ae573aecd2cc/out/vs/workbench/api/node/extensionHostProcess.js:151:30375)
	at async Promise.all (index 0)
2023-10-23 16:52:14.625 [info] Eager extensions activated
2023-10-23 16:52:14.633 [info] ExtensionService#_doActivateExtension vscode.debug-auto-launch, startup: false, activationEvent: 'onStartupFinished'
2023-10-23 16:52:14.633 [info] ExtensionService#_doActivateExtension vscode.merge-conflict, startup: false, activationEvent: 'onStartupFinished'
2023-10-23 16:52:14.667 [error] Activating extension vscode.debug-auto-launch failed due to an error:
2023-10-23 16:52:14.667 [error] Error: Cannot find module 'vscode'
Require stack:
- /home/userA/.vscode-server/bin/f1b07bd25dfad64b0167beb15359ae573aecd2cc/extensions/debug-auto-launch/dist/extension.js
- /home/userA/.vscode-server/bin/f1b07bd25dfad64b0167beb15359ae573aecd2cc/out/vs/loader.js
- /home/userA/.vscode-server/bin/f1b07bd25dfad64b0167beb15359ae573aecd2cc/out/bootstrap-amd.js
- /home/userA/.vscode-server/bin/f1b07bd25dfad64b0167beb15359ae573aecd2cc/out/bootstrap-fork.js
	at Module._resolveFilename (node:internal/modules/cjs/loader:1075:15)
	at Hook.Module.require (/opt/datadog/apm/library/nodejs/node_modules/dd-trace/packages/dd-trace/src/ritm.js:54:29)
	at require (node:internal/modules/cjs/helpers:110:18)
	at 496 (/home/userA/.vscode-server/bin/f1b07bd25dfad64b0167beb15359ae573aecd2cc/extensions/debug-auto-launch/dist/extension.js:1:45)
	at a (/home/userA/.vscode-server/bin/f1b07bd25dfad64b0167beb15359ae573aecd2cc/extensions/debug-auto-launch/dist/extension.js:1:262)
	at /home/userA/.vscode-server/bin/f1b07bd25dfad64b0167beb15359ae573aecd2cc/extensions/debug-auto-launch/dist/extension.js:1:425
	at /home/userA/.vscode-server/bin/f1b07bd25dfad64b0167beb15359ae573aecd2cc/extensions/debug-auto-launch/dist/extension.js:1:5410
	at Object.<anonymous> (/home/userA/.vscode-server/bin/f1b07bd25dfad64b0167beb15359ae573aecd2cc/extensions/debug-auto-launch/dist/extension.js:1:5516)
	at Module._compile (node:internal/modules/cjs/loader:1254:14)
	at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
	at Module.load (node:internal/modules/cjs/loader:1117:32)
	at Module._load (node:internal/modules/cjs/loader:958:12)
	at u._load (/home/userA/.vscode-server/bin/f1b07bd25dfad64b0167beb15359ae573aecd2cc/out/vs/workbench/api/node/extensionHostProcess.js:154:5631)
	at c._load (/home/userA/.vscode-server/bin/f1b07bd25dfad64b0167beb15359ae573aecd2cc/out/vs/workbench/api/node/extensionHostProcess.js:151:29196)
	at t._load (/home/userA/.vscode-server/bin/f1b07bd25dfad64b0167beb15359ae573aecd2cc/out/vs/workbench/api/node/extensionHostProcess.js:118:35261)
	at Module.require (node:internal/modules/cjs/loader:1141:19)
	at Hook.Module.require (/opt/datadog/apm/library/nodejs/node_modules/dd-trace/packages/dd-trace/src/ritm.js:85:33)
	at require (node:internal/modules/cjs/helpers:110:18)
	at Function.i [as __$__nodeRequire] (/home/userA/.vscode-server/bin/f1b07bd25dfad64b0167beb15359ae573aecd2cc/out/vs/loader.js:5:98)
	at s.vb (/home/userA/.vscode-server/bin/f1b07bd25dfad64b0167beb15359ae573aecd2cc/out/vs/workbench/api/node/extensionHostProcess.js:151:30375)
	at async Promise.all (index 0)
2023-10-23 16:52:14.669 [error] Activating extension vscode.merge-conflict failed due to an error:
2023-10-23 16:52:14.669 [error] Error: Cannot find module 'vscode'
Require stack:
- /home/userA/.vscode-server/bin/f1b07bd25dfad64b0167beb15359ae573aecd2cc/extensions/merge-conflict/dist/mergeConflictMain.js
- /home/userA/.vscode-server/bin/f1b07bd25dfad64b0167beb15359ae573aecd2cc/out/vs/loader.js
- /home/userA/.vscode-server/bin/f1b07bd25dfad64b0167beb15359ae573aecd2cc/out/bootstrap-amd.js
- /home/userA/.vscode-server/bin/f1b07bd25dfad64b0167beb15359ae573aecd2cc/out/bootstrap-fork.js
	at Module._resolveFilename (node:internal/modules/cjs/loader:1075:15)
	at Hook.Module.require (/opt/datadog/apm/library/nodejs/node_modules/dd-trace/packages/dd-trace/src/ritm.js:54:29)
	at require (node:internal/modules/cjs/helpers:110:18)
	at 9496 (/home/userA/.vscode-server/bin/f1b07bd25dfad64b0167beb15359ae573aecd2cc/extensions/merge-conflict/dist/mergeConflictMain.js:2:580537)
	at n (/home/userA/.vscode-server/bin/f1b07bd25dfad64b0167beb15359ae573aecd2cc/extensions/merge-conflict/dist/mergeConflictMain.js:2:728117)
	at 8823 (/home/userA/.vscode-server/bin/f1b07bd25dfad64b0167beb15359ae573aecd2cc/extensions/merge-conflict/dist/mergeConflictMain.js:2:579272)
	at n (/home/userA/.vscode-server/bin/f1b07bd25dfad64b0167beb15359ae573aecd2cc/extensions/merge-conflict/dist/mergeConflictMain.js:2:728117)
	at /home/userA/.vscode-server/bin/f1b07bd25dfad64b0167beb15359ae573aecd2cc/extensions/merge-conflict/dist/mergeConflictMain.js:2:728675
	at /home/userA/.vscode-server/bin/f1b07bd25dfad64b0167beb15359ae573aecd2cc/extensions/merge-conflict/dist/mergeConflictMain.js:2:728793
	at Object.<anonymous> (/home/userA/.vscode-server/bin/f1b07bd25dfad64b0167beb15359ae573aecd2cc/extensions/merge-conflict/dist/mergeConflictMain.js:2:728899)
	at Module._compile (node:internal/modules/cjs/loader:1254:14)
	at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
	at Module.load (node:internal/modules/cjs/loader:1117:32)
	at Module._load (node:internal/modules/cjs/loader:958:12)
	at u._load (/home/userA/.vscode-server/bin/f1b07bd25dfad64b0167beb15359ae573aecd2cc/out/vs/workbench/api/node/extensionHostProcess.js:154:5631)
	at c._load (/home/userA/.vscode-server/bin/f1b07bd25dfad64b0167beb15359ae573aecd2cc/out/vs/workbench/api/node/extensionHostProcess.js:151:29196)
	at t._load (/home/userA/.vscode-server/bin/f1b07bd25dfad64b0167beb15359ae573aecd2cc/out/vs/workbench/api/node/extensionHostProcess.js:118:35261)
	at Module.require (node:internal/modules/cjs/loader:1141:19)
	at Hook.Module.require (/opt/datadog/apm/library/nodejs/node_modules/dd-trace/packages/dd-trace/src/ritm.js:85:33)
	at require (node:internal/modules/cjs/helpers:110:18)
	at Function.i [as __$__nodeRequire] (/home/userA/.vscode-server/bin/f1b07bd25dfad64b0167beb15359ae573aecd2cc/out/vs/loader.js:5:98)
	at s.vb (/home/userA/.vscode-server/bin/f1b07bd25dfad64b0167beb15359ae573aecd2cc/out/vs/workbench/api/node/extensionHostProcess.js:151:30375)
	at async Promise.all (index 0)
2023-10-23 16:52:14.813 [info] ExtensionService#_doActivateExtension vscode.json-language-features, startup: false, activationEvent: 'onLanguage:jsonc'
2023-10-23 16:52:14.814 [info] ExtensionService#_doActivateExtension vscode.typescript-language-features, startup: false, activationEvent: 'onLanguage:jsonc'
2023-10-23 16:52:14.888 [error] Activating extension vscode.json-language-features failed due to an error:
2023-10-23 16:52:14.888 [error] Error: Cannot find module 'vscode'
Require stack:
- /home/userA/.vscode-server/bin/f1b07bd25dfad64b0167beb15359ae573aecd2cc/extensions/json-language-features/client/dist/node/jsonClientMain.js
- /home/userA/.vscode-server/bin/f1b07bd25dfad64b0167beb15359ae573aecd2cc/out/vs/loader.js
- /home/userA/.vscode-server/bin/f1b07bd25dfad64b0167beb15359ae573aecd2cc/out/bootstrap-amd.js
- /home/userA/.vscode-server/bin/f1b07bd25dfad64b0167beb15359ae573aecd2cc/out/bootstrap-fork.js
	at Module._resolveFilename (node:internal/modules/cjs/loader:1075:15)
	at Hook.Module.require (/opt/datadog/apm/library/nodejs/node_modules/dd-trace/packages/dd-trace/src/ritm.js:54:29)
	at require (node:internal/modules/cjs/helpers:110:18)
	at 9496 (/home/userA/.vscode-server/bin/f1b07bd25dfad64b0167beb15359ae573aecd2cc/extensions/json-language-features/client/dist/node/jsonClientMain.js:2:947775)
	at n (/home/userA/.vscode-server/bin/f1b07bd25dfad64b0167beb15359ae573aecd2cc/extensions/json-language-features/client/dist/node/jsonClientMain.js:2:1095355)
	at /home/userA/.vscode-server/bin/f1b07bd25dfad64b0167beb15359ae573aecd2cc/extensions/json-language-features/client/dist/node/jsonClientMain.js:2:1095913
	at /home/userA/.vscode-server/bin/f1b07bd25dfad64b0167beb15359ae573aecd2cc/extensions/json-language-features/client/dist/node/jsonClientMain.js:2:1098980
	at Object.<anonymous> (/home/userA/.vscode-server/bin/f1b07bd25dfad64b0167beb15359ae573aecd2cc/extensions/json-language-features/client/dist/node/jsonClientMain.js:2:1099086)
	at Module._compile (node:internal/modules/cjs/loader:1254:14)
	at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
	at Module.load (node:internal/modules/cjs/loader:1117:32)
	at Module._load (node:internal/modules/cjs/loader:958:12)
	at u._load (/home/userA/.vscode-server/bin/f1b07bd25dfad64b0167beb15359ae573aecd2cc/out/vs/workbench/api/node/extensionHostProcess.js:154:5631)
	at c._load (/home/userA/.vscode-server/bin/f1b07bd25dfad64b0167beb15359ae573aecd2cc/out/vs/workbench/api/node/extensionHostProcess.js:151:29196)
	at t._load (/home/userA/.vscode-server/bin/f1b07bd25dfad64b0167beb15359ae573aecd2cc/out/vs/workbench/api/node/extensionHostProcess.js:118:35261)
	at Module.require (node:internal/modules/cjs/loader:1141:19)
	at Hook.Module.require (/opt/datadog/apm/library/nodejs/node_modules/dd-trace/packages/dd-trace/src/ritm.js:85:33)
	at require (node:internal/modules/cjs/helpers:110:18)
	at Function.i [as __$__nodeRequire] (/home/userA/.vscode-server/bin/f1b07bd25dfad64b0167beb15359ae573aecd2cc/out/vs/loader.js:5:98)
	at s.vb (/home/userA/.vscode-server/bin/f1b07bd25dfad64b0167beb15359ae573aecd2cc/out/vs/workbench/api/node/extensionHostProcess.js:151:30375)
	at async Promise.all (index 0)
2023-10-23 16:52:14.890 [error] Activating extension vscode.typescript-language-features failed due to an error:
2023-10-23 16:52:14.890 [error] Error: Cannot find module 'vscode'
Require stack:
- /home/userA/.vscode-server/bin/f1b07bd25dfad64b0167beb15359ae573aecd2cc/extensions/typescript-language-features/dist/extension.js
- /home/userA/.vscode-server/bin/f1b07bd25dfad64b0167beb15359ae573aecd2cc/out/vs/loader.js
- /home/userA/.vscode-server/bin/f1b07bd25dfad64b0167beb15359ae573aecd2cc/out/bootstrap-amd.js
- /home/userA/.vscode-server/bin/f1b07bd25dfad64b0167beb15359ae573aecd2cc/out/bootstrap-fork.js
	at Module._resolveFilename (node:internal/modules/cjs/loader:1075:15)
	at Hook.Module.require (/opt/datadog/apm/library/nodejs/node_modules/dd-trace/packages/dd-trace/src/ritm.js:54:29)
	at require (node:internal/modules/cjs/helpers:110:18)
	at 89496 (/home/userA/.vscode-server/bin/f1b07bd25dfad64b0167beb15359ae573aecd2cc/extensions/typescript-language-features/dist/extension.js:2:940993)
	at n (/home/userA/.vscode-server/bin/f1b07bd25dfad64b0167beb15359ae573aecd2cc/extensions/typescript-language-features/dist/extension.js:2:1088597)
	at 92291 (/home/userA/.vscode-server/bin/f1b07bd25dfad64b0167beb15359ae573aecd2cc/extensions/typescript-language-features/dist/extension.js:2:229345)
	at n (/home/userA/.vscode-server/bin/f1b07bd25dfad64b0167beb15359ae573aecd2cc/extensions/typescript-language-features/dist/extension.js:2:1088597)
	at 15303 (/home/userA/.vscode-server/bin/f1b07bd25dfad64b0167beb15359ae573aecd2cc/extensions/typescript-language-features/dist/extension.js:2:691143)
	at n (/home/userA/.vscode-server/bin/f1b07bd25dfad64b0167beb15359ae573aecd2cc/extensions/typescript-language-features/dist/extension.js:2:1088597)
	at /home/userA/.vscode-server/bin/f1b07bd25dfad64b0167beb15359ae573aecd2cc/extensions/typescript-language-features/dist/extension.js:2:1089037
	at Object.<anonymous> (/home/userA/.vscode-server/bin/f1b07bd25dfad64b0167beb15359ae573aecd2cc/extensions/typescript-language-features/dist/extension.js:2:1089145)
	at Module._compile (node:internal/modules/cjs/loader:1254:14)
	at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
	at Module.load (node:internal/modules/cjs/loader:1117:32)
	at Module._load (node:internal/modules/cjs/loader:958:12)
	at u._load (/home/userA/.vscode-server/bin/f1b07bd25dfad64b0167beb15359ae573aecd2cc/out/vs/workbench/api/node/extensionHostProcess.js:154:5631)
	at c._load (/home/userA/.vscode-server/bin/f1b07bd25dfad64b0167beb15359ae573aecd2cc/out/vs/workbench/api/node/extensionHostProcess.js:151:29196)
	at t._load (/home/userA/.vscode-server/bin/f1b07bd25dfad64b0167beb15359ae573aecd2cc/out/vs/workbench/api/node/extensionHostProcess.js:118:35261)
	at Module.require (node:internal/modules/cjs/loader:1141:19)
	at Hook.Module.require (/opt/datadog/apm/library/nodejs/node_modules/dd-trace/packages/dd-trace/src/ritm.js:85:33)
	at require (node:internal/modules/cjs/helpers:110:18)
	at Function.i [as __$__nodeRequire] (/home/userA/.vscode-server/bin/f1b07bd25dfad64b0167beb15359ae573aecd2cc/out/vs/loader.js:5:98)
	at s.vb (/home/userA/.vscode-server/bin/f1b07bd25dfad64b0167beb15359ae573aecd2cc/out/vs/workbench/api/node/extensionHostProcess.js:151:30375)
	at async Promise.all (index 0)
2023-10-23 16:54:27.423 [info] ExtensionService#_doActivateExtension vscode.npm, startup: false, activationEvent: 'onTerminalQuickFixRequest:ms-vscode.npm-command'
2023-10-23 16:54:27.440 [error] Activating extension vscode.npm failed due to an error:
2023-10-23 16:54:27.440 [error] Error: Cannot find module 'vscode'
Require stack:
- /home/userA/.vscode-server/bin/f1b07bd25dfad64b0167beb15359ae573aecd2cc/extensions/npm/dist/npmMain.js
- /home/userA/.vscode-server/bin/f1b07bd25dfad64b0167beb15359ae573aecd2cc/out/vs/loader.js
- /home/userA/.vscode-server/bin/f1b07bd25dfad64b0167beb15359ae573aecd2cc/out/bootstrap-amd.js
- /home/userA/.vscode-server/bin/f1b07bd25dfad64b0167beb15359ae573aecd2cc/out/bootstrap-fork.js
	at Module._resolveFilename (node:internal/modules/cjs/loader:1075:15)
	at Hook.Module.require (/opt/datadog/apm/library/nodejs/node_modules/dd-trace/packages/dd-trace/src/ritm.js:54:29)
	at require (node:internal/modules/cjs/helpers:110:18)
	at 9496 (/home/userA/.vscode-server/bin/f1b07bd25dfad64b0167beb15359ae573aecd2cc/extensions/npm/dist/npmMain.js:2:324847)
	at n (/home/userA/.vscode-server/bin/f1b07bd25dfad64b0167beb15359ae573aecd2cc/extensions/npm/dist/npmMain.js:2:328404)
	at /home/userA/.vscode-server/bin/f1b07bd25dfad64b0167beb15359ae573aecd2cc/extensions/npm/dist/npmMain.js:2:328899
	at /home/userA/.vscode-server/bin/f1b07bd25dfad64b0167beb15359ae573aecd2cc/extensions/npm/dist/npmMain.js:2:331494
	at Object.<anonymous> (/home/userA/.vscode-server/bin/f1b07bd25dfad64b0167beb15359ae573aecd2cc/extensions/npm/dist/npmMain.js:2:331600)
	at Module._compile (node:internal/modules/cjs/loader:1254:14)
	at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
	at Module.load (node:internal/modules/cjs/loader:1117:32)
	at Module._load (node:internal/modules/cjs/loader:958:12)
	at u._load (/home/userA/.vscode-server/bin/f1b07bd25dfad64b0167beb15359ae573aecd2cc/out/vs/workbench/api/node/extensionHostProcess.js:154:5631)
	at c._load (/home/userA/.vscode-server/bin/f1b07bd25dfad64b0167beb15359ae573aecd2cc/out/vs/workbench/api/node/extensionHostProcess.js:151:29196)
	at t._load (/home/userA/.vscode-server/bin/f1b07bd25dfad64b0167beb15359ae573aecd2cc/out/vs/workbench/api/node/extensionHostProcess.js:118:35261)
	at Module.require (node:internal/modules/cjs/loader:1141:19)
	at Hook.Module.require (/opt/datadog/apm/library/nodejs/node_modules/dd-trace/packages/dd-trace/src/ritm.js:85:33)
	at require (node:internal/modules/cjs/helpers:110:18)
	at Function.i [as __$__nodeRequire] (/home/userA/.vscode-server/bin/f1b07bd25dfad64b0167beb15359ae573aecd2cc/out/vs/loader.js:5:98)
	at s.vb (/home/userA/.vscode-server/bin/f1b07bd25dfad64b0167beb15359ae573aecd2cc/out/vs/workbench/api/node/extensionHostProcess.js:151:30375)
	at async Promise.all (index 0)
```

As suggested by @amenasria  - moved there from https://github.com/DataDog/datadog-agent/issues/21406

**Comment by zeptonaut** [comment]
Also ran into this this morning (tracked as https://github.com/direnv/direnv-vscode/issues/434#issuecomment-1866863764). I probably lost ~half a day of development time to this: had I not discovered https://github.com/microsoft/vscode/issues/196300, I think I would have lost at least another half day. 

The connection datadog-agent and VS Code extensions was not at all obvious to me, which feels like it increases the urgency of fixing this issue: I suspect others that run into this issue will lose at least as much time, as I think it was just dumb luck that I figured it out.

**Comment by aw-dd** [comment]
related public issue: https://github.com/DataDog/datadog-agent/issues/21882
