### ISSUE TITLE
DD_AGENT_HOST is not used properly by the profiler for ipv6 addresses

### ISSUE THREAD

**Issue by colinhowe** [DataDog/dd-trace-js#3947]
## Related issue
Similar to #2449 - this time for the profiler.

## Expected behavior
In an IPv6 EKS cluster, $DD_AGENT_HOST is set to an IPv6 address, and requests should be sent correctly.

## Actual behavior
URLs are passed through using the `URL` object which then has the `hostname` field extracted here: https://github.com/DataDog/dd-trace-js/blame/master/packages/dd-trace/src/profiling/exporters/agent.js#L136

This results in a hostname that looks like `[2600:1f10:4380:1e10::f3b2]` which isn't going to work. We've patched this locally using:
```typescript
options.hostname = this._url.hostname.startsWith('[') ? this._url.hostname.slice(1, -1) : this._url.hostname;
```

And this works for us.

A full stacktrace is below:

```
Submitting profiler agent report attempt #1 to: {"method":"POST","path":"/profiling/v1/input","headers":{"Content-Type":"multipart/form-data; boundary=66e5f3ebcba00a11","Datadog-Container-ID":"4aed372f-7659-4a27-8a23-1032d1ae995f"},"timeout":1874,"protocol":"http:","hostname":"[2600:1f10:4380:1e10::f3b2]","port":"8126"}
Error: Error from the agent: getaddrinfo ENOTFOUND [2600:1f10:4380:1e10::f3b2]
    at error (.../node_modules/dd-trace/packages/dd-trace/src/log/writer.js:104:11)
    at onError (.../node_modules/dd-trace/packages/dd-trace/src/log/writer.js:81:16)
    at Channel.publish (node:diagnostics_channel:142:9)
    at Object.error (.../node_modules/dd-trace/packages/dd-trace/src/log/index.js:67:20)
    at Object.error (.../node_modules/dd-trace/packages/dd-trace/src/profiler.js:17:31)
    at ClientRequest.<anonymous> (.../node_modules/dd-trace/packages/dd-trace/src/profiling/exporters/agent.js:146:26)
    at ClientRequest.emit (node:events:526:35)
    at ClientRequest.emit (node:domain:488:12)
    at ClientRequest.emit (.../node_modules/dd-trace/packages/datadog-instrumentations/src/http/client.js:97:25)
    at Socket.socketErrorListener (node:_http_client:495:9)
```

**Comment by benasher44** [comment]
It looks like this code should be using `url.urlToHttpOptions`, but it's not.
