### ISSUE TITLE
Express plugin not working

### ISSUE THREAD

**Issue by suhjohn** [DataDog/dd-trace-js#4037]
tracer.init is happening first thing in the code. However, top level request is http component not express. 

<img width="260" alt="Screenshot 2024-02-07 at 5 00 21 PM" src="https://github.com/DataDog/dd-trace-js/assets/31156679/79c65b1d-b43a-45c5-9998-4c9fc3ea01f3">

<img width="1001" alt="Screenshot 2024-02-07 at 5 00 46 PM" src="https://github.com/DataDog/dd-trace-js/assets/31156679/28a45e84-16dd-4052-b04a-754fe57cc061">

To override this, tried to add a hook:
```
tracer.use('http', {
  hooks: {
    request: (span, req, _) => {
      if (span !== undefined) {
        if (req instanceof IncomingMessage) {
          logger.info(
            `[tracer.ts] req instanceof IncomingMessage setting resource.name - Span: ${span} req: ${req.url}`,
          );
        } else if (req instanceof ClientRequest) {
          logger.info(
            `[tracer.ts] req instanceof ClientRequest setting resource.name - Span: ${span} req: ${req.path}`,
          );
        }
      }
      if (req instanceof IncomingMessage) {
        logger.info(
          `[tracer.ts] req instanceof IncomingMessage span is undefined - req: ${req.url}`,
        );
      } else if (req instanceof ClientRequest) {
        logger.info(
          `[tracer.ts] req instanceof ClientRequest span is undefined - req: ${req.path}`,
        );
      }
    },
  },
});
```

This caused the application to crash with the following issue:

```
2024-02-08 00:24:32 [server] error: TypeError: Cannot read properties of undefined (reading 'length')

at DatadogSpan.toString (/usr/src/app/node_modules/dd-trace/packages/dd-trace/src/opentracing/span.js:100:35)

at Object.request (file:///usr/src/app/server/build/src/config/tracer.js:27:109)

at Object.finishSpan (/usr/src/app/node_modules/dd-trace/packages/dd-trace/src/plugins/util/web.js:302:26)

at Object.finishAll (/usr/src/app/node_modules/dd-trace/packages/dd-trace/src/plugins/util/web.js:316:9)

at HttpServerPlugin.finish (/usr/src/app/node_modules/dd-trace/packages/datadog-plugin-http/src/server.js:66:9)

at /usr/src/app/node_modules/dd-trace/packages/dd-trace/src/plugins/tracing.js:73:22

at Subscription._handler (/usr/src/app/node_modules/dd-trace/packages/dd-trace/src/plugins/plugin.js:14:9)

at Channel.publish (node:diagnostics_channel:56:9)

at ServerResponse.emit (/usr/src/app/node_modules/dd-trace/packages/datadog-instrumentations/src/http/server.js:40:22)

at onFinish (node:_http_outgoing:1001:10)
```

Is that the right way to use hooks? How can I override the `resource.name` to something more sane?

**Comment by suhjohn** [comment]
https://github.com/DataDog/dd-trace-js/issues/3595

**Comment by theodormarcu** [comment]
https://github.com/DataDog/dd-trace-js/issues/3595

Looks like this issue is what's causing the trouble. Following all the instructions leads to an app that exits early because of cyclical dependencies. We do not have cyclical dependencies in the app.
