### ISSUE TITLE
Unhandled rejection thrown with Mongodb 6.4.0

### ISSUE THREAD

**Issue by omairvaiyani** [DataDog/dd-trace-js#4154]
The latest release of mongodb's native driver, 6.4.0, prompted a recent update in dd-trace to account for changes in how promises are handled. The update from dd-trace to account for these changes results in an unhandled rejection when Mongodb throws an exception during failover.

We were able to recreate this with controlled failover which consistently crashed the application until reverting either dd-trace below 5.6.0 or mongodb's native driver back to 6.3.0.

The combination of dd-traces latest upgrade with 6.4.0 seems to be a production risk.

Happy to share more details if helpful.

**Comment by avaly** [comment]
We've just ran into the same bug the other day. We were blaming it on the `mongodb` v6.4.0 refactors, but this error is only thrown when used together with `dd-trace` v5.6.0.

```
node:internal/process/promises:288
            triggerUncaughtException(err, true /* fromPromise */);
            ^

MongoServerError: The server is in quiesce mode and will shut down
    at Connection.sendCommand (/home/dev/temp/bugs/node_modules/.pnpm/mongodb@6.5.0/node_modules/mongodb/lib/cmap/connection.js:281:27)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Connection.command (/home/dev/temp/bugs/node_modules/.pnpm/mongodb@6.5.0/node_modules/mongodb/lib/cmap/connection.js:304:26) {
  errorResponse: {
    topologyVersion: {
      processId: ObjectId {
        buffer: Buffer(12) [Uint8Array] [
          101, 250, 192, 152,
          141, 166, 116, 131,
          244,   0, 213,  94
        ]
      },
      counter: 10
    },
    ok: 0,
    errmsg: 'The server is in quiesce mode and will shut down',
    code: 91,
    codeName: 'ShutdownInProgress',
    remainingQuiesceTimeMillis: 51552,
    '$clusterTime': {
      clusterTime: Timestamp { low: 2, high: 1710935456, unsigned: true },
      signature: {
        hash: Binary {
          sub_type: 0,
          buffer: Buffer(20) [Uint8Array] [
             73, 105,  51,  23, 186, 240,
             84, 185,  97,  56,  95,  97,
             57, 250, 181, 126,  43, 162,
            158, 185
          ],
          position: 20
        },
        keyId: Long { low: 1, high: 1702923123, unsigned: false }
      }
    },
    operationTime: Timestamp { low: 2, high: 1710935456, unsigned: true }
  },
  topologyVersion: {
    processId: ObjectId {
      buffer: Buffer(12) [Uint8Array] [
        101, 250, 192, 152,
        141, 166, 116, 131,
        244,   0, 213,  94
      ]
    },
    counter: 10
  },
  ok: 0,
  code: 91,
  codeName: 'ShutdownInProgress',
  remainingQuiesceTimeMillis: 51552,
  '$clusterTime': {
    clusterTime: Timestamp { low: 2, high: 1710935456, unsigned: true },
    signature: {
      hash: Binary {
        sub_type: 0,
        buffer: Buffer(20) [Uint8Array] [
           73, 105,  51,  23, 186, 240,
           84, 185,  97,  56,  95,  97,
           57, 250, 181, 126,  43, 162,
          158, 185
        ],
        position: 20
      },
      keyId: Long { low: 1, high: 1702923123, unsigned: false }
    }
  },
  operationTime: Timestamp { low: 2, high: 1710935456, unsigned: true },
  [Symbol(errorLabels)]: Set(0) {}
}
```
