### ISSUE TITLE
dd-trace can't init with node v20.15

### ISSUE THREAD

**Issue by Tarektouati** [DataDog/dd-trace-js#4550]
Hey 👋🏼 

We are experiencing an issue with dd-trace v5.17.0 in our application with node v20.15

We get this kind of error :
```
TypeError: An error occurred while loading instrumentation hook: Cannot read properties of undefined (reading '0')
    at isInsideNodeModules (node:internal/util:508:17)
    at showFlaggedDeprecation (node:buffer:178:8)
    at new Buffer (node:buffer:266:3)
    at alloc (webpack-internal:///(instrument)/../../node_modules/.pnpm/msgpack-lite@0.1.26/node_modules/msgpack-lite/lib/bufferish-buffer.js:18:10)
    at eval (webpack-internal:///(instrument)/../../node_modules/.pnpm/msgpack-lite@0.1.26/node_modules/msgpack-lite/lib/bufferish-buffer.js:6:54)
    at (instrument)/../../node_modules/.pnpm/msgpack-lite@0.1.26/node_modules/msgpack-lite/lib/bufferish-buffer.js (front/.next/server/vendor-chunks/msgpack-lite@0.1.26.js:59:1)
    at __webpack_require__ (front/.next/server/webpack-runtime.js:33:43)
    at eval (webpack-internal:///(instrument)/../../node_modules/.pnpm/msgpack-lite@0.1.26/node_modules/msgpack-lite/lib/bufferish.js:17:37)
    at (instrument)/../../node_modules/.pnpm/msgpack-lite@0.1.26/node_modules/msgpack-lite/lib/bufferish.js (/front/.next/server/vendor-chunks/msgpack-lite@0.1.26.js:89:1)
    at __webpack_require__ (front/.next/server/webpack-runtime.js:33:43)
    at eval (webpack-internal:///(instrument)/../../node_modules/.pnpm/msgpack-lite@0.1.26/node_modules/msgpack-lite/lib/ext-buffer.js:5:17)
    at (instrument)/../../node_modules/.pnpm/msgpack-lite@0.1.26/node_modules/msgpack-lite/lib/ext-buffer.js (front/.next/server/vendor-chunks/msgpack-lite@0.1.26.js:199:1)
    at __webpack_require__ (front/.next/server/webpack-runtime.js:33:43)
    at eval (webpack-internal:///(instrument)/../../node_modules/.pnpm/msgpack-lite@0.1.26/node_modules/msgpack-lite/lib/write-core.js:3:18)
    at (instrument)/../../node_modules/.pnpm/msgpack-lite@0.1.26/node_modules/msgpack-lite/lib/write-core.js (front/.next/server/vendor-chunks/msgpack-lite@0.1.26.js:279:1)
    at __webpack_require__ (front/.next/server/webpack-runtime.js:33:43)
    at eval (webpack-internal:///(instrument)/../../node_modules/.pnpm/msgpack-lite@0.1.26/node_modules/msgpack-lite/lib/encode-buffer.js:5:15)
    at (instrument)/../../node_modules/.pnpm/msgpack-lite@0.1.26/node_modules/msgpack-lite/lib/encode-buffer.js (front/.next/server/vendor-chunks/msgpack-lite@0.1.26.js:159:1)
    at __webpack_require__ (front/.next/server/webpack-runtime.js:33:43)
    at eval (webpack-internal:///(instrument)/../../node_modules/.pnpm/msgpack-lite@0.1.26/node_modules/msgpack-lite/lib/encode.js:5:21)
    at (instrument)/../../node_modules/.pnpm/msgpack-lite@0.1.26/node_modules/msgpack-lite/lib/encode.js (front/.next/server/vendor-chunks/msgpack-lite@0.1.26.js:179:1)
    at __webpack_require__ (front/.next/server/webpack-runtime.js:33:43)
    at eval (webpack-internal:///(instrument)/../../node_modules/.pnpm/msgpack-lite@0.1.26/node_modules/msgpack-lite/index.js:3:18)
    at (instrument)/../../node_modules/.pnpm/msgpack-lite@0.1.26/node_modules/msgpack-lite/index.js (front/.next/server/vendor-chunks/msgpack-lite@0.1.26.js:19:1)
    at __webpack_require__ (front/.next/server/webpack-runtime.js:33:43)
    at eval (webpack-internal:///(instrument)/../../node_modules/.pnpm/dd-trace@5.17.0_patch_hash=kg3ltbvalaupys75dltxj3lf7a/node_modules/dd-trace/packages/dd-trace/src/datastreams/writer.js:5:17)
    at (instrument)/../../node_modules/.pnpm/dd-trace@5.17.0_patch_hash=kg3ltbvalaupys75dltxj3lf7a/node_modules/dd-trace/packages/dd-trace/src/datastreams/writer.js (front/.next/server/vendor-chunks/dd-trace@5.17.0_patch_hash=kg3ltbvalaupys75dltxj3lf7a.js:3988:1)
```

the issue seems to be coming from `msgpack-lite` in [packages/dd-trace/src/datastreams/writer.js
](https://github.com/DataDog/dd-trace-js/blob/623d7f6c0a10df4dc2dd4935081e122ae858de09/packages/dd-trace/src/datastreams/writer.js#L5)
Thanks

**Comment by thebigbluebox** [comment]
Had to lock my Node 20 version to Node 20.15.1 instead of the latest release from yesterday which is now 20.16.0.

Realized my build was utilizing just Node 20 which was causing the issue which only happened overnight on 2024-07-25.

**Comment by unkhz** [comment]
Reproduced the problem with node version 20.15.1. Problem was fixed by updating to latest (20.17.0 today).
