### ISSUE TITLE
Error on large JSON request body

### ISSUE THREAD

**Issue by natethelen** [DataDog/dd-trace-js#4594]
We are seeing this error along with a 500 express error response whenever our JSON request body is too big.  We have configured our JSON parser to handle larger payloads, but we are not sure if it is possible to get dd-trace to not error on large JSON request bodies:

```
PayloadTooLargeError: request entity too large
    at readStream (/app/node_modules/.pnpm/raw-body@2.5.2/node_modules/raw-body/index.js:163:17)
    at getRawBody (/app/node_modules/.pnpm/raw-body@2.5.2/node_modules/raw-body/index.js:116:12)
    at read (/app/node_modules/.pnpm/body-parser@1.20.2/node_modules/body-parser/lib/read.js:79:3)
    at /app/node_modules/.pnpm/dd-trace@5.18.0/node_modules/dd-trace/packages/datadog-instrumentations/src/body-parser.js:30:17
    at read (/app/node_modules/.pnpm/dd-trace@5.18.0/node_modules/dd-trace/packages/datadog-shimmer/src/shimmer.js:26:21)
    at jsonParser (/app/node_modules/.pnpm/body-parser@1.20.2/node_modules/body-parser/lib/types/json.js:138:5)
    at newFn (/app/node_modules/.pnpm/express-async-errors@3.1.1_express@4.19.2/node_modules/express-async-errors/index.js:16:20)
    at /app/node_modules/.pnpm/dd-trace@5.18.0/node_modules/dd-trace/packages/datadog-instrumentations/src/router.js:50:25
    at newFn (/app/node_modules/.pnpm/dd-trace@5.18.0/node_modules/dd-trace/packages/datadog-shimmer/src/shimmer.js:26:21)
    at Layer.handle [as handle_request] (/app/node_modules/.pnpm/express@4.19.2/node_modules/express/lib/router/layer.js:95:5)
```

**Comment by natethelen** [comment]
Node 20.14, dd-trace 5.18.0

**Comment by natethelen** [comment]
FYI, setting DD_TRACING_ENABLED to false in the ENV didn't solve the problem.  Looks like instrumentation happens regardless.

**Comment by natethelen** [comment]
OK, we found the problem.  It wasn't dd-trace.  We had a hidden default limit body-parser added to the express middleware stack in a remote location in our code.
