### ISSUE TITLE
(node:67219) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.

### ISSUE THREAD

**Issue by aseemk** [DataDog/dd-trace-js#4758]
Hi there,

I've been getting these deprecation warnings from Node. When I run with `--trace-deprecation`, the stack trace points to this library:

```
(node:67219) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
    at node:punycode:3:9
    at BuiltinModule.compileForInternalLoader (node:internal/bootstrap/realm:399:7)
    at BuiltinModule.compileForPublicLoader (node:internal/bootstrap/realm:338:10)
    at loadBuiltinModule (node:internal/modules/helpers:108:7)
    at Module._load (node:internal/modules/cjs/loader:1099:17)
    at TracingChannel.traceSync (node:diagnostics_channel:315:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:217:24)
    at Module.require (node:internal/modules/cjs/loader:1339:12)
    at Hook.Module.require (/Users/aseemk/Projects/Portola/backend/node_modules/.pnpm/dd-trace@5.23.1/node_modules/dd-trace/packages/dd-trace/src/ritm.js:97:33)
    at require (node:internal/modules/helpers:135:16)
```

You can see I've even tried upgrading to (what I believe is) the latest `dd-trace` version 5.23.1, and I'm running the latest Node v22:

```
$ node --version
v22.9.0
```

I realize it looks like the _actual_ `punycode` usage is coming from within Node itself. But is there anything y'all know about or can help with here? Would love to get rid of this warning every time I run my app. =) Thanks!

**Comment by seanadkinson** [comment]
I came here looking for help with this issue as well:

```
(node:28977) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
    at node:punycode:3:9
    at BuiltinModule.compileForInternalLoader (node:internal/bootstrap/realm:399:7)
    at BuiltinModule.compileForPublicLoader (node:internal/bootstrap/realm:338:10)
    at loadBuiltinModule (node:internal/modules/helpers:108:7)
    at Function.Module._load (node:internal/modules/cjs/loader:1099:17)
    at TracingChannel.traceSync (node:diagnostics_channel:315:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:217:24)
    at Module.require (node:internal/modules/cjs/loader:1339:12)
    at Module.Hook.Module.require (/Users/seanadkinson/code/slt-server/node_modules/dd-trace/packages/dd-trace/src/ritm.js:97:33)
    at require (node:internal/modules/helpers:135:16)
```

However, because `dd-trace` is instrumenting code, it looks like the warning is coming from this library, but it may be masking the real culprit.

Indeed, when I comment out `dd-trace` from my project and re-run, I see that it is actually from the `whatwg-url` library:

```
(node:29457) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
    at node:punycode:3:9
    at BuiltinModule.compileForInternalLoader (node:internal/bootstrap/realm:399:7)
    at BuiltinModule.compileForPublicLoader (node:internal/bootstrap/realm:338:10)
    at loadBuiltinModule (node:internal/modules/helpers:108:7)
    at Function.Module._load (node:internal/modules/cjs/loader:1099:17)
    at TracingChannel.traceSync (node:diagnostics_channel:315:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:217:24)
    at Module.require (node:internal/modules/cjs/loader:1339:12)
    at require (node:internal/modules/helpers:135:16)
    at Object.<anonymous> (/Users/seanadkinson/code/slt-server/node_modules/whatwg-url/lib/url-state-machine.js:2:18)
```

So this likely isn't actually an issue with `dd-trace`.

**Comment by calidan-x** [comment]
Please fix the punycode warning

**Comment by jakub-g** [comment]
The issue happens because `dd-trace-js` transitively uses [a very outdated version of `whatwg-url`](https://github.com/DataDog/dd-trace-js/blob/29c26b0e85adc12ecff57371410c1afa33e2b8d2/yarn.lock#L3738-L3743). So the fix would be to update that dependency, or update `node-fetch` from 2.x to 3.x which no longer has this dep. (See https://github.com/node-fetch/node-fetch/issues/1797)

**Comment by jakub-g** [comment]
Temporary workaround: add `--disable-warning=DEP0040` to `NODE_OPTIONS`.

**Comment by andrewmclagan** [comment]
This works in pnpm setup:

```
{
  "name": "your-monorepo-root",
  "private": true,
  // ...other properties like scripts, devDependencies, etc.
  "pnpm": {
    "overrides": {
      "whatwg-url": "^14.0.0",
      "tr46": "^4.1.1"
    }
  }
}
```

**Comment by BridgeAR** [comment]
We do not ship `whatwg-url` and our dependencies are up to date.

As mentioned above, the reason why this is showing up as being Datadog related is our instrumentation. That just hides the actual caller.

Closing as resolved.
