### ISSUE TITLE
Support: Fastify v5

### ISSUE THREAD

**Issue by clarkenciel** [DataDog/dd-trace-js#4828]
Fastify v5 has [changed the signature for custom logger registration](https://fastify.dev/docs/latest/Guides/Migration-Guide-V5/#new-logger-constructor-signature).
`dd-trace`'s auto-instrumentation for fastify is now broken for fastify v5.

Here's an example error from our logs:
```
REDACTED/node_modules/.pnpm/fastify@5.0.0/node_modules/fastify/lib/logger.js:84
    throw new FST_ERR_LOG_LOGGER_AND_LOGGER_INSTANCE_PROVIDED()
          ^
FastifyError [Error]: You cannot provide both logger and loggerInstance. Please provide only one.
    at createLogger (REDACTED/node_modules/.pnpm/fastify@5.0.0/node_modules/fastify/lib/logger.js:84:11)
    at fastify (REDACTED/node_modules/.pnpm/fastify@5.0.0/node_modules/fastify/fastify.js:137:33)
    at fastify (REDACTED/node_modules/.pnpm/dd-trace@5.24.0/node_modules/dd-trace/packages/datadog-instrumentations/src/fastify.js:16:25)
    at fastify (REDACTED/node_modules/.pnpm/dd-trace@5.24.0/node_modules/dd-trace/packages/datadog-shimmer/src/shimmer.js:31:21)
  code: 'FST_ERR_LOG_LOGGER_AND_LOGGER_INSTANCE_PROVIDED',
  statusCode: 500
}
```

Library versions:
**Fastify**: 5.0.0
**dd-trace**: 5.24.0

**Comment by clarkenciel** [comment]
In the process of building a minimal reproduction I found that these failures were actually caused by a misconfiguration on my part. Closing.
