### ISSUE TITLE
[BUG]: dd-trace throws error for express v4 when esbuild plugin is used 

### ISSUE THREAD

**Issue by hoangnd25** [DataDog/dd-trace-js#5056]
### Tracer Version(s)

4.53.0

### Node.js Version(s)

22

### Bug Report

I got an error when updated dd-trace for lambda:

```
2024-12-23T22:13:28.217Z	undefined	ERROR	Uncaught Exception 	
{
    "errorType": "TypeError",
    "errorMessage": "hooks[payload.package] is not a function",
    "stack": [
        "TypeError: hooks[payload.package] is not a function",
        "    at /opt/nodejs/node_modules/dd-trace/packages/datadog-instrumentations/src/helpers/bundler-register.js:31:27",
        "    at Channel.publish (node:diagnostics_channel:143:9)",
        "    at ../../node_modules/express/node_modules/qs/lib/index.js (/node_modules/express/node_modules/qs/lib/index.js:26:12)",
        "    at __require3 (file:///var/task/functions/src/lambdas/api.mjs:21:50)",
        "    at <anonymous> (/node_modules/express/lib/middleware/query.js:19:10)",
        "    at ../../node_modules/express/lib/middleware/query.js (/node_modules/express/lib/middleware/query.js:51:7)",
        "    at __require3 (file:///var/task/functions/src/lambdas/api.mjs:21:50)",
        "    at ../../node_modules/express/lib/application.js (/node_modules/express/lib/application.js:20:13)",
        "    at __require3 (file:///var/task/functions/src/lambdas/api.mjs:21:50)",
        "    at ../../node_modules/express/lib/express.js (/node_modules/express/lib/express.js:18:13)"
    ]
}
```

The code is packaged using esbuild plugin. 
The issue seems be missing qs hook when its trying to register instrument for express v4.

It looks like qs hook as removed as part of this change to support express v5

https://github.com/DataDog/dd-trace-js/pull/4913

Packaged code generated by esbuild plugin

```

// node_modules/qs/lib/index.js
var require_lib5 = __commonJS({
  "node_modules/qs/lib/index.js"(exports2, module2) {
    (function() {
      "use strict";
      var stringify3 = require_stringify3();
      var parse = require_parse3();
      var formats = require_formats4();
      module2.exports = {
        formats,
        parse,
        stringify: stringify3
      };
    })(...arguments);
    {
      const dc = require_dc_polyfill();
      const ch = dc.channel("dd-trace:bundler:load");
      const mod = module2.exports;
      const payload = {
        module: mod,
        version: "6.11.2",
        package: "qs",
        path: "qs"
      };
      ch.publish(payload);
      module2.exports = payload.module;
    }
  }
});
```

### Bundling

ESBuild

**Comment by simon-id** [comment]
Thank you for reporting the issue, we're looking into it 👍

**Comment by tlhunter** [comment]
_(Note to self: Might be related to APMS-14365)_

**Comment by IlyasShabi** [comment]
Thanks for reporting the issue, I tried to reproduce it but no luck.

- Is it only with lambda or any express4/esbuild app ?
- Would you like to share a minimum reproducible application with package.json, app.js and esbuild config ?
 
Thank you

**Comment by hoangnd25** [comment]
Thanks for looking into this, really appreciate your quick responses.

I was able to replicate the issue here https://github.com/hoangnd25/sst-dd-trace (SST v2 + CDK + Lambda).

I just realised the issue is mismatching versions of dd-trace:
- Express v5 instrument change was introduced in dd-trace `v4.53.0` & `v5.29.0`
- Lambda function is using nodejs layer v118 https://github.com/DataDog/datadog-lambda-js/releases/tag/v9.118.0, that has the Express v5 instrument change (dd-trace `v4.53.0`).
- Esbuild was using plugin from local dd-trace `v5.28.0`, which dont have the the Express v5 change.

It seems to work after I update local dd-trace to `v5.29.0` or higher.

Downgrade lambda nodejs layer to v117 also worked as it uses dd-trace `v4.50.0`.

**Comment by IlyasShabi** [comment]
Hey @hoangnd25 Thanks for providing more details and the reproducible example.

The issue is indeed caused by incompatible versions of dd-trace. To fix it, we recommend updating your local dd-trace to version 5.29.0 or later, as it matches the changes in Lambda layer v118.

**Comment by simon-id** [comment]
@hoangnd25 Did you manage to solve your problem so we can close this issue ?
