### ISSUE TITLE
Graceful error message instead of throwing the exception when I do not have dd agent installed locally

### ISSUE THREAD

**Issue by manjufy** [DataDog/dd-trace-js#580]
Error:
`Error: Network error trying to reach the agent: connect ECONNREFUSED 127.0.0.1:8126`

My Environment.
OS: MacOs
Node Version: v10.13.0
dd-trace version: ^0.11.2

I get the following error
`Error: Network error trying to reach the agent: connect ECONNREFUSED 127.0.0.1:8126
    at ClientRequest.req.on.e (/Users/manju/Codes/pickles/ams-api/node_modules/dd-trace/src/platform/node/request.js:36:33)
    at scope.activate (/Users/manju/Codes/pickles/ams-api/node_modules/dd-trace/src/scope/new/base.js:48:19)
    at Scope._activate (/Users/manju/Codes/pickles/ams-api/node_modules/dd-trace/src/scope/new/scope.js:40:14)
    at Scope.activate (/Users/manju/Codes/pickles/ams-api/node_modules/dd-trace/src/scope/new/base.js:13:17)
    at ClientRequest.<anonymous> (/Users/manju/Codes/pickles/ams-api/node_modules/dd-trace/src/scope/new/base.js:47:20)
    at ClientRequest.emit (events.js:182:13)
    at ClientRequest.EventEmitter.emit (domain.js:442:20)
    at ClientRequest.req.emit (/Users/manju/Codes/pickles/ams-api/node_modules/dd-trace/src/plugins/http/client.js:93:21)
    at Socket.socketErrorListener (_http_client.js:391:9)
    at Socket.emit (events.js:187:15)
    at Socket.EventEmitter.emit (domain.js:442:20)
    at emitErrorNT (internal/streams/destroy.js:82:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)
    at process._tickCallback (internal/process/next_tick.js:63:19)`

I do not have DD agent installed locally, However, I would like to catch this exception and throw meaningful exception messaging like `DD Agent not configured locally`

**Comment by rochdev** [comment]
We do not throw any errors by design. Since the tracer is a cross cutting concern, it shouldn't cause the application to crash when something abnormal is detected that only affects tracing.

We could add an option to register a callback to capture errors from the tracer, or potentially emit events. The problem with that is that it would have a performance impact if it's done for every errors. Are you only interested in errors from the agent?

One thing to consider also is that this error could happen even if you have an agent installed. For example when the agent is starting/restarting.

**Comment by manjufy** [comment]
Hi, @rochdev Thanks for the update. yes, agree with you, by design it makes sense not to throw errors/exceptions that might cause the app to crash.
