### ISSUE TITLE
Webpack Warnings and Koa not tracing automatically

### ISSUE THREAD

**Issue by Shikkic** [DataDog/dd-trace-js#652]
I'm having two weird issues. All I've done is simply follow the [setup instructions](https://docs.datadoghq.com/tracing/setup/nodejs/).

The first issue is webpack generates quite a few bundling warnings for the module that don't make any sense to me. Which is super odd as there are quite a few modules in the project that cause no issue. The warnings look like this:

```
WARNING in ./node_modules/dd-trace/packages/dd-trace/src/native/metrics/SpanTracker.hpp 1:0
Module parse failed: Unexpected character '#' (1:0)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
> #pragma once
|
| #include <unordered_map>
 @ ./node_modules/dd-trace/packages/dd-trace/src sync ^.*\/.*$ ./native/metrics/SpanTracker.hpp
 @ ./node_modules/dd-trace/packages/dd-trace/src/instrumenter.js
 @ ./node_modules/dd-trace/packages/dd-trace/src/proxy.js
 @ ./node_modules/dd-trace/packages/dd-trace/index.js
 @ ./node_modules/dd-trace/index.js
 @ ./src/server/tracer.js
 @ ./src/server/index.ts

WARNING in ./node_modules/dd-trace/packages/dd-trace/src/native/metrics/Process.hpp 1:0
Module parse failed: Unexpected character '#' (1:0)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
> #pragma once
|
| #include <uv.h>
 @ ./node_modules/dd-trace/packages/dd-trace/src sync ^.*\/.*$ ./native/metrics/Process.hpp
 @ ./node_modules/dd-trace/packages/dd-trace/src/instrumenter.js
 @ ./node_modules/dd-trace/packages/dd-trace/src/proxy.js
 @ ./node_modules/dd-trace/packages/dd-trace/index.js
 @ ./node_modules/dd-trace/index.js
 @ ./src/server/tracer.js
 @ ./src/server/index.ts

WARNING in ./node_modules/dd-trace/packages/dd-trace/src/native/metrics/Histogram.hpp 1:0
Module parse failed: Unexpected character '#' (1:0)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
> #pragma once
|
| // windows.h defines min and max macros.
 @ ./node_modules/dd-trace/packages/dd-trace/src sync ^.*\/.*$ ./native/metrics/Histogram.hpp
 @ ./node_modules/dd-trace/packages/dd-trace/src/instrumenter.js
 @ ./node_modules/dd-trace/packages/dd-trace/src/proxy.js
 @ ./node_modules/dd-trace/packages/dd-trace/index.js
 @ ./node_modules/dd-trace/index.js
 @ ./src/server/tracer.js
 @ ./src/server/index.ts

WARNING in ./node_modules/dd-trace/packages/dd-trace/src/native/tdigest/NOTICES 1:4
Module parse failed: Unexpected token (1:4)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
> The Java version of the t-digest was originally authored by Ted Dunning
|
| A number of small but very helpful changes have been contributed by Adrien Grand (https://github.com/jpountz) to the Java version.
 @ ./node_modules/dd-trace/packages/dd-trace/src sync ^.*\/.*$ ./native/tdigest/NOTICES
 @ ./node_modules/dd-trace/packages/dd-trace/src/instrumenter.js
 @ ./node_modules/dd-trace/packages/dd-trace/src/proxy.js
 @ ./node_modules/dd-trace/packages/dd-trace/index.js
 @ ./node_modules/dd-trace/index.js
 @ ./src/server/tracer.js
 @ ./src/server/index.ts

WARNING in ./node_modules/dd-trace/packages/dd-trace/src/native/tdigest/LICENSE-2.0.txt 2:40
Module parse failed: Unexpected token (2:40)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
|
>                                  Apache License
|                            Version 2.0, January 2004
|                         http://www.apache.org/licenses/
 @ ./node_modules/dd-trace/packages/dd-trace/src sync ^.*\/.*$ ./native/tdigest/LICENSE-2.0.txt
 @ ./node_modules/dd-trace/packages/dd-trace/src/instrumenter.js
 @ ./node_modules/dd-trace/packages/dd-trace/src/proxy.js
 @ ./node_modules/dd-trace/packages/dd-trace/index.js
 @ ./node_modules/dd-trace/index.js
 @ ./src/server/tracer.js
 @ ./src/server/index.ts
```

I also get Buffer deprecation warnings at run time as well:

```
(node:59540) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
```

I thought maybe this was an error in our webpack setup but I'm not so sure. However these were just warnings so I thought I'd test out the tracing functionality anyway, in particular the `koa` support. I can see that on startup this [file](https://github.com/DataDog/dd-trace-js/blob/master/packages/datadog-plugin-koa/src/index.js) is generating logs that I place outside of the wrappers. However no logs I place in the wrappers get triggered, and no traces are being produced when I expect them to. No debug logs for the tracer are coming through either.

When I log the tracer after I initialize it with my settings I also notice something weird, it says NoopTracer:

```sh
tracer.init({
    enabled: true,
    debug: true,
    url: "redacted",
    service: 'my-service',
    env: "tst"
});
Tracer {
  _tracer: NoopTracer {
    _scopeManager: ScopeManager {},
    _scope: Scope {},
    _span: NoopSpan {}
  },
  _instrumenter: Instrumenter {
    _tracer: [Circular],
    _enabled: false,
    _names: Set {},
    _plugins: Map {},
    _instrumented: Map {}
  },
  _deprecate: [Function],
  default: [Circular],
  tracer: [Circular]
}
```

I'm not sure how to proceed?

Also FWIW I saw this [old issue](https://github.com/DataDog/dd-trace-js/issues/298) and made sure not to make the same mistake

* **Operation system:**
Alpine
* **Node version:**
 v12.6.0
* **Tracer version:**
14.0.0
* **Agent version:**
6.12.1-jmx

**Comment by Shikkic** [comment]
So I put more console logs in place and found out that the init method is throwing an error that is not being logged. I put a console log in this [catch statement](https://github.com/DataDog/dd-trace-js/blob/master/packages/dd-trace/src/proxy.js#L49). This is the error:

```
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type undefined
    at validateString (internal/validators.js:107:11)
    at Object.dirname (path.js:1121:5)
    at Object.service (webpack-internal:///./node_modules/dd-trace/packages/dd-trace/src/platform/node/service.js:10:20)
    at Tracer.init (webpack-internal:///./node_modules/dd-trace/packages/dd-trace/src/proxy.js:30:34)
    at eval (webpack-internal:///./src/server/tracer.js:5:49)
    at Module../src/server/tracer.js (/Users/dan/dev/advice-renderer/dist/js/adviceServer.js:8966:1)
    at __webpack_require__ (/Users/dan/dev/advice-renderer/dist/js/adviceServer.js:20:30)
    at eval (webpack-internal:///./src/server/index.ts:6:1)
    at Object../src/server/index.ts (/Users/dan/dev/advice-renderer/dist/js/adviceServer.js:8918:1)
    at __webpack_require__ (/Users/dan/dev/advice-renderer/dist/js/adviceServer.js:20:30)
```

Not sure if anyone knows what this means?

**Comment by Shikkic** [comment]
Welp, I changed the source mapping configuration in our webpack setup from:

```
-    devtool: "cheap-module-eval-source-map",
+    devtool: "inline-source-map"
```

Now the tracing appears to be working in the dev environment. From what I gathered it seems like in order for some of the core modules to work, module paths (or parent paths?) are important for instrumentation purposes, so without compiling a proper source map it's just not going to work.

The only question that remains is why does dd-trace-js generate so many loader warnings. Is it just because there is an excess of non-js files included that are loaded by webpack and we don't have a loader configured to ignore/deal with it?

**Comment by rochdev** [comment]
The tracer makes a lot of assumptions about the standard Node structure to work properly. If for example Webpack alters the file structure, or how `require` works, it could cause the tracer to break.

Could you describe what your build does?

**Comment by Shikkic** [comment]
Hey @rochdev. Yeah I'm sort of seeing that play out now, I've just hit nothing but issuess using webpack to bundle the code and dd-trace-js.

I'm not a front developer by trade, merely just helping my team instrument with datadog, however I believe we use webpack to bundle our code, assets, and node_modules into one file that gets executed. I think this makes some of the pathing assumptions in dd-trace not work correctly. Even after adding the source mapping the tracing for koa still doesn't work, it only works on native modules like `net` which I think was the exact issue this guy was having https://github.com/DataDog/dd-trace-js/issues/560.

I figured out why it wasn't instrumenting `koa`. The first reason is that the [getModules](https://github.com/DataDog/dd-trace-js/blob/master/packages/dd-trace/src/instrumenter.js#L237) method of the `Instrumentor` does not have `koa` in the `require.cache` Object. If I manually put it in there or import Koa _before_ the tracer, it will attempt to patch but error out on a module not found issue:

```sh
rror: Cannot find module './node_modules/koa/package.json'
    at webpackEmptyContext (/Users/dan/dev/advice-renderer/dist/js/adviceServer.js:26557:10)
    at getModules (/Users/dan/dev/advice-renderer/dist/js/adviceServer.js:27167:118)
    at /Users/dan/dev/advice-renderer/dist/js/adviceServer.js:27120:13
    at Array.forEach (<anonymous>)
    at Instrumenter._load (/Users/dan/dev/advice-renderer/dist/js/adviceServer.js:27119:12)
    at Instrumenter._set (/Users/dan/dev/advice-renderer/dist/js/adviceServer.js:27052:10)
    at /Users/dan/dev/advice-renderer/dist/js/adviceServer.js:26941:52
    at Array.forEach (<anonymous>)
    at Instrumenter.patch (/Users/dan/dev/advice-renderer/dist/js/adviceServer.js:26940:10)
    at Tracer.init (/Users/dan/dev/advice-renderer/dist/js/adviceServer.js:30072:30) {
  code: 'MODULE_NOT_FOUND'
```

What's weird is that `'./node_modules/koa/package.json'` does not work, but if I manually change [this require line](https://github.com/DataDog/dd-trace-js/blob/master/packages/dd-trace/src/instrumenter.js#L257) in the instrumentor to use this path `'koa/package.json'` it auto instruments as expected.

**Comment by Shikkic** [comment]
@rochdev Thanks again for helping me out, I was able to get it working! Happy to hear about the public plugin API, excited to see that come out. 

If anyone else is reading this and is wondering what the final solution looks like that worked for us (We used TypeScript so we needed have it in a separate file and exported):

```js
// tracer.js: The tracer is initialized in this seperate file to avoid hoisting.

const tracer = require("dd-trace");

// Disable automated plugin instrumentation as to not break anything
tracer.init({ plugins: false });

// Explicitly enable the 'net' and 'http' package for tracing as we know they're safe
tracer.use("net", { enabled: true });
tracer.use("http", { enabled: true });

// Require the necessary modules we want to instrument
const Koa = require("koa");
const KoaRouter = require("koa-router");

// Require the koa and koa-router adapters used for patching. Returns an Array of adapaters.
const koaPlugin = require("dd-trace/packages/datadog-plugin-koa/src");

// Filter the array of adapters to return the correlated module export we need
// (The adapater version for validation is coming from "dd-trace/packages/datadog-plugin-koa/src"
// It tells us the versions it supoprts patching for).
const koaAdapters = koaPlugin.filter(adapter => {
    return (
        adapter.name === "koa" &&
        adapter.versions.some(version => {
            return version === ">=2";
        })
    );
});
const routerAdapters = koaPlugin.filter(adapter => {
    return (
        adapter.name === "koa-router" &&
        adapter.versions.some(version => {
            return version === ">=7";
        })
    );
});

// For each module call it's patch function, monkey patching the module methods with tracing
koaAdapters.forEach(adapter => adapter.patch.call(tracer._instrumenter, Koa, tracer, {}));
routerAdapters.forEach(adapter => adapter.patch.call(tracer._instrumenter, KoaRouter, tracer, {}));

export default tracer;
```

Going to close this now, thanks again!
