### ISSUE TITLE
DD Trace causing runtime error due to type error bug

### ISSUE THREAD

**Issue by blugavere** [DataDog/dd-trace-js#660]
**Describe the bug**

see below stack trace

**Environment**

    "dd-trace": "0.14.0",
    "express-graphql": "0.9.0",
    "graphql": "14.5.1",
    "graphql-tools": "4.0.5",

* **Operation system:**
* **Node version:**
* **Tracer version:**
* **Agent version:**

        "TypeError: Cannot read property 'apply' of undefined",
        "    at /srv/app/node_modules/dd-trace/packages/datadog-plugin-graphql/src/index.js:342:32",
        "    at resolveWithTrace (/srv/app/node_modules/dd-trace/packages/datadog-plugin-graphql/src/index.js:137:18)",
        "    at resolveFieldValueOrError (/srv/app/node_modules/graphql/execution/execute.js:467:18)",
        "    at resolveField (/srv/app/node_modules/graphql/execution/execute.js:434:16)",
        "    at executeFields (/srv/app/node_modules/graphql/execution/execute.js:275:18)",
        "    at executeOperation (/srv/app/node_modules/graphql/execution/execute.js:219:122)",
        "    at executeImpl (/srv/app/node_modules/graphql/execution/execute.js:104:14)",
        "    at execute (/srv/app/node_modules/graphql/execution/execute.js:64:35)",
        "    at scope.activate (/srv/app/node_modules/dd-trace/packages/datadog-plugin-graphql/src/index.js:162:50)",
        "    at Scope._activate (/srv/app/node_modules/dd-trace/packages/dd-trace/src/scope/base.js:44:14)",
        "    at Scope.activate (/srv/app/node_modules/dd-trace/packages/dd-trace/src/scope/base.js:13:17)",
        "    at call (/srv/app/node_modules/dd-trace/packages/datadog-plugin-graphql/src/index.js:162:26)",
        "    at executeWithTrace (/srv/app/node_modules/dd-trace/packages/datadog-plugin-graphql/src/index.js:38:14)",
        "    at getGraphQLParams.then.then.optionsData (/srv/app/node_modules/express-graphql/index.js:152:16)",
        "    at <anonymous>"

**Comment by XBeg9** [comment]
Same here, trying to debug and find what's causing the issue. Could you please downgrade to graphql 14.4.*

**Comment by xzyfer** [comment]
Just ran into this issue which resulted in a minor site outage. I can confirm the bug is the result of updating `graphql` 14.4.2 -> 14.5.3.
