### ISSUE TITLE
dd-trace crash with tedious

### ISSUE THREAD

**Issue by jermeo** [DataDog/dd-trace-js#661]
**Describe the bug**

Hello,

When we use the dd-agent, we have an error which is throw by the plugin datadog-plugin-tedious. If the agent is disable, no problem. We use tedious through mssql library.

* Sample of code:

```
const tracer = require('dd-trace').init({})
const sql = require('mssql')

const test = async () => {
    try {
        const pool = await sql.connect('mssql://########:########@########/########')
        const request = new sql.Request(pool)
        request.input('myParam', sql.VarChar, '1')
        const result = await request.execute('dbo.#######################')
        console.log(result.recordsets[0].length) 
    } catch (err) {
        console.error(err)
    }
}

test()
```
* Error stack:
```
TypeError: Cannot read property 'value' of undefined
    at getQuery (/home/chuck/git/myProject/test/node_modules/dd-trace/packages/datadog-plugin-tedious/src/index.js:89:24)
    at ConnectionWithTrace.makeRequestWithTrace (/home/chuck/git/myProject/test/node_modules/dd-trace/packages/datadog-plugin-tedious/src/index.js:42:21)
    at ConnectionWithTrace.callProcedure (/home/chuck/git/myProject/test/node_modules/tedious/lib/connection.js:1529:10)
    at parent.acquire (/home/chuck/git/myProject/test/node_modules/mssql/lib/tedious.js:1105:20)
    at _acquire.then.connection (/home/chuck/git/myProject/test/node_modules/mssql/lib/base.js:175:42)
    at process._tickCallback (internal/process/next_tick.js:68:7)

```
Statement is undefined in this code:

```
function getQuery (request) {
  if (request.parameters) {
    if (request.parameters.length === 0) {
      return request.sqlTextOrProcedure
    } else {
      const statement = request.parametersByName.statement || request.parametersByName.stmt
      return statement.value
    }
  }
}
```

Regards

**Environment**

* **Operation system:** Linux Ubuntu 19
* **Node version:** 10.16.3
* **Tracer version:** 0.14.0
* **Agent version:** v6

**Comment by jermeo** [comment]
Thanks rishabh for this rapid fix ! We are waiting the next release.
Kind regards

**Comment by jermeo** [comment]
Very thanks for this fix !
