### ISSUE TITLE
Tracer requires a package.json

### ISSUE THREAD

**Issue by kevinoneill** [DataDog/dd-trace-js#72]
On initialise tracer attempts to load a package.json file from the `cwd`.  My application deployments don't include a `package.json` so the application fails to start.

```
/xxx/node_modules/dd-trace/src/platform/node/load.js:12
  this._service = pkg.name
                      ^
 TypeError: Cannot read property 'name' of undefined
    at Object.load (/xxx/node_modules/dd-trace/src/platform/node/load.js:12:23)
    at TracerProxy.init (/xxx/node_modules/dd-trace/src/proxy.js:19:16)
    at Object.&lt;anonymous&gt; (/xxx/lib/index.js:3:21)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:188:16)
```

The issue stems from `this.service = coalesce(options.service, platform.env('DD_SERVICE_NAME'), platform.service())`. Being a function `coalesce` is not lazy so all the arguments are evaluated before , the only work around is to add a package.json to make it happy.

Adding a default option or using lazy evaluation (e.g. by using the `||` operator) would solve the issue.

**Comment by rochdev** [comment]
@kevinoneill released in `v0.1.4`
