### ISSUE TITLE
TypeError: Cannot read property 'isSampled' of undefined

### ISSUE THREAD

**Issue by gloutsch** [DataDog/dd-trace-js#768]
**Describe the bug**

The js tracer does not find a sample rule (that does not exists) and can't send traces to the agent :(
I have an express app, followed the instructions https://app.datadoghq.com/apm/docs?architecture=host-based&language=node for the typescript version.

at the top of the entrypoint script (`server.ts`) : 
```
import './tracer'
```

`tracer.ts`
```
import tracer from 'dd-trace'
tracer.init()
export default tracer
```

stacktrace :
```
 TypeError: Cannot read property 'isSampled' of undefined
     at PrioritySampler._isSampledByRule (/opt/app/node_modules/dd-trace/packages/dd-trace/src/priority_s\
ampler.js:107:25)
     at PrioritySampler.isSampled (/opt/app/node_modules/dd-trace/packages/dd-trace/src/priority_sampler.\
js:46:14)
     at PrioritySampler.sample (/opt/app/node_modules/dd-trace/packages/dd-trace/src/priority_sampler.js:\
62:39)
     at SpanProcessor.process (/opt/app/node_modules/dd-trace/packages/dd-trace/src/span_processor.js:15:\
29)
     at DatadogSpan._finish (/opt/app/node_modules/dd-trace/packages/dd-trace/src/opentracing/span.js:116\
:21)
     at DatadogSpan.Span.finish (/opt/app/node_modules/opentracing/src/span.ts:169:14)
     at finish (/opt/app/node_modules/dd-trace/packages/dd-trace/src/plugins/util/tx.js:51:8)
     at Socket.<anonymous> (/opt/app/node_modules/dd-trace/packages/dd-trace/src/plugins/util/tx.js:25:5)
     at /opt/app/node_modules/dd-trace/packages/dd-trace/src/scope/base.js:50:19
     at Scope._activate (/opt/app/node_modules/dd-trace/packages/dd-trace/src/scope/async_hooks.js:51:14)
     at Scope.activate (/opt/app/node_modules/dd-trace/packages/dd-trace/src/scope/base.js:12:19)
     at Socket.bound (/opt/app/node_modules/dd-trace/packages/dd-trace/src/scope/base.js:49:20)
     at Object.onceWrapper (events.js:284:20)
     at Socket.emit (events.js:201:15)
     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1040:10)
```

`rule` in `priority_sampler.js` is `-1` 

I have also tried to set the `sampleRate` :
```
tracer.init({sampleRate: 0.5})
```

But I get the same error.

**Environment**

`express@4.17.1`
`redis@2.8.0`
`mongoose@5.7.1`

* **Operation system:**

`Ubuntu 16.04.6 LTS`

* **Node version:**

`v12.0.0`

* **Tracer version:**

`0.16.1`

* **Agent version:**

`6.15.0`

**Comment by rochdev** [comment]
Is the snippet above the actual code you are running? I cannot seem to reproduce the issue.

**Comment by gloutsch** [comment]
hey @rochdev, sorry for the late reply.
I just summarized how our environment is defined but it's not the real application.
I'll try to create a reproducible sample app.

**Comment by rochdev** [comment]
Can you also provide the value of `tracer._tracer._prioritySampler._rules` when the error occurs? This will be easier than setting up a reproduction application and might give me an idea of what could be causing the issue.

**Comment by andrewsouthard1** [comment]
Hey @gloutsch - please let us know if you're still having this issue otherwise we'll close for now.

**Comment by gloutsch** [comment]
Hi,
Sorry I have no longer access to the environment.
I remember that we had weird issues on this application because some javascript librairies do monkey patching on common functions. So it's probably not related to the dd js tracer.
Thank you for closing this.
