### ISSUE TITLE
Node.js cassandra-driver 4.4.0: Instrumentation fails

### ISSUE THREAD

**Issue by robaca** [DataDog/dd-trace-js#935]
**Describe the bug**

During startup instrumentation for the cassandra-driver (4.4.0) fails with the following error stack:

```
Error: Expected object [object Object] to contain method _innerExecute.
    at /.../node_modules/dd-trace/packages/dd-trace/src/instrumenter.js:72:17
    at Array.forEach (<anonymous>)
    at /.../node_modules/dd-trace/packages/dd-trace/src/instrumenter.js:70:13
    at Array.forEach (<anonymous>)
    at Instrumenter.wrap (/.../node_modules/dd-trace/packages/dd-trace/src/instrumenter.js:69:13)
    at Instrumenter.patch (/.../node_modules/dd-trace/packages/datadog-plugin-cassandra-driver/src/index.js:154:12)
    at Instrumenter.patch /.../node_modules/dd-trace/packages/dd-trace/src/instrumenter.js:134:36)
    at /.../node_modules/dd-trace/packages/dd-trace/src/platform/node/loader.js:100:52
    at Array.forEach (<anonymous>)
    at /.../node_modules/dd-trace/packages/dd-trace/src/platform/node/loader.js:96:14
```

**Environment**

* **Operation system:** Linux/NixOS
* **Node version:** 12.13.0
* **Tracer version:** 0.16.3
* **Agent version:** -

**Comment by robaca** [comment]
I updated the dd-trace version to 0.20.1 and now it's working fine
