### ISSUE TITLE
DD-trace exception

### ISSUE THREAD

**Issue by sisfm** [DataDog/dd-trace-js#955]
**Getting Exception on nodejs**

(node:17)   UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'filter' of   undefined
--
at Object.request   (/usr/app/ms-dollar/node_modules/@common/node-logger/src/dataDogTrace.js:27:49)
at finish   (/usr/app/ms-dollar/node_modules/dd-trace/packages/dd-trace/src/plugins/util/web.js:237:29)
at ServerResponse.res._datadog_end   (/usr/app/ms-dollar/node_modules/dd-trace/packages/dd-trace/src/plugins/util/web.js:270:5)
at scope.activate   (/usr/app/ms-dollar/node_modules/dd-trace/packages/dd-trace/src/scope/base.js:54:19)
at Scope._activate   (/usr/app/ms-dollar/node_modules/dd-trace/packages/dd-trace/src/scope/async_hooks.js:51:14)
at Scope.activate   (/usr/app/ms-dollar/node_modules/dd-trace/packages/dd-trace/src/scope/base.js:12:19)
at ServerResponse.bound [as _datadog_end]   (/usr/app/ms-dollar/node_modules/dd-trace/packages/dd-trace/src/scope/base.js:53:20)
at ServerResponse.res.end   (/usr/app/ms-dollar/node_modules/express-winston/index.js:241:17)
at scope.activate   (/usr/app/ms-dollar/node_modules/dd-trace/packages/dd-trace/src/scope/base.js:54:19)
at Scope._activate   (/usr/app/ms-dollar/node_modules/dd-trace/packages/dd-trace/src/scope/async_hooks.js:51:14)
at Scope.activate   (/usr/app/ms-dollar/node_modules/dd-trace/packages/dd-trace/src/scope/base.js:12:19)
at ServerResponse.bound   (/usr/app/ms-dollar/node_modules/dd-trace/packages/dd-trace/src/scope/base.js:53:20)
at ServerResponse.send   (/usr/app/ms-dollar/node_modules/express/lib/response.js:221:10)
at ServerResponse.json   (/usr/app/ms-dollar/node_modules/express/lib/response.js:267:15)
at DollarController.getOrangeQuotation   (/usr/app/ms-dollar/src/application/controllers/dollar.controller.js:152:9)
at process._tickCallback   (internal/process/next_tick.js:68:7)
(node:17)   UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error   originated either by throwing inside of an async function without a catch   block, or by rejecting a promise which was not handled with .catch().   (rejection id: 703)

**Env:Prod**

* **OS: 10.16.0-alpine:**
* **Node version: v10.16.0**
* **Tracer version: dd-trace@0.20.3**
* **Agent version: v7.19.0**

**Comment by rochdev** [comment]
Can you provide the context of the error? So basically:

- When does it happen?
- How is the tracer configured/initialized?
- It looks like the error may be coming from a module that is using the tracer and not the tracer. Can you provide the code from where the error is being thrown?

**Comment by andrewsouthard1** [comment]
Hey @sisfm - closing this for now but please let us know if you're still seeing issue.
