### ISSUE TITLE
dd-trace causing node cluster worker crashes with mongodb 

### ISSUE THREAD

**Issue by Throckmortra** [DataDog/dd-trace-js#971]
**Describe the bug**

When using dd-trace in our nodejs server, long-lived ETL jobs are getting crashes related to mongodb. We believe async_hooks does not play nice with mongodb lib. We have disabled mongodb-core and still seeing this issue. Ironically, using the newest beta build that @bengl created for us does fix our previous memory leak issues from #959 but this issue is also a show stopper for our dd-trace adoption. 

**Environment**

* **Operation system:**
node:12-buster container running on Amazon Linux 1
* **Node version:**
v12.17.0
* **Tracer version:**
0.21.0-beta.1 (thanks Brian!)
* **Agent version:**
7.16.0

```
/usr/src/app/node_modules/mongodb/lib/core/cursor.js:35
      throw err;
      ^

MongoNetworkError: connection 89 to redacted timed out
    at TLSSocket.<anonymous> (/usr/src/app/node_modules/mongodb/lib/core/connection/connection.js:355:7)
    at /usr/src/app/node_modules/dd-trace/packages/dd-trace/src/scope/base.js:54:19
    at async_hooks.js:263:14
    at AsyncResource.runInAsyncScope (async_hooks.js:186:9)
    at AsyncLocalStorage.run (async_hooks.js:261:21)
    at Scope._activate (/usr/src/app/node_modules/dd-trace/packages/dd-trace/src/scope/async_local_storage.js:28:26)
    at Scope.activate (/usr/src/app/node_modules/dd-trace/packages/dd-trace/src/scope/base.js:12:19)
    at TLSSocket.bound (/usr/src/app/node_modules/dd-trace/packages/dd-trace/src/scope/base.js:53:20)
    at Object.onceWrapper (events.js:421:28)
    at TLSSocket.emit (events.js:315:20)
    at TLSSocket.EventEmitter.emit (domain.js:482:12)
    at TLSSocket.Socket._onTimeout (net.js:481:8)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
Emitted 'error' event on ChangeStream instance at:
    at ChangeStream.<anonymous> (/usr/src/app/node_modules/mongoose/lib/cursor/ChangeStream.js:38:51)
    at ChangeStream.emit (events.js:315:20)
    at ChangeStream.EventEmitter.emit (domain.js:482:12)
    at processNewChange (/usr/src/app/node_modules/mongodb/lib/change_stream.js:535:43)
    at ChangeStreamCursor.<anonymous> (/usr/src/app/node_modules/mongodb/lib/change_stream.js:420:5)
    at ChangeStreamCursor.emit (events.js:315:20)
    at ChangeStreamCursor.EventEmitter.emit (domain.js:482:12)
    at /usr/src/app/node_modules/mongodb/lib/core/cursor.js:344:16
    at handleCallback (/usr/src/app/node_modules/mongodb/lib/core/cursor.js:32:5)
    at /usr/src/app/node_modules/mongodb/lib/core/cursor.js:790:16
    at /usr/src/app/node_modules/mongodb/lib/change_stream.js:335:9
    at Object.queryCallback [as cb] (/usr/src/app/node_modules/mongodb/lib/core/wireprotocol/get_more.js:19:21)
    at Connection.flush (/usr/src/app/node_modules/mongodb/lib/core/connection/connection.js:206:18)
    at connectionFailureHandler (/usr/src/app/node_modules/mongodb/lib/core/connection/pool.js:259:10)
    at Connection.Pool._connectionTimeoutHandler (/usr/src/app/node_modules/mongodb/lib/core/connection/pool.js:188:5)
    at Connection.emit (events.js:315:20)
    at Connection.EventEmitter.emit (domain.js:482:12)
    at TLSSocket.<anonymous> (/usr/src/app/node_modules/mongodb/lib/core/connection/connection.js:353:10)
    at /usr/src/app/node_modules/dd-trace/packages/dd-trace/src/scope/base.js:54:19
    [... lines matching original stack trace ...]
    at AsyncLocalStorage.run (async_hooks.js:261:21) {
  [Symbol(mongoErrorContextSymbol)]: { isGetMore: true }
}
Worker 556 died with code: null, and signal: SIGSEGV
Starting a new worker
```

**Comment by rochdev** [comment]
Can you try with the latest Node 14? Also, is this something that is reproducible in a small snippet?

**Comment by Throckmortra** [comment]
this is difficult to reproduce because we can't get it to happen on demand. It is intermittent. Node 14 isn't an option for us until LTS arrives but we can see about testing

**Comment by bengl** [comment]
@Throckmortra it may be worth giving [`segfault-raub`](https://www.npmjs.com/package/segfault-raub) a try. Just add it to your dependencies, then insert the following right before `require('dd-trace')`:

```js
require('segfault-raub`)
```

This will print a C++ stack to `stderr` when a `SIGSEGV` happens. If we can get that, we can probably find the C++ function that's misbehaving and work from there.

**Comment by andrewsouthard1** [comment]
@Throckmortra - just to confirm was this something you are able to run? Are you still experiencing this issue?

**Comment by Throckmortra** [comment]
@andrewsouthard1 I was on vacation last week. I'll follow up with our engineers today and see if they want to try this out

**Comment by Throckmortra** [comment]
Just to update here, I haven't seen this error since we moved to unified Mongo Topology. We only had a window of 2-3 days to look for this before we had to turn APM off again due to performance issues (this time affecting CPU resources instead of memory) 

We are now doing some testing with different dd-trace and node versions again. Will update if we run into any crashes

**Comment by Throckmortra** [comment]
Another update: Haven't seen this issue since moving to unified Mongo topology
